### ISSUE TITLE
Sorting out release page

### ISSUE THREAD

**Issue by xtemp09** [brechtsanders/winlibs_mingw#103]
Could you somehow sort https://github.com/brechtsanders/winlibs_mingw/releases page historically?

The latest releases are somewhere in the middle of the page. [This post](https://github.community/t/release-page-not-sorting-correctly/121002/2) might help to sort out this problem..

**Comment by brechtsanders** [comment]
It annoys me too that newer prereleases appear before the latest release version.

That is why I provide proper download information on https://winlibs.com/

From the link you sent I can't figure out anything to help me fix the order.
Any suggestions are welcome.

**Comment by xtemp09** [comment]
I don't know how to solve the problem either. ='(
