### ISSUE TITLE
mingw64\bin\not.exe detected as malware

### ISSUE THREAD

**Issue by gdementen** [brechtsanders/winlibs_mingw#105]
FWIW, that file was flagged as malware by our antivirus, while being installed automatically by [Nuitka/nuitka](https://github.com/Nuitka/Nuitka)

Threat Names: Artemis!A77554605DF8
Detecting Product Names: McAfee Endpoint Security

Target Filename <path>\gcc\x86_64\11.2.0-12.0.1-9.0.0-r1\mingw64\bin\not.exe

https://www.virustotal.com/gui/file/e740d0cce9340348b9fe447595561b239c5ab3706b6a3591a5317d974f239559/detection

**Comment by brechtsanders** [comment]
That looks like an old version.
Does your antivirus have the same issue with the latest version?

In the past I have seen antivirus software give false positives on build tools several times.
This is understandable as compilers and linkers actually treat code as data and then write that to files that are execurable. It's a virusscanner's job to be suspicious about that.

If you get a virus alert it's best to pass it through multiple scanners (e.g. via https://www.virustotal.com/) to determine if it's a false positive. If others don't see an issue you can always submit it as a false positive report  to the vendor of your antivirus.

**Comment by gdementen** [comment]
Thanks for your answer. As mentioned, this is installed automatically for me so I don't control the version and I did check it on virus total (see that link above) and it was detected by several scanners.

BTW: what is not.exe supposed to be? I could not find any information on this.

**Comment by brechtsanders** [comment]
I believe `not.exe` is like `true.exe` and `false.exe`.
It switch the result code between zero and non-zero.
When I run `not false; echo $?` the result is zero = true.
When I run `not true; echo $?` the result is non-zero = false.
I only see `not.exe` in the packages that include LLVM, so I assume that's where it comes from.

Sorry, I overlooked your link.
Here's the scan of the one from LLVM 14.0.3: https://www.virustotal.com/gui/file/09dece36268bcee3a6915fb398a77fd316d5d99cb9f1759082bd915015255808

It only has a single antivirus hit (Gridinsoft) so I assume it's a false positive.

**Comment by gdementen** [comment]
Thanks for your answer and looking into this

**Comment by kayhayen** [comment]
I will try and update to latest winlibs, but it will probably only be in 0.8.1 as it's too late for 0.8
