### ISSUE TITLE
A guide, tips and notices on building GCC for Windows  

### ISSUE THREAD

**Issue by BoQsc** [brechtsanders/winlibs_mingw#11]
I'd like to have stable, portable and low storage build.
I saw that latest winlibs release is taking way over 180mb in compressed file.
Uncompressed it takes over 1.58GB of hard drive space.

I expected GCC compiler to be as small utility program - around 20mb uncompressed.  
What is happening? Are my expectations doomed?

Why we are having such unimaginable sizes for such trivial thing as GNU compiler collection?
http://winlibs.com/#download-release

 1.58GB is a size of a complete operating system! It's crazy, it is insane.   
What is happening to the efficiency!  
All I wanted is to compile a small Hello world program in C. 

Now I feel the need to compile GCC myself, in a hope to if it is possible to make it more portable for my usecase of simple C language.

**Comment by BoQsc** [comment]
Related issue: https://github.com/brechtsanders/winlibs_mingw/issues/1

**Comment by brechtsanders** [comment]
Note that GCC alone isn't enough, you also need Binutils and MinGW-w64, so I really doubt that would fit in just 20MB...

The goal of winlibs.com is to have all possible features included, not to build a minimal compiler.

I recently also added LLVM and CLang, which - I have to admit - made the result huge.
Maybe I could release with and without LLVM/CLang next time so you can choose, though I really wanted to avoid confusing people about which download they really need.

**Comment by BoQsc** [comment]
> Note that GCC alone isn't enough, you also need Binutils and MinGW-w64, so I really doubt that would fit in just 20MB...
> 
> The goal of winlibs.com is to have all possible features included, not to build a minimal compiler.
> 
> I recently also added LLVM and CLang, which - I have to admit - made the result huge.
> Maybe I could release with and without LLVM/CLang next time so you can choose, though I really wanted to avoid confusing people about which download they really need.

@brechtsanders There is really not much of a difference between ~180mb compressed archive and ~50mb compressed archive. Both of them are too large for portable use once extracted.

I'd also go for simplicity and releases only with LLVM and CLang.  
Although it is still hard to handle the fact that uncompressed release is getting close to 2GB.

**Comment by brechtsanders** [comment]
Storage on personal computers isn't as expensive as it used to be, but neither is download volume.
So I am willing to consider the following options for the future:
- switching downloads to .zip format
- splitting downloads into a main part with essentials (GCC, MinGW-w64, binutils, GDB for Win32/Win64)
- creating seperate downloads for add-ons like:
  + LLCM+CLang
  + GCC and binutils targetting other platforms (like AVR/Arduino)

That would require me to rethink the versioning system (which is currently just the component versions combined).

**Comment by zeitbit** [comment]
@brechtsanders
> Maybe I could release with and without LLVM/CLang next time so you can choose

Yes, please.

**Comment by brechtsanders** [comment]
I just added downloads for the latest release that don't have additional LLVM and assemblers.
And there's a choice between `.7z` and `.zip` files.
Enjoy.

**Comment by longnguyen2004** [comment]
Does the LLVM release includes all the import libraries and stuff? That would be huge to distribute. You only need to package the compiler itself. Have a look at [llvm-mingw](https://github.com/mstorsjo/llvm-mingw)
