### ISSUE TITLE
Include GNU Modula2

### ISSUE THREAD

**Issue by 3oheicrw** [brechtsanders/winlibs_mingw#110]
Since GM2 will be part of GCC source tree from GCC 12 onwards, I suggest we should ship it too (alongside gobjc, gfortran,...).

https://www.nongnu.org/gm2/release.html

**Comment by brechtsanders** [comment]
I couldn't find any indication of Modula2 support in the GCC 12.1.0 sources.

**Comment by 3oheicrw** [comment]
> I couldn't find any indication of Modula2 support in the GCC 12.1.0 sources.

It will definitely included in future GCC versions. When it's included, could you make sure you will ship it?

**Comment by 3oheicrw** [comment]
It's in the process of migrating into the GCC git tree: https://www.nongnu.org/gm2/12/development.html

**Comment by brechtsanders** [comment]
Okay, I will keep an eye out for this.

**Comment by 3oheicrw** [comment]
> Okay, I will keep an eye out for this.

Thank you.

**Comment by 3oheicrw** [comment]
gm2 will be part of gcc 13: https://lists.gnu.org/archive/html/gm2/2022-07/msg00010.html

**Comment by 3oheicrw** [comment]
Sorry everyone. I was wrong. GNU Modula-2 seems to be Unix-like only and will not work on Windows, even with Cygwin.

A few more details:

The repository the document used is now invalid: https://www.nongnu.org/gm2/11/building_on_gcc_11.html
This mailing list discussion addressed it: https://lists.gnu.org/archive/html/gm2/2022-07/msg00008.html
But it's not really, the repo at http://floppsie.comp.glam.ac.uk/git/gm2 is very unstable, it will stuck at 48% when cloning.

So everyone, we will clone from gcc's github mirror, the branch devel/modula-2:

git clone -b devel/modula-2 https://github.com/gcc-mirror/gcc gm2-floppsie

The configuration process is successfull but the actual building failed with no rules for target!
