### ISSUE TITLE
Include libc++ on GCC+LLVM builds?

### ISSUE THREAD

**Issue by jpgpng** [brechtsanders/winlibs_mingw#113]
Currently there is only libstdc++ available. Modern gcc now allows linking with libc++ and clang has support to choose which stdlib to link with out of the box and with ease.

**Comment by jpgpng** [comment]
Doesn't use all LLVM tools like this but include a bit more LLVM tools and libraries (compiler-rt, libc++, libunwind,...) alongside GNU ones please! https://github.com/mstorsjo/llvm-mingw

(I personally hate LLD so much, it breaks linking process on many software I tried to build, GNU ld is much better, I don't like project go that extreme to be LLVM-only like that at all).

**Comment by jpgpng** [comment]
> Are you sure GCC can link with LLVM's standard library on a MinGW-w64 platform?

I'm not sure. But from libc++ homepage they tell we could have g++ to link with libc++ with:

```
$ g++ -nostdinc++ -nodefaultlibs           \
      -isystem <install>/include/c++/v1    \
      -L <install>/lib                     \
      -Wl,-rpath,<install>/lib             \
      -lc++ -lc++abi -lm -lc -lgcc_s -lgcc \
      test.cpp
```

(command taken from there: https://libcxx.llvm.org/UsingLibcxx.html#using-a-custom-built-libc)

> So far I haven't even been able to built LLVM's standard library with GCC+MinGW-w64...

I think you have to build clang first and use that clang to build libc++: https://libcxx.llvm.org/BuildingLibcxx.html#cmake-ninja-mingw

**Comment by 3oheicrw** [comment]
So what he is proposing is nothing change to the current GCC + LLVM builds other than also use Clang to build libc++ and ship it with the current distribution as an alternative to libstdc++? The default stdlib of Clang still be libstdc++ and libc++ could be used by specifying -stdlib=libc++ isn't it?

**Comment by jpgpng** [comment]
> So what he is proposing is nothing change to the current GCC + LLVM builds other than also use our Clang to build libc++ and ship it with the current distribution as an alternative to libstdc++? The default stdlib of Clang still be libstdc++ and libc++ could be used by specifying -stdlib=libc++ isn't it?

Yes, I don't want to use all llvm tools like llvm-mingw. I hate lld.

**Comment by brechtsanders** [comment]
So far I havent't been able to build LLVM with it's own `libc++`, but once I have I will publish it.

**Comment by 3oheicrw** [comment]
If it's only about lld being problematic then you could tell clang to use gnu ld via -fuse-l (https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html). The document is for gcc but clang also supports this option too.

**Comment by jpgpng** [comment]
Not needed anymore. I have workaround for lld now.
