### ISSUE TITLE
Include flex + bison + byacc in the distro?

### ISSUE THREAD

**Issue by 3oheicrw** [brechtsanders/winlibs_mingw#116]
These small tools are very useful (when they are needed). Including them in the distro helped us not having to spawn a full MSYS2 shell.

**Comment by brechtsanders** [comment]
`yacc` is a shell script that calls `bison.exe`, so adding the bison/yacc package is not an option as I'm not planning to distribute a shell script (use MSYS2 for that).

I could add `byacc.exe` to the distribution, but I think we can leave that as a separate package for when the package manager is ready...
