### ISSUE TITLE
A Hello world program in C language produced by GCC is 332KB

### ISSUE THREAD

**Issue by BoQsc** [brechtsanders/winlibs_mingw#12]
Hello world binary is 332KB That's almost half a megabyte! Please suggest optimisations. So weird!
Is that because stdio library is included in the executable while compiling?

> 1 MB = 1000 KB (in decimal)
> 1 MB = 1024 KB (in binary)
Source: https://en.wikipedia.org/wiki/Megabyte

## Hello.c
```
#include <stdio.h>

int main ()
{
  printf("Hello world!\n");
  return 0;
}
```

![image](https://user-images.githubusercontent.com/21064622/80808916-41fcdf00-8bc9-11ea-88b5-9deef0ce1718.png)

**Comment by BoQsc** [comment]
I have found some working examples and little bit of onesided explanation.
https://stackoverflow.com/questions/33597523/why-is-smallest-compiled-exe-i-can-make-with-gcc-is-67kb

By this method alone I was able to produce 4kb standalone Hello World executable File instead of 140KB

**Comment by brechtsanders** [comment]
I just tried both tests above.
The first example compiled with `gcc -s -o test.exe test.c` using my build of GCC 9.3.0 resulted in 19456 bytes for 64-bit Windows and 15872 for 32-bit Windows, which seems fine to me.
BoQsc's example was only 3584 bytes for 64-bit Windows and 3072 for 32-bit Windows, which is amazing.

So I'm thinking you had all the debug information in the resulting .exe.
You can remove it afterwards with the `strip` command, or during the linking process by adding the `-s` flag.
Of course your .exe won't be suitable for debugging when you do this.

To reduce size even more you could also optimize compilation for reduced size with the `-Os` flag.
