### ISSUE TITLE
Someone used your project name

### ISSUE THREAD

**Issue by alter-ego-of-3oheicrw** [brechtsanders/winlibs_mingw#120]
I don't save a bookmark to this repo but find it via Google search each time I want to access it. Today Google gives me to a different project with the same name. It took me many minutes to realize I'm browsing the wrong project.

https://github.com/winlibs

**Comment by brechtsanders** [comment]
Not much I can do about that now.

But I recommend always going to https://winlibs.com/ as all relevant information will be published there.
