### ISSUE TITLE
New version request (GCC 9.5 + LLVM 14.0.6)

### ISSUE THREAD

**Issue by kevin3w** [brechtsanders/winlibs_mingw#121]
As the last version of GCC 9.5, we would like you to provide a final distribution of GCC 9.5 + LLVM 14.0.6 for this release. Thank you very much!

**Comment by brechtsanders** [comment]
Why would you need a build of an old release of GCC and an old release of LLVM?

**Comment by kevin3w** [comment]
Hi Sanders
The current releases are good enough. Thank you for your hard work to maintain. As know as the GCC 9.5 is the last version of the  9 series , theoretically it has the fewest bugs (the same with LLVM 14.0.6), so we'd like you to help us provide such a release for long-term use  in the working environment. Of course, this is just a request, which is not necessary.

**Comment by brechtsanders** [comment]
I'm not going to spend time on older LLVM, but I did release a new build of 9.5.

https://github.com/brechtsanders/winlibs_mingw/releases/tag/9.5.0-10.0.0-msvcrt-r1

**Comment by Eric-01** [comment]
While you are at it, could you please add the missing UCRT version of GCC 11.3.0 back to your website? I think you accidentally removed it from there a while ago and just didn't bring it back.

**Comment by Eric-01** [comment]
This may involve adding a link to the newly built GCC 9.5 to your website, and if you work on it, could you please add the missing UCRT version of GCC 11.3 there as well? I think you accidentally removed it from the website a while ago and just didn't bring it back.

**Comment by brechtsanders** [comment]
Done. Thanks for pointing that out.

**Comment by kevin3w** [comment]
> I'm not going to spend time on older LLVM, but I did release a new build of 9.5.
> 
> https://github.com/brechtsanders/winlibs_mingw/releases/tag/9.5.0-10.0.0-msvcrt-r1

Thanks  Sanders. The new release works good.
