### ISSUE TITLE
Error 'initializer element is not constant', but same code compiles on Linux gcc

### ISSUE THREAD

**Issue by PowerOfCreation** [brechtsanders/winlibs_mingw#122]
The following code(test.c):

```C
#include <stddef.h>

typedef struct Edge
{
    union BGX 
    {
        unsigned long X; 
    } BGX;
} Edge;

const Edge graphExpression[] =
    {
    {{0}}
};

const Edge graphFactor[] =
    {
    {{(unsigned long) graphExpression}}
};
```

does not compile with `gcc.exe -c test.c`, but it works just fine with gcc from other sources like Homebrew.

WinLibs:
```bash
$ gcc.exe --version
gcc.exe (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ gcc.exe -c test.c
.\test.c:18:7: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   18 |     {{(unsigned long) graphExpression}}
      |       ^
.\test.c:18:7: error: initializer element is not constant
.\test.c:18:7: note: (near initialization for 'graphFactor[0].BGX.X')
```
Ubuntu WSL with homebrew:

```bash
$ /home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0/bin/gcc-12 --version
gcc-12 (Homebrew GCC 12.2.0) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ /home/linuxbrew/.linuxbrew/Cellar/gcc/12.2.0/bin/gcc-12  -c /.../test.c
```

**Comment by brechtsanders** [comment]
Why are you casting a pointer to anything other than `uintptr_t`/`intptr_t`? 

I didn't write the compiler itself. Have you tried asking this question on https://stackoverflow.com/ ?

**Comment by PowerOfCreation** [comment]
> Why are you casting a pointer to anything other than `uintptr_t`/`intptr_t`?
> 
> I didn't write the compiler itself. Have you tried asking this question on https://stackoverflow.com/ ?

That was a quick response :D No, I haven't tried different casts and I didn't post on stackoverflow because it is a bug and not really a question from my understanding. Who is responsible for the underlying compiler, is it MinGW? Should I file a bug here: https://sourceforge.net/p/mingw-w64/bugs/?

**Comment by brechtsanders** [comment]
Try and ask it on stackoverflow. The compiler is GCC, MinGW-w64 is merely a kind of standard library for Windows. So if you feel it really is a GCC bug you should report it here: https://gcc.gnu.org/bugs/

But on Windows the size of a pointer doesn't exactly match `long` or  `unsigned long`, that's why the types `intptr_t`/`uintptr_t` exist.

**Comment by s6nonqxt** [comment]
The same error on gcc version 12.2.0 (Rev6, Built by MSYS2 project).

**Comment by brechtsanders** [comment]
`(unsigned long) graphExpression` where `graphExpression` is a pointer assumes `sizeof(unsigned long) == sizeof(void*)` which is not the case in Windows.

The solution for this is to add `#include <stdint.h>` and use `uintptr_t X; ` and  `(uintptr_t) graphExpression` instead.

This allows your code to be portble to platforms where you can't make assumptions on the size of a pointer.

**Comment by PowerOfCreation** [comment]
> `(unsigned long) graphExpression` where `graphExpression` is a pointer assumes `sizeof(unsigned long) == sizeof(void*)` which is not the case in Windows.
> 
> The solution for this is to add `#include <stdint.h>` and use `uintptr_t X; ` and `(uintptr_t) graphExpression` instead.
> 
> This allows your code to be portble to platforms where you can't make assumptions on the size of a pointer.

Now I get what you mean, thank you very much for coming back to this and explaining it :)
