### ISSUE TITLE
Requesting for experimental version GCC 13

### ISSUE THREAD

**Issue by desmond-gold** [brechtsanders/winlibs_mingw#123]

**Comment by brechtsanders** [comment]
Now GCC 13 entered stage 3 I think it's a good time to give it a go.

See #117 for my progress.

**Comment by brechtsanders** [comment]
Here you go: https://github.com/brechtsanders/winlibs_mingw/releases/tag/13.0.0-snapshot20221030-10.0.0-msvcrt-r1posix
