### ISSUE TITLE
How to setup your MinGW distribution to use with MSYS2 Shell?

### ISSUE THREAD

**Issue by s6nonqxt** [brechtsanders/winlibs_mingw#124]
MSYS2 is rolling release so it's always the latest and greatest stuffs. I'm currently having troubles with gcc 12.2.0 on msys2 and wanted to use your gcc 11.3.0 msvcrt instead. Please let me know how to set everything up. Thank you.

**Comment by brechtsanders** [comment]
There is no setup. Just unzip and use it.

If you want to use it from Command Prompt / PowerShell or even MSYS2 just add the full path of the extracted `mingw32/bin` or  `mingw64/bin` folder to the beginning of your PATH environment variable.

Some more usages are explained on https://winlibs.com/
