### ISSUE TITLE
Would recommend to release in .zip archive instead of 7z even if compression is x3 times lower

### ISSUE THREAD

**Issue by BoQsc** [brechtsanders/winlibs_mingw#13]
I'm not forcing, I just made this issue to consider the long term usability.

.zip archives are more standard and cross platform, easier to use than 7z which requires additional specific 7zip software to decompress the release.

One of Yours .7zip release size: 51,7 MB
Release decompressed: 548 MB
Release archived in .zip file: 150 MB

For the shake of standardisation and simplicity just release everything in .zip file. That's my opinion.

**Comment by brechtsanders** [comment]
7-Zip is completely free. Surely the audience for a compiler knows how to install a free tool like 7-Zip or PeaZip (if they haven't already).
The compression of .7z files is a lot better than .zip files - less than half the size in this case!

But to validate your statement I have created .zip files of the latest release (10.1.0-10.0.0-7.0.0-r1) - which are over 300MB - so I can check if people actually download this.

**Comment by BoQsc** [comment]
> 7-Zip is completely free. Surely the audience for a compiler knows how to install a free tool like 7-Zip or PeaZip (if they haven't already).
> The compression of .7z files is a lot better than .zip files - less than half the size in this case!
> 
> But to validate your statement I have created .zip files of the latest release (10.1.0-10.0.0-7.0.0-r1) - which are over 300MB - so I can check if people actually download this.

I'd say, remove the 7zip releases and reduce the confusion of: which one should be downloaded and what's the difference between .7zip and .zip archive.

Why make the life more complicated for everyone, just for checking the statistics of which one will be downloaded more.

7zip is going to be downloaded more, since it is in the first place, and behind the .zip version.

**Comment by nenin-sc** [comment]
> Why make the life more complicated for everyone
Hate to say that, but individual who has difficulties with usage of 7z must not even try to use mingw compilers, neither stand-alone nor msys2-based.

**Comment by brechtsanders** [comment]
Just did a new release and I have also announces .zip files on http://winlibs.com/ this time.
Before, the site only listed .7z files.
Via the github releases page the previous release was only downloaded in .zip format in less than 2% of the downloads.
I will keep an eye on this how it evolves.
If .zip is more popular I'm willing to drop the .7z releases next time.
But if not I may stick with .7z...

**Comment by BoQsc** [comment]
> > Why make the life more complicated for everyone
> 
> Hate to say that, but individual who has difficulties with usage of 7z must not even try to use mingw compilers, neither stand-alone nor msys2-based.

You should stop judging who should and who should not use the software.
This issue is all about usability and accessibility, and nothing about the experience or skills in that relation.  
Clearing up unecessary complexity and mental load should be the first and foremost importance for any project. I'm closing this issue since .zip release is available.

**Comment by brechtsanders** [comment]
About 20% of downloads now are in .zip format.
So I will keep the .zip downloads available for the future releases.

**Comment by nenin-sc** [comment]
Please do not abandon the 7z ones.

**Comment by brechtsanders** [comment]
I will keep both.
