### ISSUE TITLE
Hardware wanted to support Windows on ARM (aarch64-w64-mingw32)

### ISSUE THREAD

**Issue by brechtsanders** [brechtsanders/winlibs_mingw#130]
I strongly believe Windows on ARM has some future as a platform.

Binutils and GCC are not quite ready, but the work is underway.
See for example the issue I logged [here](https://sourceware.org/bugzilla/show_bug.cgi?id=29964) fro binutils.

To be able to support Windows on ARM I'm looking for hardware that can run it, i particular the ARM [Windows Dev Kit 2013](https://www.microsoft.com/en-us/d/windows-dev-kit-2023/94k0p67w7581).
However this can't be bought in my country.

Is there anybody that can sponsor winlibs with hardware that runs natively Windows on ARM?

**Comment by bwoodsend** [comment]
You can run an arm64 Windows virtual machine on a macOS M1 machine - I'd be surprised if you can't get one of those (albeit heavily overpriced) - see [here](https://docs.getutm.app/guides/windows/).

I'm happy to run experiments on my machine for you.

**Comment by xtemp09** [comment]
Wondrous news, especially after [Windows RT](https://en.wikipedia.org/wiki/Windows_RT) && Surface.

**Comment by brechtsanders** [comment]
@bwoodsend I know Apple M1 is the most decent ARM platform out there right now and virtualization of Windows on ARM can be done with at least Qemu and VirtualBox , but I really want to know everything works natively, on a chip that Microsoft is targetting (Qualcomm).

Are you able to get MSYS2 working on your virtual Windows on ARM?

**Comment by bwoodsend** [comment]
MSYS2 works well although it's running under emulation since MSYS2 only supports `x86_64`.
```
brenainn@WINDOWS-KNDK3G4 UCRT64 ~
# uname -m
x86_64
```

**Comment by brechtsanders** [comment]
@bwoodsend I would prefer it was native.
Were you doing it as described [here](https://www.msys2.org/wiki/arm64/)?

**Comment by bwoodsend** [comment]
Ahh, I didn't know that existed. I'll try that.

**Comment by bwoodsend** [comment]
It's given me a native arm64 clang compiler.
```
brenainn@WINDOWS-KNDK3G4 CLANGARM64 ~
# clang -v
clang version 15.0.7
Target: aarch64-w64-windows-gnu
Thread model: posix
InstalledDir: C:/msys64/clangarm64/bin
```
Managed to natively compile hello world with it.

**Comment by brechtsanders** [comment]
Great!

Just curious. What does `uname -m` say? Is the shell still emulated?

**Comment by bwoodsend** [comment]
Yeah, just boring old `x86_64`.

**Comment by brechtsanders** [comment]
No worries, it's just the shell. If the compiler is native that's already very good.

**Comment by bwoodsend** [comment]
Where do you want to go from here? I can give you remote access to the VM if you like? Or do we all chip in and try to buy you your own?

**Comment by brechtsanders** [comment]
I would really love to get my hands on hardware of my own. It's a shame Microsoft doesn't offer their Dev Kit for free for open source developers. I mean, that would make since if it's their goal to get more software on that platform.

Does anybody know of any CI build environments running Windows on ARM? That could also be an option.

@bwoodsend I will keep your offer in mind when I want to run something on the native platform. But for now I'm still trying to build a proper cross-compiler on Windows on Intel. I haven't been very lucky with GCC yet (even though binutils recently got some unofficial support for aarch64pe), so I'm going to have to look at LLVM for the time being.

**Comment by bwoodsend** [comment]
> I would really love to get my hands on hardware of my own. It's a shame Microsoft doesn't offer their Dev Kit for free for open source developers. I mean, that would make since if it's their goal to get more software on that platform.

You would think that. Given the choice between not supporting arm64 and porting all my code to use MSVC, I know which I'd go for. But then I also expected Apple to help VirtualBox enable VMWare on macOS M1 so that CI/CD for macOS M1 would be possible - they didn't and M1 is still seen as unsupportable by anyone not willing to by their own machine.

> Does anybody know of any CI build environments running Windows on ARM? That could also be an option.

I would expect either Travis CI to be the first. Travis currently offers all kinds of weird architectures for Linux only.

I have, in the past, gotten around shipping restrictions by using [shipito](https://www.shipito.com/en/shipping-calculator/) which is a glorified wharehouse in the USA that forwards packages to pretty much anywhere. Depending on where you are, it may not be too outrageously expensive.

**Comment by brechtsanders** [comment]
In the mean time I have talked to Microsoft, and now I know how to order the Windows Dev Kit 2013.
Now I need to find the funds.

**Comment by brechtsanders** [comment]
Good news, I now have a Windows Dev Kit 2013.
I have started compiling things, but some dependencies will need some tweaking for everything to build I'm afraid.

**Comment by michael-o** [comment]
> Good news, I now have a Windows Dev Kit 2013. I have started compiling things, but some dependencies will need some tweaking for everything to build I'm afraid.

How did you get it? Bought it?

**Comment by brechtsanders** [comment]
I bought it, but as it couldn't be ordered in my country I actually had to call Microsoft and ask then to ship it to me from another country.
