### ISSUE TITLE
[suggest] Provide an Online/Offline Installer to install different version of MinGW.

### ISSUE THREAD

**Issue by hwhsu1231** [brechtsanders/winlibs_mingw#132]
### Suggestion

This issue is related to: https://github.com/brechtsanders/winlibs_mingw/issues/64

My suggestion is as follows:

* Provide individual archives for different version of MinGW as usual.
* Provide an **"Online Installer"** (just as Qt does) to install our desired version of MinGW into the default location.

The following is one of the template directory structures that I recommend, where I took [Qt](https://download.qt.io/official_releases/online_installers/) and [MSYS2](https://www.msys2.org/) for reference:

```
C:/winlibs
    /gcc-13.0.0
        /mingw32
        /mingw64
        /ucrt32
        /ucrt64
    /gcc-12.2.0
    /gcc-12.2.0-llvm-14.0.6
    /gcc-12.2.0-llvm-15.0.6
    /gcc-12.2.0-llvm-15.0.7
    /gcc-11.3.0
    /gcc-11.3.0-llvm-14.0.3
    /gcc-11.3.0-llvm-14.0.1
    /gcc-12.1.0
    ...
```

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/218038742-ec263c63-c493-455e-af9d-08bf9d0e5e4a.png)
![image](https://user-images.githubusercontent.com/71438617/218037196-4f06f8ea-4dbc-4c27-ac28-cdd4fd4d27a6.png)

**Comment by brechtsanders** [comment]
The whole idea of the winlibs.com standalone build was not to have an installer.

You can still extract different archives yourself into your suggested structure.

What is the reason anybody would want all those different versions on their system?

What kind of target audience would need this?

**Comment by hwhsu1231** [comment]
> What is the reason anybody would want all those different versions on their system?
> 
> What kind of target audience would need this?

For example. If users are working with [Conan](https://github.com/conan-io/conan), they might want to try different version of GCC compilers when testing on Windows. 

### Limitation of MSYS2

And one possible method of installing MinGW compilers on Windows is using MSYS2. However, since MSYS2 will update its source periodically, the version of GCC compilers installed by MSYS2 may change. AFAIK, it is _not possible_ to install the previous version of GCC compiler in MSYS2 unless the package is accidentally remains in the repo of MSYS2 (based on: https://stackoverflow.com/a/33986757/16265240)

### Problems I met before...

Suppose that the highest version of `gcc` available in `settings.yml` of the latest [Conan(currently 1.58)](https://docs.conan.io/en/1.58/reference/config_files/settings.yml.html) is `12.2`. If the latest version of MinGW compilers installed by MSYS2 is happen to be `13.0`, then the following error may showed up when we executing the `conan install` command:

```
ERROR: Invalid setting '13.0' is not a valid 'settings.compiler.version' value.
```

I indeed met this kind of error when using Conan 1.52.0. Since the highest version of `gcc` compiler is `12` and the current version of MinGW installed by MSYS2 is `12.2`, then the above-mentioned error showed up. Here is the link: https://github.com/conan-io/conan/issues/12255#issuecomment-1270426359

Although Conan Team provides the solution to it, which is manually modifying the `settings.yml`, it is quite an inevitable problem which might happen anytime.

### In the end...

Since then, I was looking for another method to install MinGW on Windows. If possible, I hope this method can install the specific version of MinGW whatever I want.

**Comment by hwhsu1231** [comment]
Actually, it is fine to provide **"Offline Installers"** for different individual packages instead of an Online Installer if they can be installed to corresponding directories, respectively.

For example:

* winlibs-i686-posix-dwarf-gcc-13.0.1-mingw-w64msvcrt-10.0.0-installer.exe:

  ```
  C:\winlibs\gcc-13.0.1\mingw32
  ```

* winlibs-x86_64-posix-seh-gcc-13.0.1-mingw-w64msvcrt-10.0.0-installer.exe:

  ```
  C:\winlibs\gcc-13.0.1\mingw64
  ```

* winlibs-i686-posix-dwarf-gcc-12.2.0-mingw-w64ucrt-10.0.0-installer.exe:

  ```
  C:\winlibs\gcc-12.2.0\ucrt32
  ```

* winlibs-x86_64-posix-seh-gcc-12.2.0-mingw-w64ucrt-10.0.0-installer.exe:

  ```
  C:\winlibs\gcc-12.2.0\ucrt64
  ```

* ...etc

**Comment by brechtsanders** [comment]
I was actually thinking about using `mingw64ucrt` for the UCRT build and mingw64 for MSVCRT.

Would a folder like `C:\winlibs\gcc-12.2.0\mingw64ucrt` work for you?

If you have a 7-zip extractor + the downloaded package(s), what you asked is just a few lines of scripting.

**Comment by hwhsu1231** [comment]
> I was actually thinking about using `mingw64ucrt` for the UCRT build and `mingw64` for MSVCRT.
> 
> Would a folder like `C:\winlibs\gcc-12.2.0\mingw64ucrt` work for you?

The reason why I choose `ucrt64` as the subdirectory is that I take [MSYS2](https://www.msys2.org/docs/environments/#overview) for reference. What's the difference between `ucrt64` and `mingw64ucrt`?

> If you have a 7-zip extractor + the downloaded package(s), what you asked is just a few lines of scripting.

On Windows platform, I think it is more user-friendly to provide installers in the releases.

**Comment by Alcaro** [comment]
I don't know how common my viewpoint is, but I prefer archive files.

- They're portable. I can move them around as much as I want; if I want to copy my setup to a new computer, I just copy the files.
- They don't add any registry keys; bigger registry means slower boot.
- They don't modify PATH. I prefer not having my compiler in PATH, because if it's there, so are dlls like libwinpthread-1.dll, which means I won't notice if I forgot copying them into the program's own directory.
- They uninstall cleanly. I've seen a few installers that leave empty folders and other junk around after uninstalling; an archive can't do that.
- They don't try to claim any unique resource for themselves, so I can easily install (for example) one 32bit and one 64bit compiler side by side.
- And, most importantly, all of the above are true and verifiable from the filename alone. Sure, some installers share some or all above properties, but I can't confirm that until I try it.

That said, installers have a few advantages too. For some people, modifying PATH is a feature, not a bug; and you can install a msi from a command prompt without installing anything else (while zip archives are available as well, and explorer.exe has a preinstalled zip extractor, I'm not aware of any preinstalled command line extractor). I'm not sure what the best option is. Considering there are zip and 7z archives already, maybe offering msi as a third option would be reasonable?

**Comment by hwhsu1231** [comment]
Take [llvm-project](https://github.com/llvm/llvm-project/releases) for reference. We can see that it provides Win32 and Win64 Installers in every release version. For example:

* [LLVM-15.0.5-win32.exe](https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.5/LLVM-15.0.5-win32.exe)
* [LLVM-15.0.5-win64.exe](https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.5/LLVM-15.0.5-win64.exe)

One of the extensive benefits of providing installers is that we can use [winget-cli](https://github.com/microsoft/winget-cli) to install them with the specific version and architecture by running the following commands:

```
winget install llvm.llvm -a x64 -v 15.0.5
```

The following is the example log:

<details><summary>Click to expand</summary>

```cmd
C:\Users\hwhsu1231>winget show llvm.llvm --versions
找到 LLVM [LLVM.LLVM]
版本
------
15.0.7
15.0.6
15.0.5
15.0.4
15.0.3
15.0.2
15.0.1
15.0.0
14.0.6
14.0.5
14.0.4
14.0.3
14.0.1
14.0.0
13.0.1
13.0.0
12.0.1
12.0.0
11.1.0
11.0.0
10.0.0

C:\Users\hwhsu1231>winget install llvm.llvm -a x64 -v 15.0.5
找到 LLVM [LLVM.LLVM] 版本 15.0.5
此應用程式已由其擁有者授權給您。
Microsoft 不負任何責任，也不會授與協力廠商封裝的任何授權。
正在下載 https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.5/LLVM-15.0.5-win64.exe
  ██████████████████████████████   277 MB /  277 MB
已成功驗證安裝程式雜湊
正在啟動套件安裝...
已成功安裝
```

</details>

**Comment by hwhsu1231** [comment]
> Considering there are zip and 7z archives already, maybe offering msi as a third option would be reasonable?

I think both `*.msi` and `*.exe` are acceptable.

**Comment by chawyehsu** [comment]
Sounds like @hwhsu1231 wants a _winlibs-mingw verison manager_ thing, which does not necessarily tie to an _Installer_ implementation I think, huh? A handmade customized shell script could satisfy such needs I believe. Something like nvm.sh allows you to choose which winlibs-mingw version to install.

**Comment by michael-o** [comment]
Looks like another NIH request.

**Comment by brechtsanders** [comment]
The strength of the standalone winlibs downloads is that there is no installer.

As a result of that, it's perfectly possible to install different versions alongside each other.

I absolute recommend to NOT put it in the PATH environment, so there is no mix-up between versions.

**Comment by michael-o** [comment]
> The strength of the standalone winlibs downloads is that there is no installer.
> 
> As a result of that, it's perfectly possible to install different versions alongside each other.
> 
> I absolute recommend to NOT put it in the PATH environment, so there is no mix-up between versions.

Yes, I totally works for me with four different versions of it. CMake picks them up and ninja compiles my Fortran code.
