### ISSUE TITLE
12.2 with Nuitka gives "internal error: aborting at ../../ld/ldlang.c:527 in compare_section"

### ISSUE THREAD

**Issue by kayhayen** [brechtsanders/winlibs_mingw#134]
When disabling LTO I get this (what seems to be a problem of binutils: https://sourceware.org/bugzilla/show_bug.cgi?id=30079

```
c:/users/kayha/appdata/local/nuitka/nuitka/cache/downloads/gcc/x86_64/12.2.0-15.0.7-10.0.0-msvcrt-r4/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: internal error: aborting at ../../ld/ldlang.c:527 in compare_section
c:/users/kayha/appdata/local/nuitka/nuitka/cache/downloads/gcc/x86_64/12.2.0-15.0.7-10.0.0-msvcrt-r4/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: please report this bug
collect2.exe: error: ld returned 1 exit status
```

With LTO I am getting this
```
c:/users/kayha/appdata/local/nuitka/nuitka/cache/downloads/gcc/x86_64/12.2.0-15.0.7-10.0.0-msvcrt-r4/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: internal error: aborting at ../../ld/ldlang.c:527 in compare_section
c:/users/kayha/appdata/local/nuitka/nuitka/cache/downloads/gcc/x86_64/12.2.0-15.0.7-10.0.0-msvcrt-r4/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: please report this bug
collect2.exe: error: ld returned 1 exit status
```

The line used for link is this:

````
gcc -o C:\Users\kayha\repos\Py2C\AssertsTest.exe -Wl,--exclude-all-symbols -Wl,--out-implib,.\import.lib -municode -s -Wl,--enable-auto-import -Wl,--stack,9863168 -static-libgcc @".\@link_input.txt" -LC:\Python310_64\libs -lm -lpython310
````

The link library of Python seems to trigger this, if I understood the report correctly. I tried removing spuriosly options of Nuitka there, but I think the main question is, does winlibs have the binutils version that is affected and is there hope for a fix with the new binutils that solves it.

**Comment by brechtsanders** [comment]
The winlibs builds always use the latest builds whenever possible.

So when there is a newer binutils you can expect a winlibs release with this pretty soon after.

But if the issue you found is in binutils you should really report it there.

**Comment by kayhayen** [comment]
To me it's not clear which release contains it, that is not tracked there, but it seems quite obvious that it is that issue, fully reported and fixed, but apparently not part of your 12.2 release just yet. I will try again once I see a new 12.x release from your side I guess, and close this once the proper binutils is there.

**Comment by zycool** [comment]
i got the same issu

**Comment by kayhayen** [comment]
This doesn't happen anymore with gcc 13 it seems.
