### ISSUE TITLE
Standard and Error Output not showing on Windows Console

### ISSUE THREAD

**Issue by xamidi** [brechtsanders/winlibs_mingw#135]
In a recent [release](https://github.com/xamidi/pmGenerator/releases/tag/1.0.0) of mine, where I used [winlibs-x86_64-posix-seh-gcc-11.3.0-llvm-14.0.3-mingw-w64msvcrt-10.0.0-r3](https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.3.0-14.0.3-10.0.0-msvcrt-r3) as a compiler to obtain Windows binaries, I have an issue:

- The output is not shown on a Windows Console (CMD).
  - You can work around this by redirecting all output into a file like `pmGenerator [args] > out.txt 2>&1`,
     or by using a different console, e.g. `Cygwin64 Terminal` that comes with [Cygwin](https://www.cygwin.com/install.html) (requires `./pmGenerator`).

I wonder if there is a known workaround that makes the Windows console show C/C++ standard and error output?
It is printed with `std::cout` and `std::cerr`, but I also tested `std::wcout`. None of these are shown in CMD (tested on Windows 7).

- Using
  ```
  #include <windef.h>
  #include <wingdi.h>
  #include <processenv.h>
  #include <winbase.h>
  #include <wincon.h>
  
  HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
  DWORD dwMode = 0;
  GetConsoleMode(hOut, &dwMode);
  dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
  SetConsoleMode(hOut, dwMode);
  ```
  didn't have any effect. I suspected there need to be some Windows API calls to enable ANSI or UTF8 or UTF16 mode, but using `_setmode` from `fcntl.h` also didn't enable printing.

- I also tried using
  `int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE, LPSTR pCmdLine, int nCmdShow)`
  rather than
  `int main(int argc, char* argv[])`
  as an entry point, which had no effect.
- Calling `AllocConsole()` just opened another console window, then crashed.

Since there are easy workarounds to not depend on CMD's output, this is a low priority issue. I'm just curious. Maybe I am missing something trivial?

**Comment by brechtsanders** [comment]
Did you actually build a console application using linker flag `-mconsole`?

**Comment by xamidi** [comment]
I had not used that flag, but I just did and it didn't have any visible effect. Or do I need to do that in combination with more?

**Comment by Alcaro** [comment]
I'm pretty sure -mconsole is the default.

AllocConsole alone does nothing useful, you also need to freopen() stdin/stdout/stderr. I've done something similar in one of my programs: <https://github.com/Alcaro/Flips/blob/master/flips-w32.cpp#L874>

That said, cout being gone is strange... try creating a hello world program, without the rest of pmGenerator, and see if it works better. Depending on which result you get, it'll help narrow down where the problem is.

Another thing you could try is C stdio, printf instead of std::cout.

**Comment by xamidi** [comment]
> I'm pretty sure -mconsole is the default.
> 
> AllocConsole alone does nothing useful, you also need to freopen() stdin/stdout/stderr. I've done something similar in one of my programs: https://github.com/Alcaro/Flips/blob/master/flips-w32.cpp#L874
> 
> That said, cout being gone is strange... try creating a hello world program, without the rest of pmGenerator, and see if it works better. Depending on which result you get, it'll help narrow down where the problem is.
> 
> Another thing you could try is C stdio, printf instead of std::cout.

Ohh, calling your `GUIClaimConsole()` did the trick, thanks!

**Comment by xamidi** [comment]
@Alcaro Do you happen to also know how the Windows CMD will print UTF-8 input not as gibberish?
For example, it currently prints `≈` as `Ôëê`.

I tried to use
```
#include <fcntl.h>
// [...]
	if (claimstdout)
		_setmode(STDOUT_FILENO, _O_U8TEXT);
	if (claimstderr)
		_setmode(STDERR_FILENO, _O_U8TEXT);
```
without any effect.

**Comment by Alcaro** [comment]
Personally I wouldn't install funny console workarounds without getting to the bottom of why it's needed (it's probably some misplaced compile option somewhere, though it's hard to say anything certain when I can't find your build script), but if you're satisfied with this solution, good enough.

_O_U8TEXT is the wrong direction - if you send utf16 to that stream via wprintf or std::wcout, and it's redirected to a file, it's converted to utf8. (I don't think it does anything at all if stdout is a console.)

There is, to my knowledge, no way to make printf accept utf8, other than installing Linux; the only way to print ≈ I'm aware of is the utf16 functions. Things may improve if you're using that Windows Terminal thing, but it demands windows 10 or higher; you said 7, so WTerminal is not available.

**Comment by xamidi** [comment]
> Personally I wouldn't install funny console workarounds without getting to the bottom of why it's needed (it's probably some misplaced compile option somewhere, though it's hard to say anything certain when I can't find your build script), but if you're satisfied with this solution, good enough.
> 
> _O_U8TEXT is the wrong direction - if you send utf16 to that stream via wprintf or std::wcout, and it's redirected to a file, it's converted to utf8. (I don't think it does anything at all if stdout is a console.)
> 
> There is, to my knowledge, no way to make printf accept utf8, other than installing Linux; the only way to print ≈ I'm aware of is the utf16 functions. Things may improve if you're using that Windows Terminal thing, but it demands windows 10 or higher; you said 7, so WTerminal is not available.

Thanks. I also tried `_O_U16TEXT ` without an effect. Apart from the formatting issue, there apparently are more issues because I use `\n` rather than `\r\n`, and your
```
	if (claimstdout)
		fputc('\r', stdout);
	if (claimstderr)
		fputc('\r', stderr);
```
doesn't seem to help. So I get prints like 
```
pmGenerator -p

D:\Dropbox\eclipse\pmGenerator\Release64bitDynamicGcc11.3>Fri Feb 24 21:11:45 2023: Process started.
```
without, or 
```
pmGenerator -p

Fri Feb 24 21:15:48 2023: Process started.tDynamicGcc11.3>
```
with your `fputc('\r',[...]` instructions.

> I can't find your build script)

I do not use a build script, I build using my IDE (Eclipse). These are, for example, the commands it generates for me:
```
C:\mingw-w64\winlibs-x86_64-posix-seh-gcc-11.3.0-llvm-14.0.3-mingw-w64msvcrt-10.0.0-r3\mingw64\bin\g++ -ID:/Dropbox/eclipse/boost_1_80_0/include -ID:/Dropbox/eclipse/mingw-w64-x86_64-tbb-2021.6.0-1-any.pkg/mingw64/include -O3 -fno-align-functions -fno-align-jumps -fno-align-loops -fno-align-labels -pedantic -Wall -c -m64 -fmessage-length=0 -std=c++20 -D_FILE_OFFSET_BITS=64 -o metamath\DRuleParser.o ..\metamath\DRuleParser.cpp 
C:\mingw-w64\winlibs-x86_64-posix-seh-gcc-11.3.0-llvm-14.0.3-mingw-w64msvcrt-10.0.0-r3\mingw64\bin\g++ -ID:/Dropbox/eclipse/boost_1_80_0/include -ID:/Dropbox/eclipse/mingw-w64-x86_64-tbb-2021.6.0-1-any.pkg/mingw64/include -O3 -fno-align-functions -fno-align-jumps -fno-align-loops -fno-align-labels -pedantic -Wall -c -m64 -fmessage-length=0 -std=c++20 -D_FILE_OFFSET_BITS=64 -o nortmann\DlCore.o ..\nortmann\DlCore.cpp 
C:\mingw-w64\winlibs-x86_64-posix-seh-gcc-11.3.0-llvm-14.0.3-mingw-w64msvcrt-10.0.0-r3\mingw64\bin\g++ -ID:/Dropbox/eclipse/boost_1_80_0/include -ID:/Dropbox/eclipse/mingw-w64-x86_64-tbb-2021.6.0-1-any.pkg/mingw64/include -O3 -fno-align-functions -fno-align-jumps -fno-align-loops -fno-align-labels -pedantic -Wall -c -m64 -fmessage-length=0 -std=c++20 -D_FILE_OFFSET_BITS=64 -o grammar\CfgGrammar.o ..\grammar\CfgGrammar.cpp 
C:\mingw-w64\winlibs-x86_64-posix-seh-gcc-11.3.0-llvm-14.0.3-mingw-w64msvcrt-10.0.0-r3\mingw64\bin\g++ -ID:/Dropbox/eclipse/boost_1_80_0/include -ID:/Dropbox/eclipse/mingw-w64-x86_64-tbb-2021.6.0-1-any.pkg/mingw64/include -O3 -fno-align-functions -fno-align-jumps -fno-align-loops -fno-align-labels -pedantic -Wall -c -m64 -fmessage-length=0 -std=c++20 -D_FILE_OFFSET_BITS=64 -o helper\IPrintable.o ..\helper\IPrintable.cpp 
C:\mingw-w64\winlibs-x86_64-posix-seh-gcc-11.3.0-llvm-14.0.3-mingw-w64msvcrt-10.0.0-r3\mingw64\bin\g++ -ID:/Dropbox/eclipse/boost_1_80_0/include -ID:/Dropbox/eclipse/mingw-w64-x86_64-tbb-2021.6.0-1-any.pkg/mingw64/include -O3 -fno-align-functions -fno-align-jumps -fno-align-loops -fno-align-labels -pedantic -Wall -c -m64 -fmessage-length=0 -std=c++20 -D_FILE_OFFSET_BITS=64 -o metamath\DRuleReducer.o ..\metamath\DRuleReducer.cpp 
C:\mingw-w64\winlibs-x86_64-posix-seh-gcc-11.3.0-llvm-14.0.3-mingw-w64msvcrt-10.0.0-r3\mingw64\bin\g++ -ID:/Dropbox/eclipse/boost_1_80_0/include -ID:/Dropbox/eclipse/mingw-w64-x86_64-tbb-2021.6.0-1-any.pkg/mingw64/include -O3 -fno-align-functions -fno-align-jumps -fno-align-loops -fno-align-labels -pedantic -Wall -c -m64 -fmessage-length=0 -std=c++20 -D_FILE_OFFSET_BITS=64 -o helper\Resources.o ..\helper\Resources.cpp 
C:\mingw-w64\winlibs-x86_64-posix-seh-gcc-11.3.0-llvm-14.0.3-mingw-w64msvcrt-10.0.0-r3\mingw64\bin\g++ -ID:/Dropbox/eclipse/boost_1_80_0/include -ID:/Dropbox/eclipse/mingw-w64-x86_64-tbb-2021.6.0-1-any.pkg/mingw64/include -O3 -fno-align-functions -fno-align-jumps -fno-align-loops -fno-align-labels -pedantic -Wall -c -m64 -fmessage-length=0 -std=c++20 -D_FILE_OFFSET_BITS=64 -o main.o ..\main.cpp 
C:\mingw-w64\winlibs-x86_64-posix-seh-gcc-11.3.0-llvm-14.0.3-mingw-w64msvcrt-10.0.0-r3\mingw64\bin\g++ -ID:/Dropbox/eclipse/boost_1_80_0/include -ID:/Dropbox/eclipse/mingw-w64-x86_64-tbb-2021.6.0-1-any.pkg/mingw64/include -O3 -fno-align-functions -fno-align-jumps -fno-align-loops -fno-align-labels -pedantic -Wall -c -m64 -fmessage-length=0 -std=c++20 -D_FILE_OFFSET_BITS=64 -o nortmann\DlStructure.o ..\nortmann\DlStructure.cpp 
C:\mingw-w64\winlibs-x86_64-posix-seh-gcc-11.3.0-llvm-14.0.3-mingw-w64msvcrt-10.0.0-r3\mingw64\bin\g++ -ID:/Dropbox/eclipse/boost_1_80_0/include -ID:/Dropbox/eclipse/mingw-w64-x86_64-tbb-2021.6.0-1-any.pkg/mingw64/include -O3 -fno-align-functions -fno-align-jumps -fno-align-loops -fno-align-labels -pedantic -Wall -c -m64 -fmessage-length=0 -std=c++20 -D_FILE_OFFSET_BITS=64 -o helper\FctHelper.o ..\helper\FctHelper.cpp 
C:\mingw-w64\winlibs-x86_64-posix-seh-gcc-11.3.0-llvm-14.0.3-mingw-w64msvcrt-10.0.0-r3\mingw64\bin\g++ -ID:/Dropbox/eclipse/boost_1_80_0/include -ID:/Dropbox/eclipse/mingw-w64-x86_64-tbb-2021.6.0-1-any.pkg/mingw64/include -O3 -fno-align-functions -fno-align-jumps -fno-align-loops -fno-align-labels -pedantic -Wall -c -m64 -fmessage-length=0 -std=c++20 -D_FILE_OFFSET_BITS=64 -o nortmann\DlProofEnumerator.o ..\nortmann\DlProofEnumerator.cpp 
C:\mingw-w64\winlibs-x86_64-posix-seh-gcc-11.3.0-llvm-14.0.3-mingw-w64msvcrt-10.0.0-r3\mingw64\bin\g++ -ID:/Dropbox/eclipse/boost_1_80_0/include -ID:/Dropbox/eclipse/mingw-w64-x86_64-tbb-2021.6.0-1-any.pkg/mingw64/include -O3 -fno-align-functions -fno-align-jumps -fno-align-loops -fno-align-labels -pedantic -Wall -c -m64 -fmessage-length=0 -std=c++20 -D_FILE_OFFSET_BITS=64 -o nortmann\DlFormula.o ..\nortmann\DlFormula.cpp 
C:\mingw-w64\winlibs-x86_64-posix-seh-gcc-11.3.0-llvm-14.0.3-mingw-w64msvcrt-10.0.0-r3\mingw64\bin\g++ -ID:/Dropbox/eclipse/boost_1_80_0/include -ID:/Dropbox/eclipse/mingw-w64-x86_64-tbb-2021.6.0-1-any.pkg/mingw64/include -O3 -fno-align-functions -fno-align-jumps -fno-align-loops -fno-align-labels -pedantic -Wall -c -m64 -fmessage-length=0 -std=c++20 -D_FILE_OFFSET_BITS=64 -o helper\ProgressData.o ..\helper\ProgressData.cpp 
C:\mingw-w64\winlibs-x86_64-posix-seh-gcc-11.3.0-llvm-14.0.3-mingw-w64msvcrt-10.0.0-r3\mingw64\bin\g++ -o pmGenerator.exe ..\icon\icon_x64.res grammar\CfgGrammar.o helper\FctHelper.o helper\IPrintable.o helper\ProgressData.o helper\Resources.o main.o metamath\DRuleParser.o metamath\DRuleReducer.o nortmann\DlCore.o nortmann\DlFormula.o nortmann\DlProofEnumerator.o nortmann\DlStructure.o -s -LD:/Dropbox/eclipse/mingw-w64-x86_64-tbb-2021.6.0-1-any.pkg/mingw64/lib -Wl,--subsystem,windows -mwindows -fuse-ld=lld -lpthread -ltbb12.dll 
```

Anyway, I decided Windows CMD is a piece of trash and I won't support it.
In particular due to your alarming (but wrong) guess, that there would be

> no way to make printf accept utf8, other than installing Linux

Every console I tried on Windows **except CMD** supports UTF-8. I tried
1. the Eclipse internal console,
2. Cygwin64 Terminal, and
3. a custom Scintilla-based that I implemented myself.

**Comment by Alcaro** [comment]
> Apart from the formatting issue, there apparently are more issues because I use \n rather than \r\n

No, you don't need to change that. Just print \n, printf/cout will convert it internally.

> -Wl,--subsystem,windows -mwindows

Well, there's your problem. Delete them. Or add a -Wl,--subsystem,console afterwards; in case of contradictory command line args, last one usually wins, but apparently -Wl,subsystem overrides -mwindows/-mconsole.

Or, well, it's one of your problems. Fixing that won't do anything about your utf8 issues.

> Every console I tried on Windows except CMD supports UTF-8.

Then they do. I've never used any custom consoles on Windows.

Sounds easier than installing Linux, at least.

**Comment by xamidi** [comment]
Using `-Wl,--subsystem,console` instead of `-Wl,--subsystem,windows -mwindows` indeed fixes the text ordering issue, but the text formatting issue remeains, so yeah..

> Sounds easier than installing Linux, at least.

I'd say redirecting to a file without installing anything is a very simple option for those who wish not to use a custom console.

Regardless, thanks for giving me some understanding about the Windows console!
