### ISSUE TITLE
Can't figure out how to use --demangle command line switch in ld.exe

### ISSUE THREAD

**Issue by BenHut1** [brechtsanders/winlibs_mingw#136]
There's this command line switch, which is shown as "--demangle [=STYLE]         Demangle symbol names [using STYLE]" in the help file command line output, but nothing anywhere (even after several Google searches) gives me any indication of what I'm supposed to type into the "STYLE" field. It doesn't even seem to be a standard switch mentioned in the official GCC documentation at https://ftp.gnu.org/old-gnu/Manuals/ld-2.9.1/html_node/ld_3.html

Also as this "STYLE" field is shown as optional, with those square brackets, I figured that I could use it without listing a style. But that seems to have no effect on the output. My DLL file's exported STDCALL symbols still look like MyFunc@8, where 8 is the number of bytes allocated on the stack for the arguments passed to the function.  All the leading underscores were removed from exported functions, but that ALWAYS happened, regardless of if the --demangle command line switch was used or not. It even removed the leading underscores from function names when the --no-demangle command line switch was used. It seems that your demangling command line switches are broken.

Please fix these.

**Comment by brechtsanders** [comment]
winlibs just aims to compile a Windows build of tools like binutils and gcc.

I recommend you direct your question to the developers at these projects.
https://sourceware.org/bugzilla/

You may also want to have a look at options like `--kill-at ` and `--add-stdcall-alias`.

Also, when calling the linker from the compiler you need to pass the options with `-Wl` (e.g. `-Wl,--kill-at ` and `-Wl,--add-stdcall-alias` for the above options)
