### ISSUE TITLE
decompiler

### ISSUE THREAD

**Issue by muhy06** [brechtsanders/winlibs_mingw#137]
hi is there a way to decompile it ? I have lost my files.

**Comment by brechtsanders** [comment]
What is your question exactly?

What do you mean with "decompile" and what are you trying to decompile?

**Comment by muhy06** [comment]
exe files, compiled using the compiler

**Comment by brechtsanders** [comment]
Converting binary code to C++?
I'm pretty sure you can forget about that.

Converting binary code to C? 
There may be some possibilities, but I doubt the result will be very human readable (unless maybe the binaries where built with debugging information).

There are disassemblers that can disassemble .exe and .dll files to assembler code.
If you find something that can convert assembler to C you may get something somewhat usable, but it will not even come close to the original C code.

The real answer: always keep a backup. Or even better in case of code: share your code as open source (using a platform like github, gitlab, sourceforge, ...)
