### ISSUE TITLE
Clang 15 - Generated PDB seems faulty

### ISSUE THREAD

**Issue by Scr3amer** [brechtsanders/winlibs_mingw#138]
Hello,

I just tried to generate a Hello World along its PDB using the following command:

```clang++ -g -gcodeview -Wl,--pdb= -o test.exe main.cpp```

And when I tried debugging it with RemedyBG it didn't work. RemedyBG froze. I couldn't run the app in it and put breakpoints and whatnot.
I also tried windbg preview from the Microsoft store. It didn't crash but had some trouble putting breakpoints, displaying the arrow and highlight the line of the current instruction...

I then tried with mstorsjo's Clang 15.0.0 and it worked flawlessly with both debuggers.

I tried also your
- Clang 15.0.6
- Clang 14
- Clang 14.0.6

But they didn't even recognize the linker option to output PDB files.

All of that leads me to think that the issue comes from the way you build the toolchain. But I didn't compare your makefile with mstorsjo's one. Maybe some configuration flags are required for proper PDB generation ?

My rig (not really that it matters):
- Windows 11 22H2
- AMD Zen 4

**Comment by PHdrr** [comment]
For Clang I would recommend https://github.com/mstorsjo/llvm-mingw

**Comment by Scr3amer** [comment]
Haha I actually mentionned I already used this toolchain and it worked :D but thanks for the reply !
