### ISSUE TITLE
Error while building on MSYS2

### ISSUE THREAD

**Issue by trungnt2910** [brechtsanders/winlibs_mingw#14]
I've been trying to build a branch of GCC 10 on MSYS2 `devel/c++-modules` using your script in #1 but met some compile errors while building `pex-win32.c`.

I've been looking around the Internet for guides on building GCC on MinGW and MSYS but haven't found anything useful.

I'm quite new to building GNU tools, please help me with my issue. 

I've attached my log file [here](https://github.com/brechtsanders/winlibs_mingw/files/4575801/error.log).

Thanks.

**Comment by brechtsanders** [comment]
Which version of GCC were you using (`gcc --version`)?
Did you build or install all the prerequisites before starting to build GCC?
