### ISSUE TITLE
Change in pthreads behaviour with gcc-13.0.1

### ISSUE THREAD

**Issue by sisyphus** [brechtsanders/winlibs_mingw#141]
Hi,
I have both gcc-12.2.0 (<code>gcc version 12.2.0 (MinGW-W64 x86_64-msvcrt-posix-seh, built by Brecht Sanders)</code>) and gcc-13.0.1 (<code>gcc version 13.0.1 20230402 (experimental) (MinGW-W64 x86_64-msvcrt-mcf-seh, built by Brecht Sanders)</code>).
I also have gmp-6.2.1 and mpfr-4.3.0-dev static libraries built using both compilers.

The demo C script:
```
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <mpfr.h>

void *foo( void *ptr );

int main(void) {
     pthread_t thread1;
     char *message1 = "Thread 1 prec:";
     int  iret1;

     if(mpfr_buildopt_tls_p()) printf("mpfr was built with TLS support\n");
     else printf("mpfr was NOT built with TLS support\n");

     mpfr_set_default_prec(101); /* alter default precision from 53 to 101 */

     iret1 = pthread_create( &thread1, NULL, foo, (void*) message1);
     pthread_join( thread1, NULL);

     printf("Thread 1 returns: %d\n",iret1);
     printf("Back in main: %d\n", mpfr_get_default_prec());

     return 0;
}

void *foo( void *ptr ) {
     char *message;
     message = (char *) ptr; 
     mpfr_set_default_prec(201); 
     printf("%s %d\n", message, mpfr_get_default_prec());
}
```
If I build using gcc-12.2.0, I get output of:
```
mpfr was built with TLS support
Thread 1 prec: 201
Thread 1 returns: 0
Back in main: 101
```
That is the output I expect.
If I build using gcc-13.0.1, I get unexpected output of:
```
mpfr was built with TLS support
Thread 1 prec: 53
Thread 1 returns: 0
Back in main: 101
```
"53" is the initial value for default precision.
Do you know why "53" is being reported, given that the value was changed to "201" in the preceding line of code ?
Does this issue need to be raised elsewhere ? (I don't know much about threads, so I'm thinking that maybe I'm just doing something daft.)

I build with either:
<code>gcc -o tls.exe tls.c -fdiagnostics-color=never -ID:\_64\msys_1220\1.0\local\include -lpthread -LD:\_64\msys_1220\1.0\local\lib -lmpfr -lgmp</code>
or
<code>gcc -o tls.exe tls.c -fdiagnostics-color=never -ID:\_64\msys_1301\1.0\local\include -lpthread -LD:\_64\msys_1301\1.0\local\lib -lmpfr -lgmp</code>

It makes no difference to the output, whether I link to the gmp & mpfr static libraries built by gcc-12.2.0 or to the ones built by gcc-13.0.1.
The output I get depends solely upon which of the two compil;ers are invoked,

Finally, it makes no difference if I build this demo to instead use <b>shared</b> gmp and mpfr libraries.

Cheers,
Rob

**Comment by brechtsanders** [comment]
Looking at your code `foo()` doesn't return anything and `pthread_join()` doesn't look for it's returned value.

Instead ` printf("Thread 1 returns: %d\n",iret1);` is printing the value returned by `pthread_create()`.

So I would say your code is looking at the wrong thing...

**Comment by sisyphus** [comment]
> So your code doesn't seem entirely correct.

Well ... yes, it would have made better sense if I had changed<code>printf("Thread 1 returns: %d\n",iret1);</code> to <code>printf("pthread_create() returns: %d\n",iret1);</code>.
(My demo is just based on some code I found on the web, and I didn't pay much attention to the wording of the printf statements.)

But that's not what's bothering me.
I'm more concerned about the fact that the <code>mpfr_set_default_prec(201)</code> call that's made inside the thread (as part of the foo function) is apparently ignored when the program is compiled by gcc-13.0.1, yet is honored if the the program is compiled by gcc-12.2.0.

> For the rest this may be an MPFR issue.

I probably didn't make it clear, but I have  two gmp-6.2.1 libraries - one built by gcc-12.2.0 and one built by gcc-13.0.1.
I also have 2 mpfr-4.3.0-dev libraries - one built by gcc-12.2.0 and one built by gcc-13.0.1.
Both of those gmp libraries are built from the same gmp source.
Both of those mpfr libraries are built from the same mpfr source.

When I build the demo with gcc-12.2.0, it works as I expect - irrespective of whether I link to the gmp/mpfr libraries built by gcc-12.2.0 or to the ones built by gcc-13.0.1.

Furthermore, when I build the demo with gcc-13.0.1, I get the unexpected result of that <code>mpfr_set_default_prec(201)</code> call being ignored - irrespective of whether I link to the gmp/mpfr libraries built by gcc-12.2.0 or to the ones built by gcc-13.0.1.

So I don't really see how it could be an MPFR issue - though I stop short of asserting that such is impossible.

Cheers,
Rob

**Comment by brechtsanders** [comment]
I just compile the compiler, not sure how I can help you.

If you have a 13.0.1 with pthreads instead of mcf threads you can determine if it's the threading model making the difference.

**Comment by sisyphus** [comment]
> I just compile the compiler, not sure how I can help you.

Yep - fair enough.
I'll close this now - and chase it up on a more appropriate forum.
Thanks for the quick response.

> If you have a 13.0.1 with pthreads instead of mcf threads you can determine if it's the threading model making the difference.

Yes, I had thought of that, too.
Could you send me the link if you have such a beast available from winlibs. (I couldn't see one listed there.)

Cheers,
Rob
