### ISSUE TITLE
Requesting for GCC 13.1 released version and GCC 14 experimental version

### ISSUE THREAD

**Issue by desmond-gold** [brechtsanders/winlibs_mingw#145]

**Comment by brechtsanders** [comment]
Already on it, I have been compiling for the last 2 days.

I'm working on the GCC 13.1 release, but for GCC 14 it's way too early in stage 1, I usually wait for stage 3 or 4.

**Comment by brechtsanders** [comment]
I just made a release of the new GCC 13.1.0.
