### ISSUE TITLE
gcc -v showes a wrong version info. 

### ISSUE THREAD

**Issue by THR-hub** [brechtsanders/winlibs_mingw#148]
[https://github.com/brechtsanders/winlibs_mingw/releases/tag/13.1.0posix-16.0.3-11.0.0-ucrt-r1](url)
Download the package with the tag x64 (I didn't try the x86 version) and extract it. Run `gcc -v`. 
Then you will see the version info of msvcrt instead of ucrt. 
Either the version is in fact msvcrt and tagged ucrt wrongly or it is just showing a wrong version info.

**Comment by jackL999** [comment]
You're right I can confirm, I get
`gcc version 13.1.0 (MinGW-W64 x86_64-msvcrt-posix-seh, built by Brecht Sanders)`

but ldd shows it uses UCRT

`ldd c:\Users\jack\.local\mingw64\bin\gcc.exe
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ff8ec9f0000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ff8eaf10000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ff8ea3c0000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7ff8ea0d0000)
        libiconv-2.dll => /c/Users/jack/.local/mingw64/bin/libiconv-2.dll (0x7ff8c4ba0000)
        libwinpthread-1.dll => /c/Users/jack/.local/mingw64/bin/libwinpthread-1.dll (0x7ff8ca450000)`

**Comment by brechtsanders** [comment]
I am preparing a new build that should fix this...

**Comment by brechtsanders** [comment]
I just published new build which fix this:
https://github.com/brechtsanders/winlibs_mingw/releases/tag/13.1.0-11.0.0-msvcrt-r2
https://github.com/brechtsanders/winlibs_mingw/releases/tag/13.1.0-11.0.0-ucrt-r2
