### ISSUE TITLE
Version of Python

### ISSUE THREAD

**Issue by xtemp09** [brechtsanders/winlibs_mingw#150]
Recently I've installed a newer version Python. I just forgot about _gdb_, _lldb_ and the version of Python installed before. Now _gdb_ and _lldb_ don't work. I think the problem comes from different Python in PATH.

What version of Python is required to run _gdb_ and _lldb_?

When I run _gdb_ or _lldb_, they report:

```
# ./gdb --version
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "C:\Qt\Tools\python\Lib\io.py", line 54, in <module>
ImportError: cannot import name 'text_encoding' from 'io' (unknown location)
```

```
# ./lldb --version
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "C:\Qt\Tools\python\Lib\io.py", line 54, in <module>
ImportError: cannot import name 'text_encoding' from 'io' (unknown location)
```

```
# python --version
Python 3.10.11
```

I can't find the version in https://github.com/brechtsanders/winlibs_recipes/blob/main/recipes/gdb.winlib. It contains, for example:
```
####WARNING: --with-python causes gdb.exe to depend on python*.dll
```
but, no explanation what * is.

**Comment by brechtsanders** [comment]
Golden rule when mixing toolchains on the same system: never put them in `PATH`.

If you use IDEs put the full path to all the tools in there.

Or when using command line customize the environment for just what you're trying to use.

But `gdb.exe` and `lldb.exe` should look for their dependency `python*.dll` in the same folder as the `.exe` file. Unless you have a system setting to look in `PATH` before checking the `.exe`'s folder.
