### ISSUE TITLE
Updated request(gcc12.3+clang16.0.5 ucrt  R2)

### ISSUE THREAD

**Issue by gwcfzpd** [brechtsanders/winlibs_mingw#156]
Hi Sanders,
Thank you very much for your work. I am a user from China, but when I use gcc13.1, I confirm that it will have garbled code when parsing the code with Chinese file name, I think this should be the problem of gcc13.1. But gcc12 doesn't have this problem, and I see you have **gcc12.3**+clang16.0.4, can you please update the version based on the first version to add include linker flag **-Wl,--no-insert-timestamp** and update **clang to 16.0.5**. Thank you very much!

**Comment by brechtsanders** [comment]
This may be a general GCC issue, not specifically related to the winlibs build.

Do you have a minimal reproducible example (small example code to test with)?

Several questions to be answered here:
- Did you use `wprintf()`
- Is your source code in UTF-8 or are you using some codepage?
- Are you building from an IDE, of a prompt (Command Prompt / PowerShell / MSYS2 shell)?

**Comment by brechtsanders** [comment]
In the meantime a tip for you: search for your issue on https://stackoverflow.com/

For example: https://stackoverflow.com/questions/22525779/how-to-print-a-chinese-character

**Comment by gwcfzpd** [comment]
> In the meantime a tip for you: search for your issue on https://stackoverflow.com/
> 
> For example: https://stackoverflow.com/questions/22525779/how-to-print-a-chinese-character


Hi Sanders,
Thanks for your reply.
I'm not mentioned the code with chinese character contents. I'm mentioned the file chinese character file name for the code.
Here's very simple c code for test.

```c
#include <stdio.h>
int main(int argc, char const *argv[])
{
	printf("你好，世界")
	return 0;
}
```
And this is the parse results by GCC 13.1, if the code name is chinese character(测试.c) the error information shown the garbled code(like below figure), if the code name is english name(test.c) ,no such issue from the error information.
address：https://postimg.cc/7J0gPyVB

when I changed the code from the UTF-8 to ANSI, the code contents would be corrrect parsed, but the error information still shown the garbled code(like below figure)
address：https://postimg.cc/kBPQ1BJL

Yes  I know  this would be general issue for GCC 13.1 not the winlabs issue.  and also GCC 12.3 have no this issue when the file name inculded chinese character. So i'd like to request the revision update for the GCC12.3 to add include linker flag -Wl,--no-insert-timestamp and Clang 16.0.5.

Thanks very much.

**Comment by gwcfzpd** [comment]
> > In the meantime a tip for you: search for your issue on https://stackoverflow.com/
> > For example: https://stackoverflow.com/questions/22525779/how-to-print-a-chinese-character
> 
> Hi Sanders, Thanks for your reply. I'm not mentioned the code with chinese character contents. I'm mentioned the file chinese character file name for the code. Here's very simple c code for test.
> 
> ```c
> #include <stdio.h>
> int main(int argc, char const *argv[])
> {
> 	printf("你好，世界")
> 	return 0;
> }
> ```
> 
> And this is the parse results by GCC 13.1, if the code name is chinese character(测试.c) the error information shown the garbled code(like below figure), if the code name is english name(test.c) ,no such issue from the error information. address：https://postimg.cc/7J0gPyVB
> 
> when I changed the code from the UTF-8 to ANSI, the code contents would be corrrect parsed, but the error information still shown the garbled code(like below figure) address：https://postimg.cc/kBPQ1BJL
> 
> Yes I know this would be general issue for GCC 13.1 not the winlabs issue. and also GCC 12.3 have no this issue when the file name inculded chinese character. So i'd like to request the revision update for the GCC12.3 to add include linker flag -Wl,--no-insert-timestamp and Clang 16.0.5.
> 
> Thanks very much.

To speed up code compilation to update build to add linker flag **-Wl,--no-insert-timestamp**
And also, the MSYS2 GCC 13.1 has the same issue too(for the chinese character file name).

Thanks again.

**Comment by brechtsanders** [comment]
I don't think filenames in extended character sets are supported.

As for your example, it will never work unless you use:
```c
wprintf(L"你好, 世界");
```

Finally in order for it to work you need to run the compiled program in a prompt window that is configured with a font that has Chinese characters.

I have already build the following releases with the `-Wl,--no-insert-timestamp` linker flag:
- https://github.com/brechtsanders/winlibs_mingw/releases/tag/13.1.0-16.0.5-11.0.0-msvcrt-r5
- https://github.com/brechtsanders/winlibs_mingw/releases/tag/13.1.0-16.0.5-11.0.0-ucrt-r5

Since the issue is the same with other builds like MSYS2 I recommend you log your issue with GCC at https://gcc.gnu.org/bugzilla/
