### ISSUE TITLE
Please consider cross compile gcc with mcf

### ISSUE THREAD

**Issue by eko5624** [brechtsanders/winlibs_mingw#158]
Crossing compile these toolchains on linux is much faster than on windows, so consider it, thanks.

I tried, but the toolchain I compiled seems not works correctly. Can you give me some help?

Discussion is here: https://github.com/eko5624/toolchain-test/discussions/5

**Comment by brechtsanders** [comment]
I know Linux builds are significantly faster but [winlibs.com](https://winlibs.com/) is about native Windows builds of the toolchains, the dependencies, and in the future also many packages.

MinGW-w64 GCC comes with most Linux distributions and for LLVM there is https://github.com/mstorsjo/llvm-mingw .
