### ISSUE TITLE
Build of GCC 11.4

### ISSUE THREAD

**Issue by Victor-Ch** [brechtsanders/winlibs_mingw#159]
Could you build GCC 11.4 (at least MSVCRT runtime win64 version)?
That would be great.

**Comment by brechtsanders** [comment]
Just out of curiosity: why do you need an older version (current is GCC 13.1) ?

Here are the builds I did last night just for you ;-)
- https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.4.0-11.0.0-msvcrt-r1
- https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.4.0-11.0.0-ucrt-r1

**Comment by Victor-Ch** [comment]
Just kinda stuck on GCC 11.
Thank you very much for the builds!
