### ISSUE TITLE
Should libpthread be added to clang by default for 2-in-1 releases?

### ISSUE THREAD

**Issue by farta1986** [brechtsanders/winlibs_mingw#16]
During building this lib
https://github.com/yhirose/cpp-httplib
with clang in a mingw+clang 2-in-1 releases (GCC 10.1.0 + Clang/LLVM 10.0.0 + MinGW-w64 7.0.0 (release 2), clang report link errors due to some impl of pthread not found. It  seems  clang doesn't link libpthread by default when gcc does. 
As clang in the 2-in-1 release is built with default target x86_64-w64-windows-gnu, maybe we can add this lib linkage to clang by default?

Thanks a lot.

**Comment by brechtsanders** [comment]
I just tried to build the examples in https://github.com/yhirose/cpp-httplib using clang++ and got no error. See my output below.
Can you tell me how to reproduce your issue?
Also maybe try without openssl and zlib (using: `make -Cexample CXX=clang++ OPENSSL_SUPPORT= ZLIB_SUPPORT="-Wl,--
as-needed -lws2_32"`) to make sure the issue is not related to the dependancies.

```
$ make -Cexample CXX=clang++ ZLIB_SUPPORT="-DCPPHTTPLIB_ZLIB_SUPPORT -lz -Wl,--
as-needed -lws2_32"
make: Entering directory '/R/winlibs64-10.1.0/cpp-httplib-0.6.5/example'
clang++ -o server -std=c++14 -I.. -Wall -Wextra -pthread server.cc -DCPPHTTPLIB_OPENSSL_SUPPORT -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lssl -lcrypto -DCPPHTTPLIB_ZLIB_SUPPORT -lz -Wl,--as-needed -lws2_32
clang++ -o client -std=c++14 -I.. -Wall -Wextra -pthread client.cc -DCPPHTTPLIB_OPENSSL_SUPPORT -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lssl -lcrypto -DCPPHTTPLIB_ZLIB_SUPPORT -lz -Wl,--as-needed -lws2_32
clang++ -o hello -std=c++14 -I.. -Wall -Wextra -pthread hello.cc -DCPPHTTPLIB_OPENSSL_SUPPORT -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lssl -lcrypto -DCPPHTTPLIB_ZLIB_SUPPORT -lz -Wl,--as-needed -lws2_32
clang++ -o simplecli -std=c++14 -I.. -Wall -Wextra -pthread simplecli.cc -DCPPHTTPLIB_OPENSSL_SUPPORT -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lssl -lcrypto -DCPPHTTPLIB_ZLIB_SUPPORT -lz -Wl,--as-needed -lws2_32
clang++ -o simplesvr -std=c++14 -I.. -Wall -Wextra -pthread simplesvr.cc -DCPPHTTPLIB_OPENSSL_SUPPORT -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lssl -lcrypto -DCPPHTTPLIB_ZLIB_SUPPORT -lz -Wl,--as-needed -lws2_32
clang++ -o upload -std=c++14 -I.. -Wall -Wextra -pthread upload.cc -DCPPHTTPLIB_OPENSSL_SUPPORT -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lssl -lcrypto -DCPPHTTPLIB_ZLIB_SUPPORT -lz -Wl,--as-needed -lws2_32
clang++ -o redirect -std=c++14 -I.. -Wall -Wextra -pthread redirect.cc -DCPPHTTPLIB_OPENSSL_SUPPORT -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lssl -lcrypto -DCPPHTTPLIB_ZLIB_SUPPORT -lz -Wl,--as-needed -lws2_32
clang++ -o sse -std=c++14 -I.. -Wall -Wextra -pthread sse.cc -DCPPHTTPLIB_OPENSSL_SUPPORT -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lssl -lcrypto -DCPPHTTPLIB_ZLIB_SUPPORT -lz -Wl,--as-needed -lws2_32
clang++ -o benchmark -std=c++14 -I.. -Wall -Wextra -pthread benchmark.cc -DCPPHTTPLIB_OPENSSL_SUPPORT -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -lssl -lcrypto -DCPPHTTPLIB_ZLIB_SUPPORT -lz -Wl,--as-needed -lws2_32
make: Leaving directory '/R/winlibs64-10.1.0/cpp-httplib-0.6.5/example'
```

**Comment by farta1986** [comment]
I'm so sorry for misleading. It occurs while building an app using this lib, not build this lib itself.

Just create an simple hello world app, use the all-in-one header for the lib;
`#include "httplib.h"

int main(void)
{
  using namespace httplib;

  Server svr;

  svr.Get("/hi", [](const Request& req, Response& res) {
    res.set_content("Hello World!", "text/plain");
  });

  svr.listen("localhost", 1234);
}
`
try to build it with clang:

```
D:\temp>clang++ 1.cc -lws2_32
C:\mingw\winlibs\mingw64\bin\ld: C:\Users\fayfa\AppData\Local\Temp\1-85fae2.o:1.cc:(.text+0x1e1): undefined reference to `pthread_mutex_init'
C:\mingw\winlibs\mingw64\bin\ld: C:\Users\fayfa\AppData\Local\Temp\1-85fae2.o:1.cc:(.text+0x21d): undefined reference to `pthread_mutex_lock'
C:\mingw\winlibs\mingw64\bin\ld: C:\Users\fayfa\AppData\Local\Temp\1-85fae2.o:1.cc:(.text+0x25d): undefined reference to `pthread_mutex_unlock'
C:\mingw\winlibs\mingw64\bin\ld: C:\Users\fayfa\AppData\Local\Temp\1-85fae2.o:1.cc:(.text+0x29d): undefined reference to `pthread_mutex_destroy'
C:\mingw\winlibs\mingw64\bin\ld: C:\Users\fayfa\AppData\Local\Temp\1-85fae2.o:1.cc:(.text$_ZNSt11this_thread9sleep_forIxSt5ratioILx1ELx1000EEEEvRKNSt6chrono8durationIT_T0_EE[_ZNSt11this_thread9sleep_forIxSt5ratioILx1ELx1000EEEEvRKNSt6chrono8durationIT_T0_EE]+0x99): undefined reference to `nanosleep'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
It won't change if we split all-in-one header to a header and a .cc file.
g++ works well.

**Comment by brechtsanders** [comment]
If you check my earlier response you see that the project's examples are compiled with `-pthread` so I think the command should be: `clang++ 1.cc -pthread -lws2_32`.
That works fine for me.

**Comment by farta1986** [comment]
> If you check my earlier response you see that the project's examples are compiled with `-pthread` so I think the command should be: `clang++ 1.cc -pthread -lws2_32`.
> That works fine for me.

I saw it. I just noticed that g++ has pthread lib linked by default and wonder if we can also add it to clang by default if clang also use gnu backend by default. If you believe this is not quite helpful that's also fine.

**Comment by brechtsanders** [comment]
It's good practice to compile with the `-pthread` parameter when building with `g++`.
Most configuration tools (like `./configure` or `cmake`) take care of this.

The goal of winlibs.com is not to modify the compiler but to build it for Windows with no code modifications if possible.

If you feel it is needed you should really take this up with the creators of clang.
