### ISSUE TITLE
Where is the winlibs with gcc10.5, help

### ISSUE THREAD

**Issue by britainlondon** [brechtsanders/winlibs_mingw#161]
Where is the winlibs with gcc10.5? 
Missed it? Or have you forgotten?

**Comment by brechtsanders** [comment]
Not forgotten, just busy building the other versions.
More like rebuilding since a new binutils was also just released.

**Comment by brechtsanders** [comment]
Just curious - Why is this older version important to you?

**Comment by brechtsanders** [comment]
https://github.com/brechtsanders/winlibs_mingw/releases/tag/10.5.0-11.0.1-msvcrt-r1
