### ISSUE TITLE
Failed build with -static key for libstdc++

### ISSUE THREAD

**Issue by CynicRus** [brechtsanders/winlibs_mingw#163]
Hello. When I try build something for windows with -static key, i got weird error.
This occurs every time when compiling C++ code for windows :/
Used version: GCC 13.2.0 (with POSIX threads) + LLVM/Clang/LLD/LLDB 16.0.6 + MinGW-w64 11.0.0 (UCRT) - release 1   
`-static -stdlib=libstdc++ -target x86_64-w64-mingw32 -O3 -DNDEBUG  CMakeFiles/sample.dir/main.cpp.obj CMakeFiles/sample.dir/foo.cpp.obj CMakeFiles/sample.dir/bar.cpp.obj -o sample.exe -Wl,--out-implib,libsample.dll.a -Wl,--major-image-version,0,--minor-image-version,0  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && :
ld.lld: error: undefined symbol: pthread_mutex_destroy
>>> referenced by libstdc++.a(eh_alloc.o):(.text$__tcf_0)
ld.lld: error: undefined symbol: pthread_mutex_lock
>>> referenced by libstdc++.a(eh_alloc.o):(.text$_ZN12_GLOBAL__N_14pool4freeEPv.constprop.0)
>>> referenced by libstdc++.a(eh_alloc.o):(.text$_ZN12_GLOBAL__N_14pool8allocateEy.constprop.0)
>>> referenced by R:/winlibs64ucrt_stage/gcc-13.2.0/build_mingw/x86_64-w64-mingw32/libgcc/./gthr-default.h:749
>>>               libgcc_eh.a(emutls.o):(__emutls_get_address)
ld.lld: error: undefined symbol: pthread_mutex_unlock
>>> referenced by libstdc++.a(eh_alloc.o):(.text$_ZN12_GLOBAL__N_14pool4freeEPv.constprop.0)
>>> referenced by libstdc++.a(eh_alloc.o):(.text$_ZN12_GLOBAL__N_14pool8allocateEy.constprop.0)
>>> referenced by R:/winlibs64ucrt_stage/gcc-13.2.0/build_mingw/x86_64-w64-mingw32/libgcc/./gthr-default.h:779
>>>               libgcc_eh.a(emutls.o):(__emutls_get_address)
ld.lld: error: undefined symbol: pthread_mutex_init
>>> referenced by libstdc++.a(eh_alloc.o):(.text.startup._GLOBAL__sub_I__ZN9__gnu_cxx9__freeresEv)
>>> referenced by R:/winlibs64ucrt_stage/gcc-13.2.0/build_mingw/x86_64-w64-mingw32/libgcc/./gthr-default.h:733
>>>               libgcc_eh.a(emutls.o):(emutls_init)
ld.lld: error: undefined symbol: pthread_key_create
>>> referenced by R:/winlibs64ucrt_stage/gcc-13.2.0/build_mingw/x86_64-w64-mingw32/libgcc/./gthr-default.h:708
>>>               libgcc_eh.a(emutls.o):(emutls_init)
ld.lld: error: undefined symbol: pthread_getspecific
>>> referenced by R:/winlibs64ucrt_stage/gcc-13.2.0/build_mingw/x86_64-w64-mingw32/libgcc/./gthr-default.h:720
>>>               libgcc_eh.a(emutls.o):(__emutls_get_address)
ld.lld: error: undefined symbol: pthread_once
>>> referenced by R:/winlibs64ucrt_stage/gcc-13.2.0/build_mingw/x86_64-w64-mingw32/libgcc/./gthr-default.h:700
>>>               libgcc_eh.a(emutls.o):(__emutls_get_address)
ld.lld: error: undefined symbol: pthread_setspecific
>>> referenced by R:/winlibs64ucrt_stage/gcc-13.2.0/build_mingw/x86_64-w64-mingw32/libgcc/./gthr-default.h:726
>>>               libgcc_eh.a(emutls.o):(__emutls_get_address)
>>> referenced by R:/winlibs64ucrt_stage/gcc-13.2.0/build_mingw/x86_64-w64-mingw32/libgcc/./gthr-default.h:726
>>>               libgcc_eh.a(emutls.o):(__emutls_get_address)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.`

**Comment by brechtsanders** [comment]
Yes, I had similar issues with the MCF build.
The solution is to add the `-pthread` linker flag.

**Comment by CynicRus** [comment]
> Yes, I had similar issues with the MCF build. The solution is to add the `-pthread` linker flag.

Ty for you answer, but in version: GCC 12.2.0 + LLVM/Clang/LLD/LLDB 16.0.0 + MinGW-w64 10.0.0 (UCRT) - release 5 its perfectly works.

**Comment by brechtsanders** [comment]
Thanks for the feedback. I don't know why this changed in GCC13.
