### ISSUE TITLE
Data errors when trying to unzip .7z of GCC 12.3.0 + LLVM 16.0.4 MSVCRT (release 1)

### ISSUE THREAD

**Issue by xamidi** [brechtsanders/winlibs_mingw#164]
File [winlibs-x86_64-posix-seh-gcc-12.3.0-llvm-16.0.4-mingw-w64msvcrt-11.0.0-r1.7z](https://github.com/brechtsanders/winlibs_mingw/releases/download/12.3.0-16.0.4-11.0.0-msvcrt-r1/winlibs-x86_64-posix-seh-gcc-12.3.0-llvm-16.0.4-mingw-w64msvcrt-11.0.0-r1.7z)
from [GCC 12.3.0 + LLVM 16.0.4 + MinGW-w64 11.0.0 MSVCRT (release 1)](https://github.com/brechtsanders/winlibs_mingw/releases/tag/12.3.0-16.0.4-11.0.0-msvcrt-r1)
results in data errors upon decompression with 7-Zip 22.01 (x64).
It works fine for the `.zip` file.

**Comment by brechtsanders** [comment]
Thanks for letting me know.
File has been replaced now.
