### ISSUE TITLE
LTO needs make, but somehow the environment MAKE is not working as expected

### ISSUE THREAD

**Issue by kayhayen** [brechtsanders/winlibs_mingw#165]
If I set `MAKE` to `mingw32-make.exe` it seems to work for 64 bits, but for 32 bits, I get a bunch of "the specified command cannot be found", e.g. 4 times during gcc link with `-lfto=20` i.e. without jobserver.

If I make that path absolute, with both 32 and 64 bits, it becomes as if I had not specified it and I am being warned about serial translation. No idea why that would make a difference. It seems that somehow (winlibs) gcc is making checks on the filename provided there. The make executable is always named like this, and works, but obviously different paths are used. gcc binary is in PATH when executing it.

Any idea where the code lives that consumes the MAKE environment and how to tell what command is not being found there?

**Comment by kayhayen** [comment]
Version should be latest, I am e.g. using `C:\Users\kayha\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw32\bin\mingw32-make.exe` with no luck.

**Comment by kayhayen** [comment]
As an aside, it is saying `Das System kann den angegebenen Pfad nicht finden.` i.e. giving me German error messages. If I mean to filter them, that's no good. But `LANG` and `LC_ALL` have no effect it seems, this must be Windows resolving the error message at some level.

**Comment by kayhayen** [comment]
I checked the gcc source code. It has special handling of `\` is the paths for the environment that `MAKE` is looked up from, trying to handle escape codes. For absolute paths on Windows, not a good idea, they are not going to be `\\` and as a result will not find the binary necessary.

As for the error, the makefile attempts to use `touch` and another command. The `touch` is not found, and gives the error. I believe the make might not be redirecting that standard error output properly, even if the code is doing `2> ...` it might be with a cmd that does not do it in that way, but that's why I have the error.

The reason I was having differences is that from `git bash` there is a `touch.exe` in my PATH. From cmd.exe in my CI there is not.

This is probably stuff to report upstream, but I am not sure that winlibs is really going to care. So I feel free to close it. I do not feel like I can report this to gcc, but in my Discord somebody who self-compiles it and has had the same issue, seems to be going to do it. So, from my point of view this is done.

What I am doing for Nuitka, is to filter out the error message by checking the "command not found" Windows message and ignoring that in your locale.

It's also a shame that `--keep-temps` effectively disables the touch usage in the makefile, and that the makefile is not kept and I was only able to see it in gcc source code. I think it ought to be able to keep it.

**Comment by brechtsanders** [comment]
I do most of my builds from the MSYS2 shell, so the backslash issue is probably not present in that scenario and touch does exist.

I'm a bit confused about the title. What does LTO have to do with this? Or are you referring to something other than link time optimization?

**Comment by kayhayen** [comment]
Without LTO (-flto=20 e.g.) the gcc does not use the `MAKE` environment and creates no makefile, and that is why. It does the partitioning, and apparently runs 4 paralell processes to do LTO in that case, with make being used. It could also use a "jobserver", but that I do not want to depend on.

Their use of `touch` is only to release file space sooner, they are temp truncating files when possible if done with them, but if not possible, they do not really care, i.e. ignore the error. Including the binaries in winlibs would be a clean solution, as would be patching out the need for gcc to have it.

**Comment by Peter0x44** [comment]
This is https://gcc.gnu.org/PR110710 and is fixed for gcc 15.
the driver itself now truncates files and doesn't use an external `touch` anymore.
