### ISSUE TITLE
gdb from the 10.5 release doesn't start

### ISSUE THREAD

**Issue by sterpumihai** [brechtsanders/winlibs_mingw#168]
Hi Brecht,

I tried using your 10.5 gcc release on Windows (https://github.com/brechtsanders/winlibs_mingw/releases/tag/10.5.0-11.0.1-msvcrt-r1) but I can't run gdb due to the following error:

`The procedure entry point _zSt28__throw_bad_array_new_lengthv could not be located in the dynamic link library`

https://imgur.com/a/G0uLfGP

I also tried analysing the libstdc++ library provided in the release, the missing function is there but with a different decoration.

https://imgur.com/a/Ds0fV4L

Could you please take a look? I'm really trying to understand what's wrong.
I'm on Windows 10 22H2.

**Comment by brechtsanders** [comment]
I was able to reproduce your problem.

In this new build it seems to be okay:
https://github.com/brechtsanders/winlibs_mingw/releases/tag/10.5.0-11.0.1-msvcrt-r2

**Comment by sterpumihai** [comment]
Thanks for the feedback! Do you also know what was the cause of that issue? I'm quite curious!

**Comment by brechtsanders** [comment]
See #160

**Comment by sterpumihai** [comment]
Ok I see it's somehow related to ncurses but I don't understand the connection. I know ncurses is used by gdb (for the text based gui) but I was more interested in the technical explanation ie. how the issue appears to begin with, what's the connection to libstdc++6.dll etc.

**Comment by brechtsanders** [comment]
I just think I made some error building/packaging the previous GCC10 release.

I usually don't put much effort in older versions, so I may have been too quick...
