### ISSUE TITLE
Does WinLibs have GNU Autotools?

### ISSUE THREAD

**Issue by anonymous7002** [brechtsanders/winlibs_mingw#17]
If it doesn't, it will be harder to configure source code programs because they have Makefile.am and .in.

**Comment by brechtsanders** [comment]
I use my compilers from the MSYS2 shell which already has the GNU autotools.
The goal of winlibs.com is not to make another shell environment. MSYS2 already does a great job.
The goal is to make a personal build with as much of the optional dependancies enabled, and then to build a large aount of libraries as possible in this environment. Currently I have done this for over 1500, but I'm working on standardization and package management before I'm ready to publish.
The combination with MSYS2 works great and I use GNU Autotools all the time, as well as other tools like CMake, Meson, Ninja, ...
