### ISSUE TITLE
Clang with MCF broken ?

### ISSUE THREAD

**Issue by spinell** [brechtsanders/winlibs_mingw#172]
Hi,I just found [winlibs_mingw](https://github.com/brechtsanders/winlibs_mingw) andI decide to give it a try.

I have downloaded the latest from https://winlibs.com/ (GCC 13.2.0 (with MCF threads) + LLVM/Clang/LLD/LLDB 16.0.6 + MinGW-w64 11.0.1 (UCRT) - release 2 ). I used the 64x version with clang.

I trying to build gtest (google test)  v1.14.0 and I got some weird error .

```
F:/tools/winlibs-x86_64-mcf-seh-gcc-13.2.0-llvm-16.0.6-mingw-w64ucrt-11.0.1-r2/mingw64/bin/ld: lib/Release/libgtest_no_exception.a(gtest-all.cc.obj):gtest-all.cc:(.text+0x2e473): undefined reference to `_MCF_mutex_lock_slow'

F:/tools/winlibs-x86_64-mcf-seh-gcc-13.2.0-llvm-16.0.6-mingw-w64ucrt-11.0.1-r2/mingw64/bin/ld: lib/Release/libgtest_no_exception.a(gtest-all.cc.obj):gtest-all.cc:(.text+0x2e4c1): undefined reference to `_MCF_mutex_unlock_slow'
```

I'm not familiar with clang/gcc so I'm wondering if I did something wrong.
This is how I build gtest.

```
    set GCC_CLANG=F:\tools\winlibs-x86_64-mcf-seh-gcc-13.2.0-llvm-16.0.6-mingw-w64ucrt-11.0.1-r2\mingw64\bin
    set PATH=%GCC_CLANG%;%PATH%
    SET BUILD_DIR=%BUILD_ROOT%\clang-16.0.6-mcf-seh-ucrt
    SET INTALL_DIR=%INSTALL_ROOT%\clang-16.0.6-mcf-seh-ucrt
    SET CC=clang.exe
    SET CXX=clang++.exe
    cmake -S path_to_gtest -B path_to_build_tree -Dgtest_build_tests:bool=ON
```

**Comment by brechtsanders** [comment]
To be honest the focus on winlibs is mostly on GCC and the MCF threads model is still quite new and probably not well supported by LLVM.

Does it work with `CC=gcc.exe` and `CXX=g++.exe`?

**Comment by spinell** [comment]
yes with gcc and g++ it work.
I was just wondering if I was doing something wrong with clang.

**Comment by brechtsanders** [comment]
No. Also note that [MCF threads](https://github.com/lhmouse/mcfgthread) are not ready for LLVM yet, shou I shouldn't have packaged LLVM in an MCF build.
