### ISSUE TITLE
Is it possible to link MSVC `.lib`?

### ISSUE THREAD

**Issue by ghost** [brechtsanders/winlibs_mingw#176]
I have the `.def` file, but no `.dll`. Only a `.lib`.

**Comment by ghost** [comment]
Hi. Please help me with https://github.com/brechtsanders/winlibs_mingw/issues/177. Thank you.

**Comment by brechtsanders** [comment]
`.lib` is an extension used by MSVC. For MinGW-W64 library import files end with `.a`.
What use is a `.def` file if you don't have the `.dll`?
If you have both you can probably use `dlltool` to create a `.dll.a` file.

**Comment by brechtsanders** [comment]
Something like this:
```sh
dlltool --compat-implib -D libmariadb.dll -d mariadbclient.def -l libmariadbclient.dll.a
```
