### ISSUE TITLE
Please help me translate this MSVC command

### ISSUE THREAD

**Issue by ghost** [brechtsanders/winlibs_mingw#177]
```
@SET OUTPUT=MyDll.DLL

@SET COMPILER_OPTION=/c /GF /GS- /MT /O2
@SET LINKER_OPTION=/base:0x60000000 /def:..\Main.DEF /dll /entry:DllMain /opt:NOWIN98 /out:%OUTPUT% /release /subsystem:windows

@SET INCLUDE=..\..;%INCLUDE%

@CALL CL %COMPILER_OPTION% ..\*.c
@CALL Link %LINKER_OPTION% *.obj kernel32.lib
```

Note: this is extracted from a batch script.

**Comment by brechtsanders** [comment]
I strongly recommend against mixing MSVC and GCC/MinGW-w64 compiled files.

They use different standard libraries, for example leading to incompatible memory management.
If the resulting application starts at all, you shouldn't assume its stable or for production use.

One exception is DLLs that were written with compatibility in mind that have an API that exposes nothing from the internally used standard library.
For example avoiding memory allocated by the caller being cleaned up inside a called function in the DLL.
