### ISSUE TITLE
New “repack”/release with new Gdb 14.1?

### ISSUE THREAD

**Issue by oscarbg** [brechtsanders/winlibs_mingw#178]

**Comment by oscarbg** [comment]
Hi,
thanks for release, but I'm getting an error launching it:
![imagen](https://github.com/brechtsanders/winlibs_mingw/assets/669305/893df560-f454-4630-a714-5ad7e6ea5a9c)

**Comment by brechtsanders** [comment]
You're right, there appears to be an unresolved dependency in gdb.exe in that release.
I will start building a new release...

**Comment by brechtsanders** [comment]
@oscarbg  Can you please check if this is fixed in https://github.com/brechtsanders/winlibs_mingw/releases/tag/13.2.0posix-17.0.6-11.0.1-msvcrt-r4 ?

**Comment by oscarbg** [comment]
now works! sorry for delay in testing.. vacation days..
