### ISSUE TITLE
Clang won't run on GitHub Actions

### ISSUE THREAD

**Issue by bwoodsend** [brechtsanders/winlibs_mingw#179]
This looks like a not fun one. As of the latest tag ([13.2.0posix-17.0.6-11.0.1-msvcrt-r3](https://github.com/brechtsanders/winlibs_mingw/releases/tag/13.2.0posix-17.0.6-11.0.1-msvcrt-r3)), clang is unable to do anything on GitHub Actions. There are no error messages – just an exit code of 127.

* [Minimal workflow](https://github.com/bwoodsend/winlibs-clang-issue/blob/0b47f0dd7f730af3fb5f572271a3c975f34fdb1d/.github/workflows/test.yml)
* [Example failure](https://github.com/bwoodsend/winlibs-clang-issue/actions/runs/7160392432/job/19494710240)

It works fine locally but I'm using wine rather than a real Windows machine so I'm not sure how much that really means.

**Comment by brechtsanders** [comment]
Why use the Windows build on Wine when there are mingw-w64 compilers for most Linux distributions?

Exit code 127 is usually caused by issues loading DLLs.

Try putting the full path to `mingw64/bin` at the beginning of the `PATH` environment variable.

If that works you probably had a conflicting DLL somewhere else in your `PATH`.

**Comment by bwoodsend** [comment]
> Why use the Windows build on Wine when there are mingw-w64 compilers for most Linux distributions?

I don't normally. I just saw the failure on CI, wanted to try and reproduce it locally but couldn't be bothered rebooting to my Windows partition.

> Try putting the full path to mingw64/bin at the beginning of the PATH environment variable.

That doesn't appear to have had any effect. With [`C:/mingw64/bin` in `PATH`](
https://github.com/bwoodsend/winlibs-clang-issue/actions/runs/7173132259/job/19531802353#step:4:142), I still get the 127 error.

**Comment by brechtsanders** [comment]
So the failure on CI was on actual Windows?

**Comment by brechtsanders** [comment]
Can you try to run `clang` with `gdb` to see which error you get there?

**Comment by bwoodsend** [comment]
Sorry for the delay – I'm struggling getting gdb to work non-interactively.

> So the failure on CI was on actual Windows?

Yes, just a normal GitHub Actions `windows-latest` runner. Forget I mentioned Wine – I was only trying to use it as a second point of reference.

> Can you try to run clang with gdb to see which error you get there?

Does clang need to be recompiled with `-g` or something for this to work? I can't get gdb to just run the thing. With a commands file:
```gdb
file ./mingw64/bin/clang
start
c
```
Running `gdb --batch -x commands -args ./mingw64/bin/clang -v` gives me
```
commands:2: Error in sourced command file:
No symbol table loaded.  Use the "file" command.
```

**Comment by brechtsanders** [comment]
`No symbol table loaded.` makes sense as my releases are stripped of symbol tables, to keep them small.

Are you sure you can leave out the `.exe` extension like that?

**Comment by bwoodsend** [comment]
> Are you sure you can leave out the .exe extension like that?

Hmm, probably not. Although adding it [hasn't made it any happier](https://github.com/bwoodsend/winlibs-clang-issue/actions/runs/7280347263/job/19838582932#step:7:1).

**Comment by brechtsanders** [comment]
What about `lldb` instead of `gdb` since we are talking about debugging `clang` after all?

**Comment by bwoodsend** [comment]
`lldb` also exits with status code 127 but I can get past that using `lldb` from `13.2.0-17.0.4-11.0.1-msvcrt-r2` instead. Unfortunately it looks like another dead end:

```
 $ ./old/mingw64/bin/lldb --batch -o 'run -v' ./mingw64/bin/clang.exe
(lldb) target create "./mingw64/bin/clang.exe"
Current executable set to 'D:\a\winlibs-clang-issue\winlibs-clang-issue\mingw64\bin\clang.exe' (x86_64).
(lldb) run -v
error: unknown error
```

**Comment by brechtsanders** [comment]
@bwoodsend Can you please check if these issues are resolved in https://github.com/brechtsanders/winlibs_mingw/releases/tag/13.2.0posix-17.0.6-11.0.1-msvcrt-r4 ?

**Comment by bwoodsend** [comment]
Yep, that's working well. Thanks!
