### ISSUE TITLE
Not well format when using vscode

### ISSUE THREAD

**Issue by Orion160x** [brechtsanders/winlibs_mingw#18]
When using vscode in the debugger the symbols such as std containers  as vector or string, are not shown with his values, instead are shown with some allocator bargain an other stuff.

**Comment by brechtsanders** [comment]
Is this using gdb.exe as debugger?

**Comment by Orion160x** [comment]
yes it is using gdb.exe as debugger
Mingw-w64 from Winlibs
![image](https://user-images.githubusercontent.com/61389980/84933814-101dda00-b09c-11ea-9468-345fc3b78432.png)

Mingw-w64 from Official page
![image](https://user-images.githubusercontent.com/61389980/84933653-d77e0080-b09b-11ea-96bc-0c751ceb4380.png)

sorry if im not specific about the details

**Comment by brechtsanders** [comment]
Very strange.
Just to make sure: 
- Each time you are using `gdb.exe` that comes with that specific MinGW-w64 distribution?
- Both times you have recompiled with that compiler from scratch before debugging?
- You're building with debugging symbols enabled (`-g`) each time?
- You don't have the other MinGW-w64's `bin` folder in your `PATH` when building with one MinGW-w64?

**Comment by Guyutongxue** [comment]
I think this issue is a duplicate of #2 . The GDB is built without Python, and the `pretty-printing` setup command cannot be executed. That's why those STL's debugging is so weird.

**Comment by Orion160x** [comment]
Yeah, its a duplicate these two issues are affected by the same problem in the build of gdb
