### ISSUE TITLE
CMake is missing libexpat-1.dll

### ISSUE THREAD

**Issue by kyrylo-sovailo** [brechtsanders/winlibs_mingw#189]
Hi. The cmake version packaged in winlibs is missing the libexpat-1.dll dependency. Expat developer have been refusing to make a 64-bit version for 7 years now, so in order to make cmake work you need to somehow compile libexpat yourself, using other tools. I did it using LLVM and cmake build from their website, and then compiled it again using winlibs gcc. It works perfectly, but this kind of bootstrapping is very annoying. Could you either compile expat in your build or get rid of this dependency somehow?

Thanks for your amazing work!

**Comment by brechtsanders** [comment]
Expat builds perfectly fine with GCC+MinGW-w64 on 32-bit and 64-bit Windows, and even on Windows on ARM64.

Normally I have a package script that automatically includes all dependency DLLs.

In which download exactly was this dependency missing?

**Comment by kyrylo-sovailo** [comment]
MSVCRT, GCC13.2.0, POSIX, without LLVM, zip. [this](https://github.com/brechtsanders/winlibs_mingw/releases/download/13.2.0posix-18.1.1-11.0.1-msvcrt-r6/winlibs-x86_64-posix-seh-gcc-13.2.0-mingw-w64msvcrt-11.0.1-r6.zip)

**Comment by brechtsanders** [comment]
The file you link to does contain `libexpat-1.dll` and `cmake.exe` runs perfectly.

Maybe this is an issue specifically on your system? For example the antivirus blocking/deleting `libexpat-1.dll`...
