### ISSUE TITLE
`libLLVMDemangle.dll.a`

### ISSUE THREAD

**Issue by ghost** [brechtsanders/winlibs_mingw#190]
```
CMake Error at C:/mingw64/lib/cmake/llvm/LLVMExports.cmake:686 (message):
  The imported target "LLVMDemangle" references the file

     "C:/mingw64/lib/libLLVMDemangle.dll.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "C:/mingw64/lib/cmake/llvm/LLVMExports.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  C:/mingw64/lib/cmake/llvm/LLVMConfig.cmake:275 (incude)
  CMakeLists.txt:12 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by ghost** [comment]
Indeed there is no LLVM import libraries in `mingw64/lib`. Btw, `libLLVMDemangle.dll` is in `mingw64/bin`.

**Comment by brechtsanders** [comment]
True, but I can include the LLVM `*.dll.a` file.

In which scenario where you needing these files?

**Comment by ghost** [comment]
> True, but I can include the LLVM `*.dll.a` file.
> 
> In which scenario where you needing these files?

Build https://github.com/AdeptLanguage/Adept. But I discovered that you only include libraries, not headers. So even if everything is fine with LLVM, I still have problems with CURL, ZLIB, ZSTD,... I still can't build it without MSYS2. This is the reason I closed this issue.

**Comment by brechtsanders** [comment]
The goal of the http://winlibs.com/ build packages is to provide the build tools.
The idea is not to bloat them too much with things that aren't part of the build tools themselves.

I'm working on a package manager [here](https://github.com/brechtsanders/winlibs_tools) and build recipes [here](https://github.com/brechtsanders/winlibs_recipes).

But I haven't published any binary packages yet as I haven't found time yet to figure out which ones can actually be distributed based on their license and under which conditions (e.g. including the license file in the binary package).

Note that building the packages on my side still requires MSYS2 shell, but I don't use the mingw-w64 build tools from MSYS2. Instead I use the ones I build myself.

**Comment by ghost** [comment]
When I build [qt6-tools](https://code.qt.io/cgit/qt/qttools.git/tag/?h=v6.7.0) using winlibs(13.2.0-17.0.6-11.0.1-ucrt-r5), I meet the same problem:
```
CMake Error at C:/Users/ausosa/scoop/apps/winlibs-mingw-llvm-ucrt/current/lib/cmake/llvm/LLVMExports.cmake:686 (message):
  The imported target "LLVMDemangle" references the file

     "C:/Users/ausosa/scoop/apps/winlibs-mingw-llvm-ucrt/current/lib/libLLVMDemangle.dll.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "C:/Users/ausosa/scoop/apps/winlibs-mingw-llvm-ucrt/current/lib/cmake/llvm/LLVMExports.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  C:/Users/ausosa/scoop/apps/winlibs-mingw-llvm-ucrt/current/lib/cmake/llvm/LLVMConfig.cmake:275 (include)
  C:/Users/ausosa/scoop/apps/winlibs-mingw-llvm-ucrt/current/lib/cmake/clang/ClangConfig.cmake:10 (find_package)
```

**Comment by ghost** [comment]
> When I build [qt6-tools](https://code.qt.io/cgit/qt/qttools.git/tag/?h=v6.7.0) using winlibs(13.2.0-17.0.6-11.0.1-ucrt-r5), I meet the same problem:
> 
> ```
> CMake Error at C:/Users/ausosa/scoop/apps/winlibs-mingw-llvm-ucrt/current/lib/cmake/llvm/LLVMExports.cmake:686 (message):
>   The imported target "LLVMDemangle" references the file
> 
>      "C:/Users/ausosa/scoop/apps/winlibs-mingw-llvm-ucrt/current/lib/libLLVMDemangle.dll.a"
> 
>   but this file does not exist.  Possible reasons include:
> 
>   * The file was deleted, renamed, or moved to another location.
> 
>   * An install or uninstall procedure did not complete successfully.
> 
>   * The installation package was faulty and contained
> 
>      "C:/Users/ausosa/scoop/apps/winlibs-mingw-llvm-ucrt/current/lib/cmake/llvm/LLVMExports.cmake"
> 
>   but not all the files it references.
> 
> Call Stack (most recent call first):
>   C:/Users/ausosa/scoop/apps/winlibs-mingw-llvm-ucrt/current/lib/cmake/llvm/LLVMConfig.cmake:275 (include)
>   C:/Users/ausosa/scoop/apps/winlibs-mingw-llvm-ucrt/current/lib/cmake/clang/ClangConfig.cmake:10 (find_package)
> ```

@brechtsanders So Brecht, you really need to add these import libraries.

**Comment by brechtsanders** [comment]
Okay, I can add these `.dll.a` files in a next release.

The focus of [winlibs](https://winlibs.com/) was initially on GCC, so LLVM wasn't that well tested.

If you insist on using LLVM, you may want to try https://github.com/mstorsjo/llvm-mingw

**Comment by brechtsanders** [comment]
The LLVM `.dll.a` files are included in today's releases.
