### ISSUE TITLE
How to use your MinGW with MSYS2?

### ISSUE THREAD

**Issue by superchick** [brechtsanders/winlibs_mingw#194]
Extract it to replace `C:\msys64\mingw64` and use the `MSYS2 MINGW64` shortcut?

**Comment by brechtsanders** [comment]
### From an IDE

If you use it from an IDE  (e.g. [Code::Blocks](https://www.codeblocks.org/)) just point your IDE to the location of the right tools, as explained [here](https://winlibs.com/#usage-codeblocks).

### From the MSYS2 shell

To use them from MSYS2 I use environment variables to make sure the [winlibs](https://winlibs.com/) tools are found first.
I typically do this by calling MSYS2's shell with a specific resource file to initialize these environment variables.
This also allows me to have multiple versions on the same system that I can run from different batch files.

This `.bat` file lives in the same folder as where the `mingw64` folder was extracted and typically contains something like this (you should adjust the location of MSYS2's `bash.exe` as needed):
```
@ECHO OFF
CD /D %~dp0
D:\Prog\msys64\usr\bin\bash.exe --noprofile --rcfile profile_settings_64.sh -i
```

The `profile_settings_64.sh` file domething like this:
```
#!/bin/sh
PATH=/usr/bin:$PATH PROFILEROOT=$(cygpath $(dirname $(realpath ${BASH_ARGV:-$0})))
export BUILDPLATFORM=x86_64-w64-mingw32
export MINGWDIR=$PROFILEROOT/mingw64
export PATH=$MINGWDIR/$BUILDPLATFORM/bin:/usr/bin:$(cygpath $WINDIR)/system32:$(cygpath $WINDIR)
export HOME=$PROFILEROOT/home64
export CPATH=$MINGWPREFIX/include:$PROFILEROOT/mingw64/include
export LIBRARY_PATH=$MINGWPREFIX/lib:$PROFILEROOT/mingw64/lib
mkdir -p $HOME
export PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[0m\]\[\e[33m\]\w\[\e[0m\]\n\$'
export PS2='> '
export PS3='? '
export PS4='+ '
```
