### ISSUE TITLE
Will you add more POSIX tools?

### ISSUE THREAD

**Issue by ghost** [brechtsanders/winlibs_mingw#195]
Like [cs_mingw_w64](https://github.com/copperspice/cs_mingw_w64)?

**Comment by brechtsanders** [comment]
The goal is to provide the build tools, not a complete shell environment.

Personally I build everything inside an MSYS2 shell, but using the [winlibs](https://winlibs.com/) build tools.

Though it would be fantastic to have a complete standalone shell environment (e.g. like BusyBox) that supports things like autotools, reinventing that wheel will would sidetrack this project too much.
