### ISSUE TITLE
Please patch your `cmake` to generate `Ninja` by default

### ISSUE THREAD

**Issue by ghost** [brechtsanders/winlibs_mingw#197]
It looks like yours is vanilla `cmake`, because vanilla `cmake` generates `nmake` by default on Windows. MSYS2 patched their `cmake`. On MinGW environments, their `cmake` will generate `Ninja` by default.

**Comment by brechtsanders** [comment]
That was never an issue for me as I always specify `-G` (`-GNinja`  or `-G"MSYS Makefiles"`).

Apparently you can also use environment variable `CMAKE_GENERATOR`.

But I made the change in my build recipe [here](https://github.com/brechtsanders/winlibs_recipes/blob/main/recipes/cmake.winlib).

After all nothing builds as fast as Ninja...
