### ISSUE TITLE
Clang missing ASAN libraries

### ISSUE THREAD

**Issue by partouf** [brechtsanders/winlibs_mingw#200]
At Compiler Explorer we use your compiler distributions, and we recently had someone ask about the sanitize feature from Clang.

Example 'regular Clang' vs mingw Clang: https://compiler-explorer.com/z/ze648aTY3

The linker will complain about a missing `libclang_rt.asan_dynamic-x86_64.dll.a` and `libclang_rt.asan_dynamic_runtime_thunk-x86_64.a`
The directories don't contain any Asan dll's either

According to the Clang documentation, Windows does somewhat support it https://clang.llvm.org/docs/AddressSanitizer.html#supported-platforms - but I'll be honest, I don't have a clue myself if it really is.

You do have to build Clang with `-DLLVM_ENABLE_RUNTIMES="compiler-rt"` (on Linux we build with a bunch of those ourselves https://github.com/compiler-explorer/clang-builder/blob/main/build/build.sh#L189)

Do you think it's possible to include in future builds?

**Comment by brechtsanders** [comment]
The goal of http://winlibs.com/ was to provide build for GCC.

On popular request LLVM/CLang was added, but to allow for the mix of the two, it was a build based on GCC's runtimes.

For what you are asking you would need a build of LLVM/CLang with it's own runtime built against MinGW-w64.

Such a built can be found at https://github.com/mstorsjo/llvm-mingw

Maybe that one will suite your needs?

**Comment by partouf** [comment]
Thanks! I'll look into it
