### ISSUE TITLE
nvptx-arch.exe virus detection by Windows Defender as Trojan:Win32/Phonzy.A!ml and has 31/70 VirusTotal detections

### ISSUE THREAD

**Issue by theo543** [brechtsanders/winlibs_mingw#201]
VirusTotal link: https://www.virustotal.com/gui/file/836de615c45dae047bb3aa55526ec2329c2de1a8a14e55ac6bf16dfa89716179

winlibs personal build version gcc-13.2.0-llvm-18.1.3-mingw-w64ucrt-11.0.1-r7

There are also detections for llvm-string.exe but there's already an issue for that.

I know false positives happen, but 31/70 is a lot, is it possible these files really are compromised? Will something break if I just delete them?

**Comment by brechtsanders** [comment]
The file `nvptx-arch.exe` is only used by LLVM in relation to the NVidia GPU platform. If you're not doing any GPU stuff you can go ahead and delete it.
