### ISSUE TITLE
bits/extc++.h support

### ISSUE THREAD

**Issue by ryanbai1412** [brechtsanders/winlibs_mingw#202]
Currently, when compiling
```cpp
#include "bits/extc++.h"

int main() {}
```
I get a compilation error
```
In file included from C:/Programs/gcc13-64-winlibs/include/c++/13.2.0/x86_64-w64-mingw32/bits/extc++.h:83,
                 from program.cpp:1:
C:/Programs/gcc13-64-winlibs/include/c++/13.2.0/ext/codecvt_specializations.h:42:10: fatal error: iconv.h: No such file or directory
   42 | #include <iconv.h>
      |          ^~~~~~~~~
compilation terminated.
```

I did a bit of digging, and it seems like headers using `iconv()` are being incorrectly included because `_GLIBCXX_HAVE_ICONV` is defined in c++config.h [link1](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/precompiled/extc%2B%2B.h#L82-L85), [link2](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/config.h.in#L171).

**Comment by brechtsanders** [comment]
For now https://winlibs.com/ only provides the build tools, but no libraries yet.

You can get libiconv from https://www.gnu.org/software/libiconv/ and compile it yourself.

I am working on a [package manager](https://github.com/brechtsanders/winlibs_tools) and [build recipes](https://github.com/brechtsanders/winlibs_recipes) to make libraries available in the future.
