### ISSUE TITLE
GCC 14 now supports C++11 theads with Win32 thread model

### ISSUE THREAD

**Issue by ghost** [brechtsanders/winlibs_mingw#204]
Is it time to also provide builds based on Win32 thread model?

**Comment by brechtsanders** [comment]
Been there done that.

It was a real hassle doing both, and a lot of libraries wouldn't build with the Win32 thread model because of missing POSIX threads. 

If have been looking at [the MCF Gthread Library](https://github.com/lhmouse/mcfgthread) because it does have POSIX compatible threads but uses a more native Windows implementation. Unfortunately it's not mature enough as I have some things that won't build with it.

**Comment by brechtsanders** [comment]
By the way, I just released a new build with the MCF Gthread thread model:
https://github.com/brechtsanders/winlibs_mingw/releases/tag/14.1.0mcf-11.0.1-ucrt-r1

Note that the non Win32 thread builds still have all the Win32 thread possibilities from the Windows API.

**Comment by ghost** [comment]
@brechtsanders Please consider bringing back Win32 thread model builds as people wanting MCF thread model have their own toys to play now (see #242). You can drop MCF thread model builds to have room for Win32 thread model builds.

**Comment by brechtsanders** [comment]
Sorry, I will be sticking to the POSIX model for maximum compatibility/portability.
Note that all the Win32 threading functions are available no matter which model you use, as they are part of the MinGW-w64 libraries.

**Comment by ghost** [comment]
Win32 threading functions are not the same thing as Win32 thread model. C++11 threads now support Win32 thread model. People using the high level C++ threads API now can happily switch back and forth between Win32 thread model and POSIX thread model without having to change their code. This is the benefits of Win32 thread model.

Of course for maximum compatibility/portability, you can still stick with POSIX thread model for building your receipts. But you should provide Win32 thread model builds. People can choose what suit them best.

BTW, I have never told you to switch to use Win32 thread model.

**Comment by ghost** [comment]
I still think that MCF thread model builds should be dropped. The author of MCF thread model now providing their own builds.

**Comment by ghost** [comment]
It will be interesting to see if the issue with `clang++` and `-static` is still there in Win32 thread model or not.

**Comment by chawyehsu** [comment]
> I still think that MCF thread model builds should be dropped.

It's already the fact that there hasn't been mcf builds since Aug...

**Comment by ghost** [comment]
> It will be interesting to see if the issue with `clang++` and `-static` is still there in Win32 thread model or not.

Does Clang support Win32 thread model?

**Comment by ghost** [comment]
> > I still think that MCF thread model builds should be dropped.
> 
> It's already the fact that there hasn't been mcf builds since Aug...

Because there is nothing new in the GCC world. Still GCC 14.2. The new builds are for updating LLVM, and Clang doesn't support what is called MCF thread model. Only GCC supports MCF thread model. There is no such thing for Clang. If you pay a little more notice, you will see MCF thread model builds are GCC only (LLVM is not included).

**Comment by ghost** [comment]
> > It will be interesting to see if the issue with `clang++` and `-static` is still there in Win32 thread model or not.
> 
> Does Clang support Win32 thread model?

I don't know. But Win32 thread model is official, not a third-party effort like MCF thread model, so I think it will be supported.

**Comment by xtemp09** [comment]
> a lot of libraries wouldn't build with the Win32 thread model because of missing POSIX threads.


@brechtsanders, if I may ask, what libraries cannot be built because of missing _POSIX_ threads? Is there any update on your opinion? I have stumbled over this:[^1]



> The GNU threads library used by the win32 thread model has been reimplemented using direct Win32 API calls, except for the Objective-C specific subset. It requires Windows XP/Server 2003 or later. The new implementation also adds the support needed for the C++11 threads, using again direct Win32 API calls; this additional layer requires Windows Vista/Server 2008 or later. It is recommended to use a recent version of MinGW-W64 in conjunction with the win32 thread model.


Is it the right time to provide _win32_ toolchains?









[^1]: https://gcc.gnu.org/gcc-13/changes.html

**Comment by brechtsanders** [comment]
Several sourced failed to build. The first ones that comes to mind are [libucommon](http://www.gnu.org/software/commoncpp/) and [XDispatch](http://opensource.mlba-team.de/xdispatch/docs/current/), but there are many more.

I would need a lot of time (which I don't have) to investigate why they won't build and if they need fixes.
