### ISSUE TITLE
Compilation error on perl building with latest release

### ISSUE THREAD

**Issue by g-bougard** [brechtsanders/winlibs_mingw#205]
Building perl 5.38.2 for GLPI-Agent, I tested the latest version winlibs 14.1.0posix-18.1.5-11.0.1-msvcrt-r1.
And it failed on Posix.dll building saying putenv() is not available: (full log in [this GH Actions run](https://github.com/glpi-project/glpi-agent/actions/runs/9030123267/job/24813775978))
```
gcc -c   -DWIN32 -DWIN64 -DPERL_TEXTMODE_SCRIPTS -DMULTIPLICITY -DPERL_IMPLICIT_SYS -DUSE_PERLIO -D__USE_MINGW_ANSI_STDIO -fwrapv -fno-strict-aliasing -mms-bitfields -Os   -DVERSION=\"2.13\" -DXS_VERSION=\"2.13\"  "-I..\..\lib\CORE"   POSIX.c
POSIX.xs: In function 'fix_win32_tzenv':
POSIX.xs:1727:13: error: implicit declaration of function 'putenv'; did you mean '_putenv'? [-Wimplicit-function-declaration]
 1727 |             putenv(newenv);
      |             ^~~~~~
      |             _putenv
POSIX.c: In function 'XS_POSIX__Termios_getattr':
POSIX.c:2126:31: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 2126 |                 termios_ref = (POSIX__Termios)SvPV_nolen(SvRV(sv));
      |                               ^
POSIX.c: In function 'XS_POSIX__Termios_setattr':
POSIX.c:2182:31: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 2182 |                 termios_ref = (POSIX__Termios)SvPV_nolen(SvRV(sv));
      |                               ^
POSIX.c: In function 'XS_POSIX__Termios_getispeed':
POSIX.c:2249:31: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 2249 |                 termios_ref = (POSIX__Termios)SvPV_nolen(SvRV(sv));
      |                               ^
POSIX.c: In function 'XS_POSIX__Termios_getiflag':
POSIX.c:2281:31: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 2281 |                 termios_ref = (POSIX__Termios)SvPV_nolen(SvRV(sv));
      |                               ^
POSIX.c: In function 'XS_POSIX__Termios_getcc':
POSIX.c:2334:31: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 2334 |                 termios_ref = (POSIX__Termios)SvPV_nolen(SvRV(sv));
      |                               ^
POSIX.c: In function 'XS_POSIX__Termios_setispeed':
POSIX.c:2374:31: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 2374 |                 termios_ref = (POSIX__Termios)SvPV_nolen(SvRV(sv));
      |                               ^
POSIX.c: In function 'XS_POSIX__Termios_setiflag':
POSIX.c:2416:31: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 2416 |                 termios_ref = (POSIX__Termios)SvPV_nolen(SvRV(sv));
      |                               ^
POSIX.c: In function 'XS_POSIX__Termios_setcc':
POSIX.c:2464:31: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 2464 |                 termios_ref = (POSIX__Termios)SvPV_nolen(SvRV(sv));
      |                               ^
POSIX.xs: In function 'XS_POSIX_ctermid':
POSIX.xs:1462:20: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 1462 | #define ctermid(x) (char *) not_here("ctermid")
      |                    ^
POSIX.xs:3639:18: note: in expansion of macro 'ctermid'
 3639 |         RETVAL = ctermid(s);
      |                  ^~~~~~~
POSIX.c: In function 'XS_POSIX_ttyname':
POSIX.xs:1383:22: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 1383 | #  define ttyname(a) (char*)not_here("ttyname")
      |                      ^
POSIX.c:5453:18: note: in expansion of macro 'ttyname'
 5453 |         RETVAL = ttyname(fd);
      |                  ^~~~~~~
gmake[1]: *** [makefile:335: POSIX.o] Error 1
```
I'm rolling back to the previous version (13.2.0posix-18.1.5-11.0.1-msvcrt-r8) which works as expected.

Is it possible some lib or include files are missing in the latest release ?

**Comment by brechtsanders** [comment]
I've seen a lot of these errors too. This is not specifically related to the winlibs build, but to GCC 14 which seems to be stricter in this regard.

The root cause is usually calling a function that was not yet defined (e.g. because the necessary `#include` is missing).

Since so many software packages suffer from this issue my solution is to change my build recipes to use compiler flag `-Wno-implicit-function-declaration` to ignore these errors (as previous versions did).

**Comment by Alcaro** [comment]
I'd recommend -Wno-error=implicit-function-declaration instead. That will demote them to warnings, so they'll show up somewhere and the maintainers can fix them, but warnings are unlikely to break CIs. (There's already a pile of warnings over there, anyways.)

**Comment by brechtsanders** [comment]
`-Wno-error=implicit-function-declaration` and `-Wno-implicit-function-declaration` are synonyms.

**Comment by Alcaro** [comment]
Can't reproduce, they look different to me. https://godbolt.org/z/Kvxe5M6sa

Perhaps some of your other compiler flags change enough defaults that they end up synonymous. Godbolt tries staying close to upstream, while you're focusing more on usability in practice.

**Comment by sisyphus** [comment]
> And it failed on Posix.dll building saying putenv() is not available

I struck the same using the "UCRT" variant of the same compiler to build the current perl devel release (5.39.10).
Looks like we can expect the same issue with perl-35.40 (due later this month) - unless someone manages to get a last minute fix inserted into the  win32/GNUmakefile.

I found <code>-Wno-error=implicit-function-declaration</code> to do the job just fine, and all tests passed.

**Comment by brechtsanders** [comment]
I stand corrected.

So `-Wno-error=implicit-function-declaration` turns the error into a warning, while `-Wno-implicit-function-declaration` completely ignores the issue showing no warning or error.

But both of them allow the build to complete.
