### ISSUE TITLE
Winlibs GCC Cannot Decode UTF-8 Path Correctly

### ISSUE THREAD

**Issue by wanzzhehe** [brechtsanders/winlibs_mingw#206]
Hello,

Thank you very much for your work. However, I have encountered some tricky path encoding issues while using GCC.

For some reasons, I switched my Windows encoding format from the traditional GBK encoding to UTF-8 encoding. However, WinLibs, when I use it in a Chinese environment, attempts to parse paths in the command line using GBK encoding mode, which causes it to fail to correctly output files. Is this issue a bug? Could it be fixed?

Thank you.

Example:
![image](https://github.com/brechtsanders/winlibs_mingw/assets/26498686/35951292-ebb5-4e58-ae26-1e1f51309e40)

**Comment by brechtsanders** [comment]
Basically the winlibs builds are just a combination of existing software tools. To support special characters in paths all these tools would need to support this.

I still recommend to keep the build environments in paths without special characters. Even a space in a path may mess things up.

Having said that, that's just the build environment. It doesn't stop you from writing your own software with support for UTF-8 (or other encodings).

Anyway, if the issue you encountered is in tools like gcc or binutils, you should log the issue with them.

Finally, I see you included a screenshot that doesn't look like a command line. Is that VS Code or some other IDE? Maybe the issue you're having is in there?

**Comment by wanzzhehe** [comment]
Thank you for your response. The screenshot attached is of the left-hand file sidebar in Visual Studio Code. It illustrates the issue of file names being severely garbled in the output.

Here is a rough sketch to illustrate:

> [Folder name contains chinese characters]
> -> main.cpp
> 
> [Wrong characters]main.exe

**Comment by wanzzhehe** [comment]
Interestingly, Mingw-builds resolves file names using UTF-8 in a GBK environment, which is the opposite of the issue with WinLibs.

**Comment by brechtsanders** [comment]
Can you please be more clear about which products you are talking?

The https://winlibs.com/ builds are using standard sources from GCC, binutils, MinGW-w64, ...

It's not clear to me what exactly you are comparing or where the issues are exactly.
