### ISSUE TITLE
mfmediaengine.h missing

### ISSUE THREAD

**Issue by RoyalXXX** [brechtsanders/winlibs_mingw#208]
I downloaded **GCC 14.1.0 (with POSIX threads) + MinGW-w64 11.0.1 (UCRT) - release 1** from **winlibs.com**.
But I can't find the `mfmediaengine.h` header. It's missing.

**Comment by brechtsanders** [comment]
I don't believe this file is part of MinGW-w64 11.0.1.

Are you expecting it to be in there?

**Comment by RoyalXXX** [comment]
> I don't believe this file is part of MinGW-w64 11.0.1.
> 
> Are you expecting it to be in there?

This file, for example, is present in MSYS2 `mingw-w64-ucrt-x86_64-toolchain`.
But you're right. They copied this header from Wine (https://gitlab.winehq.org/wine/wine/-/blob/master/include/mfmediaengine.idl?ref_type=heads)

**Comment by brechtsanders** [comment]
I opened the following ticket with MinGW-w64: https://sourceforge.net/p/mingw-w64/support-requests/196/

**Comment by chawyehsu** [comment]
> This file, for example, is present in MSYS2 `mingw-w64-ucrt-x86_64-toolchain`.

`mingw-w64-ucrt-x86_64-toolchain` is backed by `mingw-w64-headers-git` the nightly mingw-w64

**Comment by chawyehsu** [comment]
@brechtsanders How about providing [snapshot builds](https://github.com/brechtsanders/winlibs_mingw/releases?q=snapshot&expanded=true) with the nightly mingw-w64 included instead.

**Comment by brechtsanders** [comment]
Is there a nightly tarball for MinGW-w64 I can use?

**Comment by chawyehsu** [comment]
I believe you can just get one from its GitHub mirror using urls like this:

- always at the latest commit on master branch:
  https://github.com/mingw-w64/mingw-w64/archive/refs/heads/master.tar.gz
- specific commit (prefer as deterministic):
  https://github.com/mingw-w64/mingw-w64/archive/f10e1f17d06cbe0240f948c0afd3aee81ac72a40.tar.gz

the same(or pretty similar) way llvm-mingw tracking rather newer mingw-w64 (based on specific commit hashs)
