### ISSUE TITLE
`<print>` not fully implemented in Winlibs GCC 14.1.0?

### ISSUE THREAD

**Issue by chikega** [brechtsanders/winlibs_mingw#209]
Using `GCC 14.1.0` with `-std=c++2b` on godbolt, my code(see below) compiles fine. But my Winlibs version appears to be having linker errors with undefined references to `std::__open_terminal` and `std::__write_to_terminal` which appear to be internal functions used by `std::println`.  

```
 g++ -std=c++2b -Wall -Wextra -pedantic cpp23_println.cpp -o prog.exe
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\chike\AppData\Local\Temp\ccSCyjIG.o:cpp23_println.:(.text$_ZSt14vprint_unicodeP6_iobufSt17basic_string_viewIcSt11char_traitsIcEESt17basic_format_argsISt20basic_format_contextINSt8__format10_Sink_iterIcEEcEE[_ZSt14vprint_unicodeP6_iobufSt17basic_string_viewIcSt11char_traitsIcEESt17basic_format_argsISt20basic_format_contextINSt8__format10_Sink_iterIcEEcEE]+0x197): undefined reference to `std::__open_terminal(_iobuf*)'
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\chike\AppData\Local\Temp\ccSCyjIG.o:cpp23_println.:(.text$_ZSt14vprint_unicodeP6_iobufSt17basic_string_viewIcSt11char_traitsIcEESt17basic_format_argsISt20basic_format_contextINSt8__format10_Sink_iterIcEEcEE[_ZSt14vprint_unicodeP6_iobufSt17basic_string_viewIcSt11char_traitsIcEESt17basic_format_argsISt20basic_format_contextINSt8__format10_Sink_iterIcEEcEE]+0x24d): undefined reference to `std::__write_to_terminal(void*, std::span<char, 18446744073709551615ull>)'
collect2.exe: error: ld returned 1 exit status
```
Using a very simple example:
```cpp
#include <iostream>
using std::cout;
using std::endl;
#include <print> // C++23 feature
using std::println;
#include <format> // C++20 feature
using std::format;

int main()
{
    int answer {42};  
    println("The answer to life, the universe, and everything is {}.", answer);
    cout << format("The answer to life, the universe, and everything is {}.", answer) << endl; 

    return 0;
}
```

**Comment by brechtsanders** [comment]
I assume your example is using things considered to be experimental, because if you add linker flag `-lstdc++exp` it builds fine.

**Comment by chikega** [comment]
> I assume your example is using things considered to be experimental, because if you add linker flag `-lstdc++exp` it builds fine.

Thank you for your quick response. Yes, I tried that previously and it does compile fine. But when I run the executable, there is no output. The lack of output when running the program suggests that there might be an issue with the implementation of `std::println` in the experimental library?

**Comment by brechtsanders** [comment]
I tried it here and I did yet the expected output.

**Comment by chikega** [comment]
I did a fresh install of everything on a newer PC and it does work. I'll have to look at what's going on with my development laptop. Thank you for checking!

**Comment by brechtsanders** [comment]
My guess would be you have another version on your system and environment variables pointing to it.

**Comment by chikega** [comment]
You are correct. A couple other GCC's associated with GNAT Studio and Embarcadero had higher precedence in the environment variables. So I moved `C:\mingw64\bin` up to the top and now it works on my development laptop. Thank you for your patience!

**Comment by brechtsanders** [comment]
I always recommend not to change any global environment variables.
These things should be configured only inside build environments and/or IDEs.

**Comment by chikega** [comment]
Just to clarify, did you mean to write "I alway recommend to NOT change any global ..."?

**Comment by brechtsanders** [comment]
@chikega Yes, sorry for the typo.
