### ISSUE TITLE
remove mingw32 prefix for make

### ISSUE THREAD

**Issue by anb0s** [brechtsanders/winlibs_mingw#21]
All executables in the bin folder have no prefix except **make** : **mingw32**-make.exe

For IDEs like Eclipse (CDT) the prefix can be configured and is automatically used for all executables. For make it has to be configured addionally.

Please remove the prefix to have all executables named consistently if poosible. Thanks!

**Comment by anb0s** [comment]
I'm using the latest distro **winlibs-x86_64-posix-seh-gcc-10.1.0-llvm-10.0.0-mingw-w64-7.0.0-r3**

**Comment by brechtsanders** [comment]
They do have a prefix, here's a screenshot illustrating this:
![image](https://user-images.githubusercontent.com/17645177/86513416-5304df00-be0a-11ea-916d-425351ed66f5.png)

Make is an exception as it's not part of gcc or binutils, and the mingw32- prefix is there to avoid confusion with MSYS2's make.

Note that is is a MinGW-w64 build, not the old MinGW.

This works fine in an IDE like Code::Blocks (see http://winlibs.com/#usage-codeblocks for instructions).

People are also using the winlibs personal build from Visual Studio Code.

**Comment by anb0s** [comment]
We migrated from the https://nuwen.net/ distribution and there all executables are without any prefixes (make is in both variants):
![image](https://user-images.githubusercontent.com/95811/86517294-2069df00-be28-11ea-8fe7-8bbd27788df5.png)

winlibs has also same files you showed without the prefix:
![image](https://user-images.githubusercontent.com/95811/86517126-b0a72480-be26-11ea-87bf-d697bd7fcc56.png)

clang and another are without too. From my experience most tools (IDEs, build systems etc.) just works and automatically detect all of the tools if the bin path is configured - only make has to be configured explicitly.

It's just about usibility for beginners (junior devs) and not an  issue for me. Sorry to bother you with this and thank you for the great distro!
