### ISSUE TITLE
What is "R:/winlibs64ucrt_stage/inst_gcc-13.2.0/share/gcc/include"?

### ISSUE THREAD

**Issue by 1298345095** [brechtsanders/winlibs_mingw#211]
When I try "g++ main.cpp -v -o a.exe", it shows information including this path. But I haven't this path.

**Comment by brechtsanders** [comment]
`R:/winlibs64ucrt_stage/inst_gcc-13.2.0` was the path used by my build process, it's normal that you don't have it.

**Comment by 1298345095** [comment]
Can I remove this?

**Comment by brechtsanders** [comment]
Sure, but I'm not sure exactly where you will remove this.
