### ISSUE TITLE
problem related to mingw

### ISSUE THREAD

**Issue by youlha1** [brechtsanders/winlibs_mingw#214]
hello, im sorry for posting this in hear i dont know where i could reach out to you, today windows defender picked 'libLLVMX86Desc.dll' from mingw build, i downloaded from winlibs as thread and also by a lot of AVs on virustotal 'https://www.virustotal.com/gui/file/6c68b133eb27d41c67461afb2a5810471bfccd3bc4769aee1275acb79c89d325'
could this be just a mistake or maybe there's something shady going on?
![ApplicationFrameHost_aEL48jVIuh](https://github.com/brechtsanders/winlibs_mingw/assets/101402094/89465267-916d-4219-af62-1060a66cd5fa)

**Comment by Alcaro** [comment]
Isn't this same as #199?

Why are the scanners complaining about all the llvm and none of the gcc?

**Comment by youlha1** [comment]
yeah but it's weird, ive been using it for year now and i never got such thing, i hope its just a mistake.

**Comment by brechtsanders** [comment]
If possible don't use the download with LLVM.
It's unclear why building LLVM with recent versions of GCC generates so many virus warnings.

**Comment by brechtsanders** [comment]
Yes, duplicate case for #199
