### ISSUE TITLE
ICE in GCC 14.1.0 when attempting to preprocess C++ source files with precompiled header included with compiler option -include

### ISSUE THREAD

**Issue by luisdallos** [brechtsanders/winlibs_mingw#217]
An internal compiler error is triggered in GCC 14.1.0 when attempting to preprocess C++ source files with precompiled header included with compiler option `-include` (note: including the precompiled header in the source code (with `#include`) instead works fine). A testcase is provided below:

`test.h`
``` C
#include <cstdio>
```
`test.cpp`
``` C
int main()
{
    ::printf("Hello world...\n");
    return 0;
}
```

To reproduce this issue:
```
g++ -x c++-header -c test.h -o test.pch.gch
g++ -include test.pch -fpch-preprocess -E test.cpp -o test.ii
```

The last command produces the following output:
```
test.cpp:1: internal compiler error: in c_init_preprocess, at cp/parser.cc:790
    1 | int main()
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://gcc.gnu.org/bugs/> for instructions.
```

Compiler information:
```
Using built-in specs.
COLLECT_GCC=K:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=K:/msys64/mingw64/bin/../libexec/gcc/x86_64-w64-mingw32/14.1.0/lto-wrapper.exe
OFFLOAD_TARGET_NAMES=nvptx-none
Target: x86_64-w64-mingw32
Configured with: ../configure --prefix=/R/winlibs64_stage/inst_gcc-14.1.0/share/gcc --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --enable-offload-targets=nvptx-none --with-pkgversion='MinGW-W64 x86_64-msvcrt-posix-seh, built by Brecht Sanders, r1' --with-tune=generic --enable-checking=release --enable-threads=posix --disable-sjlj-exceptions --disable-libunwind-exceptions --disable-serial-configure --disable-bootstrap --enable-host-shared --enable-plugin --disable-default-ssp --disable-rpath --disable-libstdcxx-debug --disable-version-specific-runtime-libs --with-stabs --disable-symvers --enable-languages=c,c++,fortran,lto,objc,obj-c++ --disable-gold --disable-nls --disable-stage1-checking --disable-win32-registry --disable-multilib --enable-ld --enable-libquadmath --enable-libada --enable-libssp --enable-libstdcxx --enable-lto --enable-fully-dynamic-string --enable-libgomp --enable-graphite --enable-mingw-wildcard --enable-libstdcxx-time --enable-libstdcxx-pch --with-mpc=/d/Prog/winlibs64_stage/custombuilt --with-mpfr=/d/Prog/winlibs64_stage/custombuilt --with-gmp=/d/Prog/winlibs64_stage/custombuilt --with-isl=/d/Prog/winlibs64_stage/custombuilt --disable-libstdcxx-backtrace --enable-install-libiberty --enable-__cxa_atexit --without-included-gettext --with-diagnostics-color=auto --enable-clocale=generic --with-libiconv --with-system-zlib --with-build-sysroot=/R/winlibs64_stage/gcc-14.1.0/build_mingw/mingw-w64 CFLAGS='-I/d/Prog/winlibs64_stage/custombuilt/include/libdl-win32   -march=nocona -msahf -mtune=generic -O2 -Wno-error=format' CXXFLAGS='-Wno-int-conversion  -march=nocona -msahf -mtune=generic -O2' LDFLAGS='-pthread -Wl,--no-insert-timestamp -Wl,--dynamicbase -Wl,--high-entropy-va -Wl,--nxcompat -Wl,--tsaware' LD=/d/Prog/winlibs64_stage/custombuilt/share/binutils/bin/ld.exe
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 14.1.0 (MinGW-W64 x86_64-msvcrt-posix-seh, built by Brecht Sanders, r1)
```

**Comment by brechtsanders** [comment]
I would recommend you report this as an actual GCC bug at https://gcc.gnu.org/bugs/

LTO has seen multiple issues in Windows builds over the years and from time to time this pops up again :-(

**Comment by luisdallos** [comment]
> I would recommend you report this as an actual GCC bug at https://gcc.gnu.org/bugs/

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115312

Although I had to file the bug report at GCC Bugzilla with a [login](https://bugmenot.com/view/gcc.gnu.org) publicly available at BugMeNot as registrations are currently closed and I do not have an account there.

> LTO has seen multiple issues in Windows builds over the years and from time to time this pops up again :-(

Precompiled headers in Windows builds work fine in GCC 13. But this issue appeared somewhere after [`gcc-14-20231119`](/brechtsanders/winlibs_mingw/releases/tag/14.0.0-snapshot20231119posix-11.0.1-msvcrt-r1) snapshot as [`gcc-14-20231217`](/brechtsanders/winlibs_mingw/releases/tag/14.0.0-snapshot20231217posix-11.0.1-msvcrt-r1) snapshot is the first affected GCC 14 pre-release.

This ICE can be triggered too with GCC 14.1.0 releases from MSYS2 project (`MINGW32`, `MINGW64` and `UCRT64` MINGW environments tested).

And according to the [reply](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115312#c1) to my bug report, the ICE is not triggered on `x86-64/Linux`.

**Comment by brechtsanders** [comment]
I have commented out `gcc_assert (!the_parser);` (in file `gcc/cp/parser.cc`) which was mentioned in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115312 so you can check if this works around your issue.

I published this build here: https://github.com/brechtsanders/winlibs_mingw/releases/tag/14.1.0posix-18.1.7-12.0.0-ucrt-r2

Can you please test it?

Note: that if this resolves the issue, it's till up to the GCC team to resolve the core issue.

**Comment by luisdallos** [comment]
> I have commented out `gcc_assert (!the_parser);` (in file `gcc/cp/parser.cc`) which was mentioned in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115312 so you can check if this works around your issue.
> 
> I published this build here: https://github.com/brechtsanders/winlibs_mingw/releases/tag/14.1.0posix-18.1.7-12.0.0-ucrt-r2
> 
> Can you please test it?

Test done and it works.

```
abc@xyz MINGW64 ~
$ touch test.cpp test.h

abc@xyz MINGW64 ~
$ g++ test.h

abc@xyz MINGW64 ~
$ g++ -include test.h -fpch-preprocess -E test.cpp
# 0 "test.cpp"
# 0 "<built-in>"
# 0 "<command-line>"
#pragma GCC pch_preprocess "./test.h.gch"
# 1 "test.cpp"
```

Now `g++` matches with `gcc`, which unlike the former, no ICE is thrown when trying to preprocess a C source file with a PCH included via `-include` compiler option as no `gcc_assert (!the_parser);` statement is present at the beginning of `c_init_preprocess` (in file [`gcc/c/c-parser.cc`)](https://github.com/gcc-mirror/gcc/blob/releases/gcc-14.1.0/gcc/c/c-parser.cc#L26894).

```
abc@xyz MINGW64 ~
$ touch test.c test.h

abc@xyz MINGW64 ~
$ gcc test.h

abc@xyz MINGW64 ~
$ gcc -include test.h -fpch-preprocess -E test.c
# 0 "test.c"
# 0 "<built-in>"
# 0 "<command-line>"
#pragma GCC pch_preprocess "./test.h.gch"
# 1 "test.c"
```

**Comment by brechtsanders** [comment]
That's good news. Hopefully GCC will fix this in their code.

**Comment by brechtsanders** [comment]
They have just fixed it in their code (see: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115312) for future releases.

**Comment by Alcaro** [comment]
I think you meant to link https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115312
