### ISSUE TITLE
Winlibs x86_64 with Posix Threads does not support C11 threads

### ISSUE THREAD

**Issue by esok** [brechtsanders/winlibs_mingw#219]
I teach a C (not C++) course that requires that students use only standard C in their projects. It would be very nice to be able to use the threading API provided in the C11 standard. I have them use WinLibs MinGW (x86-64) with posix threads for my Windows users because the gcc (mingw) compiler gives better error messages than the Microsoft C compiler, and the MCF version of gdb does not work. However, WinLibs gcc compiler does not support the C11 thread library associated with "threads.h".  It seems it would be trivial to build support for threads.h on top of posix threads since posix threads are already part of the distribution. Indeed, I have identified at least two implementations of threads.h that do this exact thing: TinyCThread (https://tinycthread.github.io/) and c11threads (https://github.com/jtsiomb/c11threads/blob/master/c11threads.h). It would be really fantastic if WinLibs provided a working threads.h too.

**Comment by brechtsanders** [comment]
I'm very glad to hear good old C is still being tought to students.

So many libraries out there stick to POSIX threads. I don't see why you wouldn't teach your students to use that.

Unless your educational institution is really pushing towards Microsoft. Which would be a shame as C probably the most cross-platform compiled language there is.

About your suggestions: they both work build fine with MinGW-w64.

In fact `c11threads.h` from the [latest tarball release](https://github.com/jtsiomb/c11threads/releases/download/v1.0/c11threads-1.0.tar.gz) just relies on POSIX threads and works fine by just including the header and then adding linker flag `-pthread` (or `-lpthread`).

`tinycthread` works too, but as a library to be linked with. See my build recipe [here](https://raw.githubusercontent.com/brechtsanders/winlibs_recipes/main/recipes/tinycthread.winlib) for both static and shared library.

I'm really curious to find out which you will choose.

Finally: it's not my goal to include libraries in the build tools. For that I'm working on a separate package manager [here](https://github.com/brechtsanders/winlibs_tools).

**Comment by esok** [comment]
I want my students to stick to standard C precisely so they won't get pulled to Microsoft's ecosystem. I do not allow students to use windows.h or conio.h in their tasks. I've used pthreads and while it is de facto the standard for threading with C, it is not part of the C standard, while C11 threads are. I'm a bit confused by your statement about not including libraries in the build tools. It looks like you're already including pthreads with MinGW. Why not support C11 threads too, since the implementation is so trivial? Doing so would make it more standards-compliant and reduce friction. Ultimately it's your decision, and I will continue to encourage my students to use your distribution of MinGW, but I thought I'd push for standard C11 thread support.
