### ISSUE TITLE
mingw32-make can't produce 64bit code

### ISSUE THREAD

**Issue by LuanVSO** [brechtsanders/winlibs_mingw#22]
i am trying to compile a 64bit program using the included make tool, but it give me this error when i run it:
```console
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
mingw32-make: *** [Makefile:20: bin/calendario] Error 1
```

**Comment by brechtsanders** [comment]
Are you trying to build a 64-bit program with the 32-bit compiler?
The 2 compilers are separated in winlibs.com to avoid any mixing of the 2.
You need to download the 64-bit compiler to compile for win64.

**Comment by LuanVSO** [comment]
ok, turns out i downloaded the wrong file when i updated it, sorry for wasting your time
