### ISSUE TITLE
cmake in winlibs-i686-posix-dwarf-gcc-10.5.0-mingw-w64msvcrt-11.0.1-r1.7z is broken

### ISSUE THREAD

**Issue by Aerocatia** [brechtsanders/winlibs_mingw#220]
cmake does not run in this release obtained using [this link](https://github.com/brechtsanders/winlibs_mingw/releases/download/10.5.0-11.0.1-msvcrt-r1/winlibs-i686-posix-dwarf-gcc-10.5.0-mingw-w64msvcrt-11.0.1-r1.7z).

![image](https://github.com/brechtsanders/winlibs_mingw/assets/12814075/af2616f1-6125-466a-a1b4-8cd689f8bea7)

PS, you have some dead links/things in the wrong place on https://winlibs.com/
For example gcc 13.3.0 is in the snapshot section, and 10.5.0 has LLVM related links that do not exist.

Thank you.

**Comment by brechtsanders** [comment]
Thanks for reporting this.

I fixed the broken links on the site.

There is normally no need to still use old versions like GCC 10.

**Comment by Aerocatia** [comment]
Normally no but I have code that segfaults if built with any later GCC while builds made with a github action that happen to use GCC 10 work. gdb is not being helpful because it causes a crash in something related to my sound driver when I try to use it. you know, the usual fun.

**Comment by brechtsanders** [comment]
That can happen if you mix things that were not all built with the same compiler.

It's best to rebuild all your dependencies too when switching compilers.
