### ISSUE TITLE
Problem building perl-5.40.0 using gcc-14.1.0 (release 2, runtime 12.0.0)

### ISSUE THREAD

**Issue by sisyphus** [brechtsanders/winlibs_mingw#221]
This is an issue that's specific to runtime 12.0.0.
It doesn't arise with gcc-14.1.0 release 1, runtime 11.0.1.
Incidentally, these "r2" builds do not yet appear at http://winlibs.com. I don't know why that is.
The one that's producing this issue for me is:
https://github.com/brechtsanders/winlibs_mingw/releases/download/14.1.0posix-18.1.7-12.0.0-ucrt-r2/winlibs-x86_64-posix-seh-gcc-14.1.0-mingw-w64ucrt-12.0.0-r2.7z

During the build, everything goes fine until I get hammered with:
```
windres --use-temp-file --include-dir=. --include-dir=.. -O COFF -D INCLUDE_MANIFEST -i perlexe.rc -o .\perlexe.res
windres: bfd_set_arch_mach(aarch64): cause of error unknown
make: *** [GNUmakefile:811: .\perlexe.res] Error 1
```
I'm just wondering if anyone here has any hints as to where that <code>bfd_set_arch_mach(aarch64)</code> directive is coming from (and why it arises).
The string "bfd_set_arch_mach" does not appear anywhere in the perl source.

For reference, the actual perl bug report is at https://github.com/Perl/perl5/issues/22266.

AFTERTHOUGHT: In case it's relevant, I'm running Windows 11.

Cheers,
Rob

**Comment by brechtsanders** [comment]
Please use the GCC 14.1.0 r1 build until we figure out this issue.

For now we know it's related to the added platform support in binutils in this release.

**Comment by sisyphus** [comment]
Thanks @brechtsanders - now confirmed as not a perl bug

UPDATE: Ooops ... I meant to close the perl issue, not this one.
I'm happy for this to be re-opened if that's deemed desirable.

'NOTHER UPDATE: This issue has been resolved  in the revised "r2" files that have now been uploaded.
(This issue is now definitely closable.)
