### ISSUE TITLE
Threat Detected by BitDefender: ~/mingw64/bin/nvptx-arch.exe

### ISSUE THREAD

**Issue by CagesThrottleUs** [brechtsanders/winlibs_mingw#223]
Bitdefender declares the mentioned bin file as infected with Gen:Variant.Tedy.570998. Requesting a research and fix for the issue with the community here. 

Worth to note that File is actually quarantined by the BitDefender.

![image](https://github.com/brechtsanders/winlibs_mingw/assets/62324457/c355fe37-fe9c-4b1d-892f-8cc4e14d491a)

**Comment by CagesThrottleUs** [comment]
Also did a VirusTotal Scan as [here](https://www.virustotal.com/gui/file/3636c64847870b600f747c0c9dc1a23fc249c6c24ec9c3ad09ed0326c44a9977). Several good anti-virus shows Tedy as the popular type. 

You can probably check this [StackOverflow Question](https://stackoverflow.com/questions/75886428/fake-positive-bit-defender-problem-genvariant-tedy-304469)

**Comment by brechtsanders** [comment]
Since `nvptx-arch.exe` is also part of LLVM this issue is a duplicate for #199

**Comment by brechtsanders** [comment]
Thanks for the tip about the icon in the [StackOverflow Question](https://stackoverflow.com/questions/75886428/fake-positive-bit-defender-problem-genvariant-tedy-304469).

I just released binaries which now have icons on the LLVM `.exe` files.

Further followup in #199.
