### ISSUE TITLE
build Qt5.15.14 using x86_64-gcc-14.1.0-ucrt-r2

### ISSUE THREAD

**Issue by heatheric** [brechtsanders/winlibs_mingw#224]
before build,set env_var:
qt_src_path c:\qt5
mingw64_path c:\pkg\mingw64

according to qtwiki  https://wiki.qt.io/Building_Qt_5_from_Git
run configure.bat  to  generate a makefile
"..\qt5\configure.bat -prefix C:\qt_build -verbose -opensource -confirm-license -debug-and-release -optimize-debug -shared -platform win32-g++ -skip webengine -nomake tests -gui -Widgets -libpng -libjpeg"

cmd erorr info is below:
Bootstrapping qmake ...
/d/Prog/winlibs64ucrt_stage/mingw64/bin/x86_64-w64-mingw32-g++.exe -c -o main.o 
-DUNICODE -DMINGW_HAS_SECURE_API=1 -std=c++11 -ffunction-sections -g  
-IC:/qt5/qtbase/qmake 
-IC:/qt5/qtbase/qmake/librar/include/QtCore/5.15.14/QtCore 
-I../src/corelib/global 
-IC:/qt5/qtbase/mkspecs/win32-g++ 
-DQT_VERSION_STR=\"5.15.14\" 
-DQT_VERSION_MAJOR=5  
-DQT_VERSION_MINOR=15  
-DQT_VERSION_PATCH=14  
-DQT_BUILD_QMA
process_begin: 
CreateProcess(NULL, sh.exe -c "/d/Prog/winlibs64ucrt_stage/mingw64/bin/x86_64-w64-mingw32-g++.exe -c -o main.o -DUNICODE -DMINGW_HAS_SECURE_API=1 -std=c++11 -ffunction-sections -g -IC:/
qtbase/include/QtCore/5.15.14 -IC:/qt5/qtbase/include/QtCore/5.15.14/QtCore -I../src/corelib/global -IC:/qt5/qtbase/mkspecs/win32-g++ -DQT_VERSION_STR=\"5.15.14\" -DQT_VERSION_MAJOR=5 -DQT_VERSION_MIN
make (e=2): FileNotFoundError。
mingw32-make: *** [makefile:274: main.o] Error 2

since mingw64 path is "c:\pkg\mingw64", why cmd show "/d/Prog/winlibs64ucrt_stage/mingw64"

**Comment by brechtsanders** [comment]
Why are you running a `.bat` file from a the git bash shell?
Git/MSYS shell will typically make paths UNIX-compatible replacing driveletters like you are experiencing (`C:\` becomes `/C/`).

The advantage if that shell is that you can run the UNIX-style configure script from Qt.

Check out my [Qt5 recipe](https://github.com/brechtsanders/winlibs_recipes/blob/main/recipes/qt.winlib) to see how I do that.

But if possible I strongly recommend switching to Qt6, as it uses CMake for the configuration step. And if you combine that with [Ninja](https://ninja-build.org/) for building, the build will be a lot faster.
