### ISSUE TITLE
CppCheck said <iostream> is not found

### ISSUE THREAD

**Issue by ghost** [brechtsanders/winlibs_mingw#227]
The command I used:

```
cppcheck --language=c++ --enable=all --template=gcc --inline-suppr --disable=unusedFunction test.cpp
```

**Comment by brechtsanders** [comment]
It looks to me like cppcheck doesn't know where the include file is.

This makes sense if cppcheck doesn't know how `g++` will go look for include files, or even which `g++` you will use exactly.

In my test I had to add the include path, e.g. using `-ID:/Prog/winlibs-gcc13.2.0-posix-msvcrt-11.0.1/mingw64/include/c++/13.2.0`

**Comment by ghost** [comment]
Internet search suggested me to use `--suppress=missingIncludeSystem`. I have not yet tried, though.
