### ISSUE TITLE
cmake 3.28.6 is the last version supports Windows 7

### ISSUE THREAD

**Issue by ghost** [brechtsanders/winlibs_mingw#228]
cmake 3.29.3 included in winlibs will not run on Windows 7 because of missing of GetSystemTimePreciseAsFileTime in KERNEL32.DLL.

**Comment by brechtsanders** [comment]
Windows 7 is no longer supported by Microsoft. Why go to the trouble to still support it?

**Comment by Alcaro** [comment]
On the other hand, breaking it with no notice is arguably impolite. And [the releases](https://github.com/brechtsanders/winlibs_mingw/releases/tag/14.1.0posix-18.1.7-12.0.0-ucrt-r2) mention working on Windows 7 (in a roundabout way that actually means the output programs work on 7, but is easy to misread).

Perhaps you should add a policy for which host OSes winlibs supports. If you don't want to keep it up to date, you could use something like 'winlibs supports Windows versions still supported by Microsoft; older versions may work, but are not tested and may break permanently without prior notice; this is not a winlibs bug, don't report it, upgrade your OS (or install Linux and Wine)'.
