### ISSUE TITLE
Compilation with Ccache and mingw32-make doesn't work

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [brechtsanders/winlibs_mingw#229]
I'm trying to compile locally [Notepad++](https://github.com/notepad-plus-plus/notepad-plus-plus) by using WinLibs + Ccache + mingw32-make and get such error:
```
ccache g++ -DNDEBUG -I ../include -I ../src -I ../../boostregex --std=c++17 -Wpedantic -Wall -Wextra -O3 -DSCI_OWNREGEX -c ../src/AutoComplete.cxx -o ../../PowerEditor/gcc/bin.x86_64.build/_scintilla.build/AutoComplete.occache: error: No such file or directory
mingw32-make[1]: *** [makefile:74: ../../PowerEditor/gcc/bin.x86_64.build/_scintilla.build/AutoComplete.o] Error 1
mingw32-make[1]: *** Waiting for unfinished jobs....
```

The same code compiles without any problems by using Github Action and Msys2.
https://github.com/ArkadiuszMichalski/notepad-plus-plus/actions/runs/8859141894/job/24328608354
![image](https://github.com/brechtsanders/winlibs_mingw/assets/2730894/7d65207c-1a96-4d3c-bb22-393cd941a5f0)

I tried using the same version of Ccache and mingw32-make.exe as in Msys2, but it didn't help.

Can anyone confirm that also experiencing this problem?

Step to reproduce:
1. Download WinLibs and set system `Path` variable to `WinLibs/bin`.
2. Download Notepad++ repository.
3. In `Notepad++\PowerEditor\gcc` folder invoke `mingw32-make CXX="ccache g++"`.

**Comment by brechtsanders** [comment]
Are you sure this is not a duplicate of one of these?
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14902
- https://github.com/brechtsanders/winlibs_mingw/issues/183

**Comment by ArkadiuszMichalski** [comment]
I'm sure, this is another problem.

**Comment by ArkadiuszMichalski** [comment]
I checked it more precisely and determined that I was setting the `CCACHE_DIR` variable incorrectly (in combination with other commands it unnecessarily added a space at the end, I had to surround the whole thing with ""). Sorry for the confusion.
