### ISSUE TITLE
Please add MCF release for 14.2 + llvm 18.1.8. Currently only posix available

### ISSUE THREAD

**Issue by UsmanTariq2** [brechtsanders/winlibs_mingw#235]
Thanks

**Comment by brechtsanders** [comment]
I will get started on this build, but know that i's just GCC, as  MCF threads are not supported yet for LLVM.

**Comment by brechtsanders** [comment]
https://github.com/brechtsanders/winlibs_mingw/releases/tag/14.2.0mcf-12.0.0-ucrt-r1

**Comment by sisyphus** [comment]
My thanks to @brechtsanders, too.

**Comment by UsmanTariq2** [comment]
Awsome. Thanks for taking the time out
