### ISSUE TITLE
-lasan not found!

### ISSUE THREAD

**Issue by Shadoware** [brechtsanders/winlibs_mingw#236]
Is it possible to use address sanitizer with this compiler in c++?

Im receiving this error:
E:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lasan: No such file or directory
collect2.exe: error: ld returned 1 exit status

**Comment by brechtsanders** [comment]
The error you get is that it can't find the asan library because you specified `-lasan`.

But according to GCC documentation the correct GCC flag is `-fsanitize=address`.

Can you please check if that works for you?

**Comment by Shadoware** [comment]
Actually I specified -fsanitize=address, but the error message came like that.
Address sanitizer is working for you?

**Comment by brechtsanders** [comment]
Seems to be unsupported in GCC for MinGW-w64, see: https://www.mingw-w64.org/contribute/#thorough-status-report-for-sanitizers-asan-tsan-usan
