### ISSUE TITLE
Remove Cppcheck

### ISSUE THREAD

**Issue by ghost** [brechtsanders/winlibs_mingw#238]
This program is very useless. The w64devkit suite that has included it for a long time finally decided to get rid of it in version [2.0.0](https://github.com/skeeto/w64devkit/releases/tag/v2.0.0).

**Comment by brechtsanders** [comment]
It was requested in #191 and that's why it was added

**Comment by ghost** [comment]
But it's broken. The one requested it can't use it. And he has deleted his account.

**Comment by brechtsanders** [comment]
Because there were issues I switched from https://ctags.sourceforge.net/ to https://github.com/universal-ctags/ctags

Which one do you say is broken?

**Comment by ghost** [comment]
> Because there were issues I switched from https://ctags.sourceforge.net/ to https://github.com/universal-ctags/ctags
> 
> Which one do you say is broken?

I think we are talking about `cppcheck.exe`?

**Comment by brechtsanders** [comment]
My bad, I confuse them because the were requested to be added around the same time.

Are you sure `cppcheck` is broken? There was a new release exactly one week ago.

**Comment by ghost** [comment]
> Are you sure `cppcheck` is broken? There was a new release exactly one week ago.

The one requested it can't use it. The w64devkit suite which has included it for a long time dropped it. I have tested both the winlibs.com version and the w64devkit version. They all have problems finding standard library. See #227.
