### ISSUE TITLE
"Paused on exception" with pthreads function delcared, not used

### ISSUE THREAD

**Issue by Airstrike1** [brechtsanders/winlibs_mingw#24]
A simple pthread_create declared in header, **not** used in main causes:
"Paused on exception"
"ntdll.dll!ntdll!RtlRaiseStatus"
"ntdll.dll!ntdll!memset"
"ntdll.dll!ntdll!LdrInitializeThunk"

Worked with gcc 9.2 distro (https://nuwen.net/mingw.html)

**Comment by brechtsanders** [comment]
Can you post some code to reproduce this?

**Comment by brechtsanders** [comment]
No code provided to reproduce this.
Assuming this is caused my calling the wrong DLL (e.g. when a different distro is in the PATH).
Closing ticket. Feel free to reopen if you can provide a reproducible scenario.
