### ISSUE TITLE
Please add `cc.exe`

### ISSUE THREAD

**Issue by ghost** [brechtsanders/winlibs_mingw#240]
It's only a copy of `gcc.exe`, but it should better be there. Some build systems still hardcode `CC` and `CXX` to `cc` and `c++` respectively. I found that you already have `c++.exe`. It's better to just add `cc.exe` instead of having the users to set `CC` variable manually.

I'm using your GCC in MSYS2. I have the Cygwin GCC installed (because I sometimes need to test some POSIX programs). If there is no `cc.exe` and `CC` is not set to `gcc` manually, `/usr/bin/cc` which is the Cygwin GCC will be picked.

Note: Not only `cc.exe`, Cygwin GCC will also install `c89.exe`, `c99.exe`, and `c11.exe`. If you can please add them, too. Thank you.

**Comment by brechtsanders** [comment]
In my opinion `cc.exe` and the likes refer to non GCC compilers.

You should use build environments that point to specific build tools.

Certainly don't add specific build tools (like Cygwin) to the global system `PATH` if you can avoid it.

I would actually recommend using environment vaiables (or `make` arguments) `CC` and `CXX` to specifically point to the desired compiler (be it GCC or LLVM).

But I'm not going to add copies of the build tools just so your system wouldn't be confused.

**Comment by ghost** [comment]
> In my opinion `cc.exe` and the likes refer to non GCC compilers.

On popular systems like Linux and BSD, `cc` is actually just `gcc` or `clang`.

> You should use build environments that point to specific build tools.
> 
> Certainly don't add specific build tools (like Cygwin) to the global system `PATH` if you can avoid it.
> 
> I would actually recommend using environment vaiables (or `make` arguments) `CC` and `CXX` to specifically point to the desired compiler (be it GCC or LLVM).

Yes. I know how to use these environment variables. But as I said, most of the time people will expect everything to work out of the box because `cc` is actually just `gcc` or `clang` on modern systems. You only have to set `CC` manually if you want to cross compile. On MSYS2, there are both the Cygwin GCC and the MinGW-w64 GCC. It will lead to very confusing situation as no one will think a wrong GCC is picked to be the case. It will waste a significant amount of time only to debug.

> But I'm not going to add copies of the build tools just so your system wouldn't be confused.

Please reconsider. The llvm-mingw project does exactly so. The w64devkit project does, too.

**Comment by brechtsanders** [comment]
Which list of files do you propose to include exactly (and what they are a copy of)?

Also to make something like `c89.exe` work as expected it wouldn't be a copy but rather a seperate program calling `gcc.exe -std=c89`.

With llvm-mingw I have had issues with it's `gcc.exe` because then configure tools think it's GCC instead of LLVM/CLang which in some projects makes it call the compiler unsupported flags.

**Comment by ghost** [comment]
I think only `cc.exe` is needed. I don't know much about `c89.exe`, `c99.exe`, and `c11.exe`. All of these binaries have the same checksum as `gcc.exe` on llvm-mingw.

**Comment by ghost** [comment]
This is useful to have.

**Comment by brechtsanders** [comment]
I strongly believe it is important that build systems don't get confused about which build tools they are using.

If the compiler is called `gcc.exe` or `clang.exe` this is quite clear. But if `cc.exe` would be provided this may get confusing.
