### ISSUE TITLE
-static with clang++ gives errors about pthreads

### ISSUE THREAD

**Issue by pfmoore** [brechtsanders/winlibs_mingw#241]
Here's a simple reproducible example, using "GCC 14.2.0 (with POSIX threads) + LLVM/Clang/LLD/LLDB 18.1.8 + MinGW-w64 12.0.0 UCRT - release 1" (64-bit version).

hw.cpp:
```
#include <iostream>

int main() {
    std::cout << "Hello, world!" << std::endl;
    return 0;
}
```

Compile with `clang++ -o hw.exe .\hw.cpp` and everything works fine. `objdump` shows it links at runtime to `libstdc++-6.dll`.

However, if you try to build a statically linked executable, using `clang++ -o hw.exe -static .\hw.cpp` the linker thows a series of errors:

```
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(locale.o):(.text$__tcf_0+0x8): undefined reference to `pthread_mutex_destroy'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(locale.o):(.text$_ZNSt6locale5facet15_S_get_c_localeEv+0x13): undefined reference to `pthread_once'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(locale.o):(.text.unlikely._ZNSt6locale5_Impl16_M_install_cacheEPKNS_5facetEy+0x54): undefined reference to `pthread_mutex_unlock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(locale.o):(.text$_ZNSt6locale5_Impl16_M_install_cacheEPKNS_5facetEy+0x2d): undefined reference to `pthread_mutex_lock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(locale.o):(.text$_ZNSt6locale5_Impl16_M_install_cacheEPKNS_5facetEy+0x17b): undefined reference to `pthread_mutex_unlock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(locale.o):(.text$_ZNSt6locale5_Impl16_M_install_cacheEPKNS_5facetEy+0x1bc): undefined reference to `pthread_mutex_init'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(locale_init.o):(.text$__tcf_0+0xc): undefined reference to `pthread_mutex_destroy'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(locale_init.o):(.text$_ZN12_GLOBAL__N_116get_locale_mutexEv+0x48): undefined reference to `pthread_mutex_init'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(locale_init.o):(.text$_ZNSt6locale13_S_initializeEv+0x15): undefined reference to `pthread_once'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(locale_init.o):(.text$_ZNSt6locale7classicEv+0x15): undefined reference to `pthread_once'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(locale_init.o):(.text$_ZNSt6localeC2Ev+0x21): undefined reference to `pthread_once'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(locale_init.o):(.text$_ZNSt6localeC2Ev+0x52): undefined reference to `pthread_mutex_lock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(locale_init.o):(.text$_ZNSt6localeC2Ev+0x6f): undefined reference to `pthread_mutex_unlock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(locale_init.o):(.text.unlikely._ZNSt6locale6globalERKS_+0x16): undefined reference to `pthread_mutex_unlock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(locale_init.o):(.text$_ZNSt6locale6globalERKS_+0x1f): undefined reference to `pthread_once'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(locale_init.o):(.text$_ZNSt6locale6globalERKS_+0x41): undefined reference to `pthread_mutex_lock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(locale_init.o):(.text$_ZNSt6locale6globalERKS_+0xa9): undefined reference to `pthread_mutex_unlock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(eh_alloc.o):(.text$__tcf_0+0xc): undefined reference to `pthread_mutex_destroy'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(eh_alloc.o):(.text$_ZN12_GLOBAL__N_14pool4freeEPv.constprop.0+0x14): undefined reference to `pthread_mutex_lock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(eh_alloc.o):(.text$_ZN12_GLOBAL__N_14pool4freeEPv.constprop.0+0xbf): undefined reference to `pthread_mutex_unlock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(eh_alloc.o):(.text$_ZN12_GLOBAL__N_14pool8allocateEy.constprop.0+0x14): undefined reference to `pthread_mutex_lock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(eh_alloc.o):(.text$_ZN12_GLOBAL__N_14pool8allocateEy.constprop.0+0x99): undefined reference to `pthread_mutex_unlock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(eh_alloc.o):(.text.startup._GLOBAL__sub_I__ZN9__gnu_cxx9__freeresEv+0x2a): undefined reference to `pthread_mutex_init'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(guard.o):(.text.unlikely.__cxa_guard_acquire+0x3f): undefined reference to `pthread_mutex_unlock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(guard.o):(.text$__cxa_guard_acquire+0x45): undefined reference to `pthread_once'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(guard.o):(.text$__cxa_guard_acquire+0x51): undefined reference to `pthread_mutex_lock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(guard.o):(.text$__cxa_guard_acquire+0x7d): undefined reference to `pthread_once'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(guard.o):(.text$__cxa_guard_acquire+0x8f): undefined reference to `pthread_once'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(guard.o):(.text$__cxa_guard_acquire+0x9e): undefined reference to `pthread_cond_wait'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(guard.o):(.text$__cxa_guard_acquire+0xb7): undefined reference to `pthread_mutex_unlock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(guard.o):(.text$__cxa_guard_acquire+0xe2): undefined reference to `pthread_mutex_unlock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(guard.o):(.text$__cxa_guard_abort+0x17): undefined reference to `pthread_once'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(guard.o):(.text$__cxa_guard_abort+0x23): undefined reference to `pthread_mutex_lock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(guard.o):(.text$__cxa_guard_abort+0x42): undefined reference to `pthread_once'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(guard.o):(.text$__cxa_guard_abort+0x4e): undefined reference to `pthread_cond_broadcast'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(guard.o):(.text$__cxa_guard_abort+0x62): undefined reference to `pthread_mutex_unlock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(guard.o):(.text$__cxa_guard_release+0x17): undefined reference to `pthread_once'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(guard.o):(.text$__cxa_guard_release+0x23): undefined reference to `pthread_mutex_lock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(guard.o):(.text$__cxa_guard_release+0x45): undefined reference to `pthread_once'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(guard.o):(.text$__cxa_guard_release+0x51): undefined reference to `pthread_cond_broadcast'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib\libstdc++.a(guard.o):(.text$__cxa_guard_release+0x65): undefined reference to `pthread_mutex_unlock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib/gcc/x86_64-w64-mingw32/14.2.0\libgcc_eh.a(emutls.o): in function `__gthread_mutex_init_function':
R:/winlibs64ucrt_stage/gcc-14.2.0/build_mingw/x86_64-w64-mingw32/libgcc/./gthr-default.h:746:(.text+0x5e): undefined reference to `pthread_mutex_init'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib/gcc/x86_64-w64-mingw32/14.2.0\libgcc_eh.a(emutls.o): in function `__gthread_key_create':
R:/winlibs64ucrt_stage/gcc-14.2.0/build_mingw/x86_64-w64-mingw32/libgcc/./gthr-default.h:721:(.text+0x71): undefined reference to `pthread_key_create'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib/gcc/x86_64-w64-mingw32/14.2.0\libgcc_eh.a(emutls.o): in function `__gthread_getspecific':
R:/winlibs64ucrt_stage/gcc-14.2.0/build_mingw/x86_64-w64-mingw32/libgcc/./gthr-default.h:733:(.text+0xad): undefined reference to `pthread_getspecific'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib/gcc/x86_64-w64-mingw32/14.2.0\libgcc_eh.a(emutls.o): in function `__gthread_once':
R:/winlibs64ucrt_stage/gcc-14.2.0/build_mingw/x86_64-w64-mingw32/libgcc/./gthr-default.h:713:(.text+0xf7): undefined reference to `pthread_once'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib/gcc/x86_64-w64-mingw32/14.2.0\libgcc_eh.a(emutls.o): in function `__gthread_mutex_lock':
R:/winlibs64ucrt_stage/gcc-14.2.0/build_mingw/x86_64-w64-mingw32/libgcc/./gthr-default.h:762:(.text+0x106): undefined reference to `pthread_mutex_lock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib/gcc/x86_64-w64-mingw32/14.2.0\libgcc_eh.a(emutls.o): in function `__gthread_mutex_unlock':
R:/winlibs64ucrt_stage/gcc-14.2.0/build_mingw/x86_64-w64-mingw32/libgcc/./gthr-default.h:792:(.text+0x11b): undefined reference to `pthread_mutex_unlock'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/lib/gcc/x86_64-w64-mingw32/14.2.0\libgcc_eh.a(emutls.o): in function `__gthread_setspecific':
R:/winlibs64ucrt_stage/gcc-14.2.0/build_mingw/x86_64-w64-mingw32/libgcc/./gthr-default.h:739:(.text+0x157): undefined reference to `pthread_setspecific'
C:/Users/Gustav/scoop/apps/mingw-winlibs-llvm-ucrt/current/bin/ld: R:/winlibs64ucrt_stage/gcc-14.2.0/build_mingw/x86_64-w64-mingw32/libgcc/./gthr-default.h:739:(.text+0x220): undefined reference to `pthread_setspecific'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

This is particularly frustrating, as I have no need of threads. And it's worth noting that the non-static build did *not* link to `libwinpthread-1.dll`, so the compiler obviously recognises that there's no need for thread support.

**Comment by brechtsanders** [comment]
The winlibs attempt to build LLVM uses the GCC standard libraries in order to allow both toolkits to be used interchangeable. However this is probably not a good idea.

LLVM comes with its own standard libraries and I would really recommend using the builds from https://github.com/mstorsjo/llvm-mingw

**Comment by Alcaro** [comment]
If you recommend not using them, perhaps you should document them as such on winlibs.com.

And put the without-clang builds before with-clang.

**Comment by pfmoore** [comment]
Thanks. I was using this because it's really hard to find a good build of LLVM for Windows. The ones from the LLVM site use the MSVC standard C library, and broke horribly because I have a project that needs C++11, and the MSVC libs no longer support C++11. So I picked the winlibs build because I was already using it for gcc.

I'll look into the mstorsjo builds as an alternative, and switch to the without-clang builds from here.

**Comment by ghost** [comment]
> The winlibs attempt to build LLVM uses the GCC standard libraries in order to allow both toolkits to be used interchangeable. However this is probably not a good idea.
> 
> LLVM comes with its own standard libraries and I would really recommend using the builds from https://github.com/mstorsjo/llvm-mingw

Oof, unless I just missed it (and it's possible) it'd be really nice to have this stated up front on releases.

**Comment by ghost** [comment]
> The winlibs attempt to build LLVM uses the GCC standard libraries in order to allow both toolkits to be used interchangeable. However this is probably not a good idea.

Nope. Nothing wrong with this. The OP forgot to add `-pthread`. Adding `-pthread` and everything will be fine.

Update: `-lpthread` doesn't work, only `-pthread` will work.

**Comment by pfmoore** [comment]
Interesting. I can confirm that this is correct, but *why* do I need `-pthread`? My code doesn't use threads. so I assume this is needed because of something in the stdlib. Also, why doesn't `-static` tell the compiler to statically compile in the necessary thread support?

I'm not disputing the validity of the answer, I'm just trying to understand better what's going on here.

Also, I'll note that the resulting executable is over twice the size of the ones I get using the mstorsjo builds recommended by @brechtsanders above. Presumably that's because there's a bunch of (unnecessary?) thread support code being linked in?

**Comment by brechtsanders** [comment]
> Also, I'll note that the resulting executable is over twice the size of the ones I get using the mstorsjo builds recommended by @brechtsanders above. Presumably that's because there's a bunch of (unnecessary?) thread support code being linked in?

If you build with debugging information included that will take up some place. You can strip debugging information by either linking with the `-s` flag or running `strip` on the `.exe` (and `.dll`) files after they are built.

**Comment by pfmoore** [comment]
I know, but I built both cases with debugging, so unless I'm misunderstanding what the `strip` command does, that won't help the *relative* size difference. Presumably there's something else going on with that?

**Comment by brechtsanders** [comment]
Only way to figure that out is to analyze the `.exe` files.

For example using [Dependency Walker](https://www.dependencywalker.com/).

To eliminate difference in debugging data size I would recommend comparing stripped `.exe` files.

Especially look for differences in dependency `.dll` files.

**Comment by ghost** [comment]
I have compiled your sample code with both winlibs and llvm-mingw. The binary size of winlibs is almost twice. If you compare the size of libstdc++ DLL and libc++ DLL, you can see that it's also almost twice.

**Comment by pfmoore** [comment]
Interesting. So it's possibly the C++ standard library code that's the size difference. But as I'm doing a static build, surely only the functions I'm using will be linked in, and therefore the difference won't be as significant?

Ultimately, though, it looks like this is the reason for the size difference - and unless there are significant benefits to using `libstdc++` (and why would there be, they should both be implementations of the same C++ standard library) I feel like picking the smaller one is better.

I'd still like to know why a program that doesn't use threads needs to specify `-pthread` when linked statically (but not when linked dynamically). That feels weird to me.

**Comment by brechtsanders** [comment]
Just a small question: Did you link with `-static-libstdc++`?

Just to be sure one of your tests does't link to the shared libstdc++ ...

**Comment by pfmoore** [comment]
> Just a small question: Did you link with `-static-libstdc++`?

No. I wasn't even aware of this option. Should I have needed to?

To be clear, I'm not a professional C/C++ programmer. I've used C (and a little C++) on and off over the years, but not intensively. In this instance, I'm helping a friend by building an app he has written for him on Windows, where I want it to be completely self-contained (hence the static build) so that he can distribute it to people as a single file executable. I use the `-static` flag because that's the "obvious" way to get a static build, but beyond that if there's anything else I should be doing I'm probably not aware of it (and as I'm not a regular C/C++ programmer, I'm not even aware of where the best places are to ask for advice - hence the fact that I'm asking dumb questions here...)

> Just to be sure one of your tests does't link to the shared libstdc++

I did run `objdump -p <my exe> | grep DLL` (which is how I typically check what libraries an exe links to) and it showed nothing but system dlls (KERNEL32.dll and various ucrt DLLs).

**Comment by brechtsanders** [comment]
In my opnion to be able to distribute you don't necessary need to go through the trouble of a static build. A shared build can be distributed as long as all dependencies (and their dependencies and so on...) are also distributed (in the same folder as your `.exe`).

My [pedeps](https://github.com/brechtsanders/pedeps) project comes with a tool called `copypedeps` which has a `-r` flag to copy all dependencies recursively, which you can use for this purpose.

**Comment by pfmoore** [comment]
Understood, but in my experience, distributing common DLLs along with the app frequently results in *other* apps picking up my application's copy of a common DLL (because it's a CLI application, it's on `%PATH%` along with its DLLs), and then segfaulting because the versions differ in incompatible ways.

For this particular application and user base, distributing just a single exe is more convenient and safer.

**Comment by brechtsanders** [comment]
You should really avoid tinkering with the `PATH` environment variable on the system level, because is will mess things up, just like you mentioned.

Also avoid copying any `.dll` files in system folders for the same reason.

Instead copy all `.exe` and `.dll` files in the same folder and distribute your application like that. That way your `.exe` files will use the `.dll` file(s) you supplied (and not those elswhere on the system that happen to have the same name).

**Comment by pfmoore** [comment]
> Instead copy all .exe and .dll files in the same folder and distribute your application like that. 

That's what I was doing. But in order to make the application available as a command line executable, the `.exe` needs to be on `PATH` - which means that the DLLs in the same folder are also on `PATH`. A folder with the executable plus DLLs works for a GUI application, that gets run from a double click or a shortcut, but it can cause the problems I mentioned for command line programs (like gcc itself). There's a bunch of DLLs in mingw64\bin\*.dll, for example - if I put mingw64\bin on PATH (so that I can invoke gcc by name) those DLLs are visible to any other applications searching `PATH`. The winlibs documentation explicitly says to put the bin directory on your PATH.

But this is unrelated to the question I originally asked about `-static` and `-static-libstdc++`, so I'm happy to drop this side discussion if you are.

**Comment by brechtsanders** [comment]
The winlibs documentation does mention adding to the `PATH` for a specific shell session.
But certainly not to set it system-wide.

This is only to avoid the hassle of specifying the full path to tools `gcc.exe` every time they are called.

When using an IDE (like Code::Blocks) the full path is used every time.

This has the advantage of having multiple toolchains on the same system.

There is no difference between command line or GUI applications with regards to how they look for `.dll` files. If the file is found in the same folder as the `.exe` that one is used, of not it will search the locations listed in the `PATH` environment variable.

I'm glad your original question is resolved and so I will close this issue.
