### ISSUE TITLE
Can you make a fully static GCC distro?

### ISSUE THREAD

**Issue by ghost** [brechtsanders/winlibs_mingw#243]
Like this one:

https://github.com/mmozeiko/build-gcc-mingw/releases

This is the smallest and most compact GCC distro I have ever found. The ones provided by Equation.com and w64devkit are also fully static, but they are more bloated.

**Comment by brechtsanders** [comment]
What's the use of static?
It will have larger `.exe` files and less `.dll` files, but that doesn't mean it will load faster.

**Comment by brechtsanders** [comment]
Also, I think static GCC builds don't support plugins
