### ISSUE TITLE
How to set clang to use ld.lld by default?

### ISSUE THREAD

**Issue by ghost** [brechtsanders/winlibs_mingw#246]
It uses ld by default. I tried to pass `LDFLAGS="-fuse-ld=lld"` to `make` but it will tell the flag is unknown and stop the linking process altogether. This is only a hack btw. If there is a config I could change to have clang always uses ld.lld it's much better.

The linker is the only thing I want to set to use LLVM's. I'm happy with the rest of binutils. Please don't tell me to just use llvm-mingw. I don't want to do that. llvm-mingw will not provide me an all-in-one suite of tools like yours.

**Comment by chadchoi** [comment]
@brechtsanders Do you have any idea? Should `-fuse-ld=lld` be put in `CXXFLAGS` instead of `LDFLAGS`? `-fuse-ld=lld` is a switch of the compiler driver (`gcc.exe` or `clang.exe`) to select which linker to be used. `LDFLAGS` is for passing into the linker.

**Comment by ghost** [comment]
Since there is no` lld.exe`, only `ld.lld.exe`, so I changed it to `LDFLAGS="-fuse-ld=ld.lld"` because I think the linker name should match the binary name. It turned out to be the reason for the error I got. Only `LDFLAGS="-fuse-ld=lld"` is correct.
