### ISSUE TITLE
[Idea] ccls

### ISSUE THREAD

**Issue by ghost** [brechtsanders/winlibs_mingw#248]
Even no-one-uses tools like cppcheck is included. What about ccls? Will be way more useful. LLVM is there already. Not much bloat added I think. You will ask me how much value is added by ccls? Well, NetBeans still not yet support clangd.

**Comment by brechtsanders** [comment]
My focus is currently more on GCC than on LLVM.

Do I understand correctly ccls is mostly used by IDEs? If so I don't see why distributing it would be of added value, unless IDEs would automatically pick this up somehow...
