### ISSUE TITLE
How to add C regex.h to my install

### ISSUE THREAD

**Issue by yannou38** [brechtsanders/winlibs_mingw#249]
Hello ! 

I've been building a project using this toolchain, however the team responsible for it recently added regex.h (the C one, not C++), which is not present in the releases.

I've been searching high and low for a solution, but most of them boil down to "use other tools" (cygwin, msys2 ...), which would be quite inconvenient for me (notably on the CI side)

Do you have some insight about finding the regex lib and adding it to winlibs on my end ?

**Comment by Alcaro** [comment]
Are you sure standard C has a regex.h? Looks to me like it's a POSIX thing.

If it's so new I can't google it, it's probably not implemented yet in any compiler either. If it's still POSIX only, then you'll have to use another regex library. PCRE, maybe?

**Comment by yannou38** [comment]
I believe it's not standard, but may be posix. honestly i'm not very experienced in C and have troubles making sense of toolchains and libraries.

i'll try to take a look at PCRE and see how i can add it to my version of mingw

**Comment by yannou38** [comment]
PCRE doesn't seem to give regex.h (oh, and i believe i was unclear, but i'm only building that project have have no input on used libs). I may be forced to switch toolchain, which is a shame.

Thank you for the quick reply, however.

**Comment by brechtsanders** [comment]
The winlibs build tools distribution is just the build tools, I consider regex.h to be part of a separate library.

Libraries are built separately (until the [winlibs build tools](https://github.com/brechtsanders/winlibs_tools) find a place to host all the binaries and all binaries are checked against their license to see if binary distribution is even allowed).

I have a working build recipe for pcre here: https://github.com/brechtsanders/winlibs_recipes/blob/main/recipes/pcre.winlib
