### ISSUE TITLE
Typo in http://winlibs.com/philosophy.html

### ISSUE THREAD

**Issue by michael-o** [brechtsanders/winlibs_mingw#26]
It says:

> The winlibs.com ecosystem does have a Windows installer, so it doesn't need administrator rights

I guess a *not* is missing there.

**Comment by Eric-01** [comment]
Also I've found another issue. Your website has the following sentence:
> MinGW-w64 - Short for "Minimalist GNU for Windows", generates native Windows binaries, but doesn't support newer Windows features and doesn't support Windows 64-bit.

While the official one contains the following information:
> It has forked it in 2007 in order to provide support for 64 bits and new APIs.

**Comment by Eric-01** [comment]
Also I've found another issue. Your website has the following sentence:
> MinGW-w64 - Short for "Minimalist GNU for Windows", generates native Windows binaries, but doesn't support newer Windows features and doesn't support Windows 64-bit.

While the official one contains the following information:
> Mingw-w64 is an advancement of the original mingw.org project, created to support the GCC compiler on Windows systems. It has forked it in 2007 in order to provide support for 64 bits and new APIs.

**Comment by Eric-01** [comment]
Also I've found another issue. Your website has the following sentence:
> MinGW-w64 - Short for "Minimalist GNU for Windows", generates native Windows binaries, but doesn't support newer Windows features and doesn't support Windows 64-bit.

While the official one contains the following information:
> Mingw-w64 is an advancement of the original mingw.org project, created to support the GCC compiler on Windows systems. It has forked it in 2007 in order to provide support for 64 bits and new APIs.

**Comment by brechtsanders** [comment]
Fixed
