### ISSUE TITLE
clang and clang++ won't start: error 0xc0000142

### ISSUE THREAD

**Issue by zufuliu** [brechtsanders/winlibs_mingw#28]
tested on Win10 2004 (10.0.19041.508) AMD x64 system for both winlibs-x86_64-posix-seh-gcc-10.2.0-llvm-10.0.1-mingw-w64-8.0.0-r1.7z and winlibs-i686-posix-dwarf-gcc-10.2.0-llvm-10.0.1-mingw-w64-8.0.0-r1.7z

**Comment by brechtsanders** [comment]
Can you try again with the latest release https://github.com/brechtsanders/winlibs_mingw/releases/tag/10.2.0-11.0.0-9.0.0-r5 ?
Pleas let me know if it's okay now.

**Comment by zufuliu** [comment]
Thanks, they starts now.
