### ISSUE TITLE
<typeinfo> has an issue with clang when -static-libstdc++

### ISSUE THREAD

**Issue by denchat** [brechtsanders/winlibs_mingw#29]
issue:  operator== symbol get duplicated on linking phase when compile with `-static-libstdc++` on clang target `x86_64-w64-windows-gnu`

workaround:  by conditioning `__clang__` with always inline attribute as seen in

Issues when building with clang (duplicate libstdc++.a symbols)
https://github.com/msys2/MINGW-packages/issues/1677#issuecomment-242980310

**Comment by Keithcat1** [comment]
Do you mean errors like this:
C:\mingw64\lib\libstdc++.a(bad_alloc.o): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size                                               
I get this when trying to build third-party software. Anything I can do?

**Comment by visglz** [comment]
I also get a lot of these warnings with "-static" (list not complete):

```
C:/.../mingw64/lib\libstdc++.a(eh_alloc.o): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
C:/.../mingw64/lib\libstdc++.a(eh_exception.o): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has 
different size
C:/.../mingw64/lib\libstdc++.a(eh_personality.o): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
```

Is there any news on this?

**Comment by fwsGonzo** [comment]
I think I solved it by compiling with GCC. It might have been an incompatibility between different run-times and pre-built libraries. If you build everything yourself you might still be able to use Clang. This was very long ago, so I don't really remember the details.

**Comment by brechtsanders** [comment]
True, you should never mix GCC and CLang in the same build...

**Comment by visglz** [comment]
@brechtsanders I am not mixing clang and gcc in the same build. What I am trying to do is to build statically (-static) with clang.  Is this a supported use case? Or are there issues as winlibs_mingw including libstdc++ is build using gcc?

The issue can be reproduced with `winlibs-x86_64-posix-seh-gcc-13.2.0-llvm-17.0.6-mingw-w64ucrt-11.0.1-r5` and [googletest](https://github.com/google/googletest) v1.14.0 like this:

```shell
cmake -D CMAKE_PREFIX_PATH="D:/download/2024-W08/winlibs-x86_64-posix-seh-gcc-13.2.0-llvm-17.0.6-mingw-w64ucrt-11.0.1-r5/mingw64" -DCMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++ -Dgtest_build_tests=ON  -DCMAKE_CXX_FLAGS_INIT="-pthread -static" -G Ninja -B build
```

```shell
cmake --build build -j --verbose
```

There are lot of "duplicate section ... has different size" messages:
```
D:/download/2024-W08/winlibs-x86_64-posix-seh-gcc-13.2.0-llvm-17.0.6-mingw-w64ucrt-11.0.1-r5/mingw64/lib\libstdc++.a(eh_alloc.o): duplicate section `.rdata$_ZTSSt9exception[_ZTSSt9exception]' has different size
```

However I think this does not lead to an error, but the following does:

```
D:/download/2024-W08/winlibs-x86_64-posix-seh-gcc-13.2.0-llvm-17.0.6-mingw-w64ucrt-11.0.1-r5/mingw64/bin/ld: D:/download/2024-W08/winlibs-x86_64-posix-seh-gcc-13.2.0-llvm-17.0.6-mingw-w64ucrt-11.0.1-r5/mingw64/lib\libstdc++.a(tinfo.o):(.text$_ZNKSt9type_infoeqERKS_+0x0): multiple definition of `std::type_info::operator==(std::type_info const&) const'; googletest/CMakeFiles/googletest-printers-test.dir/test/googletest-printers-test.cc.obj:googletest-printers-test.cc:(.text$_ZNKSt9type_infoeqERKS_[_ZNKSt9type_infoeqERKS_]+0x0): first defined here
```

**Comment by fwsGonzo** [comment]
I suspect you are not just building statically with Clang. There's probably (static) libraries you are not aware of being pulled in, which are built by GCC. I believe all MinGW libraries are built by GCC.

Building a fully static program that only depends on code you have built yourself is rare to see, these days. Although it does happen.

**Comment by visglz** [comment]
@fwsGonzo Thats my suspicion too: That the mixing of clang build static libraries (from gtest) and gcc build static libraries  (from stdlib) happens non-intentionally. However this would mean that in general "-static" is just not supported with clang using "winlibs_mingw". Just wanted to make sure that I understood it correctly. The reason why I like to build with "-static" is to be independend from the installation directory of the toolchain (where otherwise the stdlib would be).

In the meanwhile I tried out another mingw llvm project: https://github.com/mstorsjo/llvm-mingw. There everything is build with clang and at least the googletest test can be build and run sucessfully with "-static".
