### ISSUE TITLE
Can you please share the source with built instructions, I would love to compile it for Windows on Arm (Aarch64 target)

### ISSUE THREAD

**Issue by janftacnik** [brechtsanders/winlibs_mingw#30]
Hi Brecht,

you are doing great job with these releases. For Windows on ARM there are already 2 very good binary releases of LLVM compilers and tools, but none includes Fortran. I despreately need Fortran on WOA and I have got some experience building those two LLVM toolchains (they are https://github.com/mstorsjo/llvm-mingw/releases has also Windows on arm version, but unfortunately without Fortran; second one is described in the article https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/native-clang-for-windows-on-arm and works nicely - also without Fortran). I have never tried to add Fortran to those releases, but your releases are strictly for Windows and that is why it should be fairly easy to compile it on Windows on ARM - of course using one of those releases for compilation). Would you mind sharing your build chain or should I try to add fortran from your sources to those releases that have omitted it ? 
Thank you in advance for any answer, my email is jan.ftacnik@oki.cz, I am from Prague.

**Comment by Scr3amer** [comment]
Hello there !

I am also interested in learning how to build toolchains on windows. It is always a nightmare of configuration x).

Thanks for any explanation provided.
And thank you for providing these nice bundles. Saved me a lot of time with the missing headers from the official Clang download.

Scr3am

**Comment by brechtsanders** [comment]
Sorry for the late reply.
My build scripts are native compilations on Windows (x86 and x86_64, not IA64 is I don't have such a system).
What you need is a cross-compiler.
Also, I build every single dependance from scratch to get a solid base for production-quality builds.
I have started looking into how to cross-compile for ARM64 (triplet: aarch64-w64-mingw32) but have so far been unsuccessful.
My cross-compilation experiments did lead me to build nvptx (nVidia GPU) offloading support in GCC, but that uses newlib. The challenge for WOA will be that MinGW-w64 needs to be completely ready for this platform.

**Comment by Scr3amer** [comment]
No worries for the reply. Better later than never. Look at me :p, 2 months later.

Ok so you basically start a Msys2 Mingw64 shell and configure/make the compilers ?

Maybe you can put a text file on this github with the commands and options you write in the Msys shell _verbatim_ to configure and build the compiler packages. It is a wealth of information to investigate issues.

By the way is it possible to build MinGW with Visual C++ ?

I know that clang can and that gcc cannot (because according to gcc website its source code uses gcc specific features) but I can't find any information regarding MinGW.

**Comment by Scr3amer** [comment]
I had in mind the use case of someone who doesn't have / want Msys and wanted to build a Clang-mingw64 toolchain from Visual Studio.

But even in that case you are screwed because you can't run configure in cmd.

**Comment by brechtsanders** [comment]
@Scr3amer That is not my focus. I am building the winlibs ecosystem with the goal to totally not need MSVC and to completely avoid any mix between different compilers, as such a pure environment has a lot less issues.
(You can still use the winlibs standalone compiler from Visual Studio Code.)

About the Windows on ARM topic: I have started a few attempts, but was not successful yet in building MinGW-w64 GCC for this platform.

**Comment by xtemp09** [comment]
@brechtsanders
So, can you share build instructions?

I have compiled LLVM a couple of times, but the output binaries are huge. clang is 90 MB, llvm-ar is 12 Mb. The files from  toolchains downloaded from github are much smaller.

Though, I set them to depend on libc++ instead of libgcc, compiler-rt instead of libgcc_s, and they use native win32 threads instead of pthreads. libc++abi is linked to libc++ statically. clang uses the new pass manager, compiler-rt, libc++ by default.

**Comment by brechtsanders** [comment]
I build LLVM roughly as follows in MSYS2 shell using https://winlibs.com/ MinGW-w64 GCC as compiler:
```bash
cmake.exe -Wno-dev -GNinja -DCMAKE_INSTALL_PREFIX:PATH=$INSTALLPREFIX/share/llvm -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_SHARED_LIBS:BOOL=OFF -DLLVM_LINK_LLVM_DYLIB:BOOL=ON -DLLVM_BUILD_STATIC=ON -DLIBCLANG_BUILD_STATIC:BOOL=ON -DLLVM_LINK_LLVM_DYLIB:BOOL=OFF -DDCLANG_LINK_CLANG_DYLIB:BOOL=ON -DLLVM_HOST_TRIPLE:STRING=$RUNPLATFORM -DLLVM_TARGETS_TO_BUILD:STRING=all -DCLANG_VENDOR:STRING="(built by Brecht Sanders)" -DLLVM_ENABLE_PROJECTS:STRING="clang;clang-tools-extra;compiler-rt;lld;lldb;libclc" -DLLVM_EXPORT_SYMBOLS_FOR_PLUGINS:BOOL=OFF -DLLVM_ENABLE_THREADS:BOOL=ON -DCLANG_BUILD_TOOLS:BOOL=ON -DCLANG_DEFAULT_RTLIB:STRING=libgcc -DCLANG_DEFAULT_CXX_STDLIB:STRING=libstdc++ -DCLANG_DEFAULT_OPENMP_RUNTIME:STRING=libgomp -DCLANG_DEFAULT_UNWINDLIB:STRING=libgcc -DCLANG_ENABLE_PROTO_FUZZER:BOOL=OFF -DCLANG_ENABLE_STATIC_ANALYZER:BOOL=ON -DLLDB_ENABLE_LIBXML2:STRING=ON -DLLDB_ENABLE_LUA:STRING=ON -DLLDB_ENABLE_LZMA:STRING=ON -DLLVM_ENABLE_EH:BOOL=$(if ( echo $RUNPLATFORM | grep -q x86_64 ); then echo "ON"; else echo "OFF"; fi) -DLLVM_ENABLE_RTTI:BOOL=ON -DLLVM_ENABLE_MODULES:BOOL=OFF -DLLVM_ENABLE_ASSERTIONS:BOOL=OFF -DLLVM_ENABLE_FFI:BOOL=ON -DLLVM_OPTIMIZED_TABLEGEN:BOOL=ON -DLLVM_ENABLE_LIBXML2:STRING=ON -DLLVM_ENABLE_THREADS:BOOL=ON -DLLVM_ENABLE_UNWIND_TABLES:BOOL=ON -DLLVM_ENABLE_Z3_SOLVER:BOOL=ON -DLLVM_INCLUDE_TOOLS:BOOL=ON -DLLVM_INCLUDE_UTILS:BOOL=ON -DLLVM_INSTALL_UTILS:BOOL=ON -DLLVM_ENABLE_LIBEDIT:BOOL=OFF -DLLDB_ENABLE_LIBEDIT:STRING=OFF -DLLDB_ENABLE_CURSES:BOOL=OFF -DLLDB_ENABLE_LIBXML2:BOOL=ON -DLLDB_ENABLE_LUA:BOOL=ON -DLLDB_ENABLE_LZMA:BOOL=ON -DLLDB_ENABLE_PYTHON:BOOL=OFF -DPython3_EXECUTABLE:PATH=$PYDIR/python.exe -DLLVM_INCLUDE_DOCS:BOOL=OFF -DCLANG_INCLUDE_TESTS:BOOL=OFF -DCOMPILER_RT_INCLUDE_TESTS:BOOL=OFF -DLLDB_INCLUDE_TESTS:BOOL=OFF -DLLVM_INCLUDE_GO_TESTS:BOOL=OFF -DLLVM_INCLUDE_TESTS:BOOL=OFF -DLLVM_TOOL_LLVM_C_TEST_BUILD:BOOL=OFF -DLLVM_INCLUDE_EXAMPLES:BOOL=OFF -DLLVM_BUILD_BENCHMARKS:BOOL=OFF -DLLVM_BUILD_TESTS:BOOL=OFF -DBUILD_CLANG_FORMAT_VS_PLUGIN:BOOL=OFF -DCLANG_PLUGIN_SUPPORT:BOOL=ON -DCLANG_ENABLE_CLANGD:BOOL=ON -DCLANG_TOOL_APINOTES_TEST_BUILD:BOOL=OFF -DCLANG_TOOL_ARCMT_TEST_BUILD:BOOL=OFF -DCLANG_TOOL_CLANG_IMPORT_TEST_BUILD:BOOL=OFF -DCLANG_TOOL_C_ARCMT_TEST_BUILD:BOOL=OFF -DCLANG_TOOL_C_INDEX_TEST_BUILD:BOOL=OFF -DCLANG_INCLUDE_DOCS:BOOL=OFF -DCLANG_BUILD_EXAMPLES:BOOL=OFF -DLLD_BUILD_TOOLS:BOOL=ON -DLLDB_TOOL_LLDB_SERVER_BUILD:BOOL=OFF -DLLDB_TOOL_LLDB_VSCODE_BUILD:BOOL=OFF -DLLDB_DISABLE_PYTHON:BOOL=ON -Sllvm -Bbuild_static &&
cmake.exe -Wno-dev -GNinja -DCMAKE_INSTALL_PREFIX:PATH=$INSTALLPREFIX/share/llvm -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_SHARED_LIBS:BOOL=ON -DLLVM_BUILD_STATIC=OFF -DLIBCLANG_BUILD_STATIC:BOOL=OFF -DLLVM_LINK_LLVM_DYLIB:BOOL=OFF -DDCLANG_LINK_CLANG_DYLIB:BOOL=ON -DLLVM_HOST_TRIPLE:STRING=$RUNPLATFORM -DLLVM_TARGETS_TO_BUILD:STRING=all -DCLANG_VENDOR:STRING="(built by Brecht Sanders)" -DLLVM_ENABLE_PROJECTS:STRING="clang;clang-tools-extra;compiler-rt;lld;lldb;libclc" -DLLVM_EXPORT_SYMBOLS_FOR_PLUGINS:BOOL=OFF -DLLVM_ENABLE_THREADS:BOOL=ON -DCLANG_BUILD_TOOLS:BOOL=ON -DCLANG_DEFAULT_RTLIB:STRING=libgcc -DCLANG_DEFAULT_CXX_STDLIB:STRING=libstdc++ -DCLANG_DEFAULT_OPENMP_RUNTIME:STRING=libgomp -DCLANG_DEFAULT_UNWINDLIB:STRING=libgcc -DCLANG_ENABLE_PROTO_FUZZER:BOOL=OFF -DCLANG_ENABLE_STATIC_ANALYZER:BOOL=ON -DLLDB_ENABLE_LIBXML2:STRING=ON -DLLDB_ENABLE_LUA:STRING=ON -DLLDB_ENABLE_LZMA:STRING=ON -DLLVM_ENABLE_EH:BOOL=$(if ( echo $RUNPLATFORM | grep -q x86_64 ); then echo "ON"; else echo "OFF"; fi) -DLLVM_ENABLE_RTTI:BOOL=ON -DLLVM_ENABLE_MODULES:BOOL=OFF -DLLVM_ENABLE_ASSERTIONS:BOOL=OFF -DLLVM_ENABLE_FFI:BOOL=ON -DLLVM_OPTIMIZED_TABLEGEN:BOOL=ON -DLLVM_ENABLE_LIBXML2:STRING=ON -DLLVM_ENABLE_THREADS:BOOL=ON -DLLVM_ENABLE_UNWIND_TABLES:BOOL=ON -DLLVM_ENABLE_Z3_SOLVER:BOOL=ON -DLLVM_INCLUDE_TOOLS:BOOL=ON -DLLVM_INCLUDE_UTILS:BOOL=ON -DLLVM_INSTALL_UTILS:BOOL=ON -DLLVM_ENABLE_LIBEDIT:BOOL=OFF -DLLDB_ENABLE_LIBEDIT:STRING=OFF -DLLDB_ENABLE_CURSES:BOOL=OFF -DLLDB_ENABLE_LIBXML2:BOOL=ON -DLLDB_ENABLE_LUA:BOOL=ON -DLLDB_ENABLE_LZMA:BOOL=ON -DLLDB_ENABLE_PYTHON:BOOL=OFF -DPython3_EXECUTABLE:PATH=$PYDIR/python.exe -DLLVM_INCLUDE_DOCS:BOOL=OFF -DCLANG_INCLUDE_TESTS:BOOL=OFF -DCOMPILER_RT_INCLUDE_TESTS:BOOL=OFF -DLLDB_INCLUDE_TESTS:BOOL=OFF -DLLVM_INCLUDE_GO_TESTS:BOOL=OFF -DLLVM_INCLUDE_TESTS:BOOL=OFF -DLLVM_TOOL_LLVM_C_TEST_BUILD:BOOL=OFF -DLLVM_INCLUDE_EXAMPLES:BOOL=OFF -DLLVM_BUILD_BENCHMARKS:BOOL=OFF -DLLVM_BUILD_TESTS:BOOL=OFF -DBUILD_CLANG_FORMAT_VS_PLUGIN:BOOL=OFF -DCLANG_PLUGIN_SUPPORT:BOOL=ON -DCLANG_ENABLE_CLANGD:BOOL=ON -DCLANG_TOOL_APINOTES_TEST_BUILD:BOOL=OFF -DCLANG_TOOL_ARCMT_TEST_BUILD:BOOL=OFF -DCLANG_TOOL_CLANG_IMPORT_TEST_BUILD:BOOL=OFF -DCLANG_TOOL_C_ARCMT_TEST_BUILD:BOOL=OFF -DCLANG_TOOL_C_INDEX_TEST_BUILD:BOOL=OFF -DCLANG_INCLUDE_DOCS:BOOL=OFF -DCLANG_BUILD_EXAMPLES:BOOL=OFF -DLLD_BUILD_TOOLS:BOOL=ON -DLLDB_TOOL_LLDB_SERVER_BUILD:BOOL=OFF -DLLDB_TOOL_LLDB_VSCODE_BUILD:BOOL=OFF -DLLDB_DISABLE_PYTHON:BOOL=ON -Sllvm -Bbuild_shared &&
ninja -Cbuild_static install/strip &&
ninja -Cbuild_shared install/strip &&
echo SUCCESS
```
Note that I have build all the prerequisites from the source in the same environment.
The above builds both static and shared libraries, but the `.exe` files use the shared libraries.
Standard libraries from MinGW-w64 GCC are used to ensure maximum compatibility.

**Comment by xtemp09** [comment]
Thanks, I really appreciate it.

Why do you set LLDB_DISABLE_PYTHON=ON and why do you not build libopenmp? I know that libopenmp requires assembler, but it's just an MSVC tool of 590 kB.

**Comment by brechtsanders** [comment]
I try to build everything from source and unfortunately I haven't been able to compile Python from source yet.

Whatever I do, none of my builds depend on MSVC. If I need an assembler I will go for an open source assembler.

The focus of the winlibs build is on GCC, which comes which libgomp. I haven't yet figured out if this conflicts with openmp.

**Comment by brechtsanders** [comment]
I see `-DCLANG_DEFAULT_OPENMP_RUNTIME:STRING=libgomp` was in there to use GCC's libgomp.
So you're right, I didn't build  openmp explicitly.
Maybe it will build with jwasm.

**Comment by xtemp09** [comment]
Why do you use `BUILD_SHARED_LIBS`? I found [this](https://llvm.org/docs/BuildingADistribution.html#shared-libs).

**Comment by brechtsanders** [comment]
There were complaints the static build was so big, so I switched to shared builds.
In retrospect this may not have been the best choice.

But as my main focus is on GCC I haven't taken the time yet on how to best build LLVM.

Right now I build each GCC release with itself, and I add LLVM to also build with this GCC.
Maybe LLVM would work better if it is also built with itself, but I haven't tried that yet.

**Comment by Keithcat1** [comment]
@brechtsanders See #68 where I found several ways to make the LLVM builds much smaller without reducing their performance. [Building an LLVM distribution](https://llvm.org/docs/BuildingADistribution.html) states:

Warning
One very important note: Distributions should never be built using the BUILD_SHARED_LIBS CMake option. That option exists for optimizing developer workflow only. Due to design and implementation decisions, LLVM relies on global data which can end up being duplicated across shared libraries resulting in bugs. As such this is not a safe way to distribute LLVM or LLVM-based tools.
Also, I noticed that the lates build of LLVM on winlobs.com regressed to using BUILD_SHARED_LIBS.

**Comment by brechtsanders** [comment]
Thanks for all your tips. I am trying to put some time into building LLVM/Clang, and maybe even do it as a separate distribution instead of together with GCC.

**Comment by Keithcat1** [comment]
I don't think building it as a separate distribution makes much sense,
we already have LLVM MinGW for that.
I also recently discovered that LLVM_LINK_LLVM_DYLIB works on windows,
even though it shouldn't or maybe the docs are just outdated. This
option is basically what we've been looking for and will put all of
LLVM in its own dynamic library and then Clang and LLD ETC just link
to that and save a ton of space.

**Comment by brechtsanders** [comment]
I'm closing this ticket now, because all build recipes used are now published at: https://github.com/brechtsanders/winlibs_recipes

I too would like to target Windows on ARM64 (MinGW-w64 for aarch64). It would really help if I could get hold of a [Windows on ARM developer kit](https://developer.qualcomm.com/hardware/windows-on-snapdragon/snapdragon-developer-kit), but unfortunately Microsoft won't ship outside US (I'm in Europe)...
