### ISSUE TITLE
[LLDB] TUI not reacting to actions

### ISSUE THREAD

**Issue by Scr3amer** [brechtsanders/winlibs_mingw#31]
Hello,

I was trying to use the embedded textual GUI with ncurses of lldb but when I select an option like creating a target nothing happens.
Am I missing something ?

I tried the latest release and the GCC9.3 one.

PS: I don't use MSys or anything else. Just raw lldb in cmd.

Win 10 v2004
Cheers,
Scr3am

**Comment by brechtsanders** [comment]
Fixed in https://github.com/brechtsanders/winlibs_mingw/releases/tag/10.2.0-11.0.0-9.0.0-r5
