### ISSUE TITLE
[GDB] Warning: Couldn't determine a path for the index cache directory

### ISSUE THREAD

**Issue by ElAlderson** [brechtsanders/winlibs_mingw#32]
Hi @brechtsanders ! Thank you for bringing the latest GNU compilers to Windows as a standalone package.

The FORTRAN and C compilers seem to run fine but while running GDB, I'm greeted with the following message:
```
C:\>gdb
c:\program files\mingw64\bin\gdb.exe: warning: Couldn't determine a path for the index cache directory.
GNU gdb (GDB for MinGW-W64 x86_64, built by Brecht Sanders) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb)
```

The warning that I'm shown doesn't pose any problems (at least none that I'm aware of) but is a nuisance nonetheless. Before using Winlibs, I used MinGW-w64 version of GDB where such warnings were non-existent. Upon closer inspection, I've noticed a few differences in the contents of MinGW-w64 folder and Winlibs folder. But I'm not sure where the source of the warning is. It would be great if you can shed some light on this whether this is a generic error that I'm facing or there's a problem with my GNU setup.

**Comment by brechtsanders** [comment]
This seems to be a known issue.
When launched from MSYS shell the warning is not shown.
The reason is because there the `HOME` environment variable is set.
If you do this before running `gdb` the warning is no longer shown:
```
SET HOME=%USERPROFILE%
```

**Comment by ElAlderson** [comment]
Thank you for the fix. But there's a small problem. It works in CMD but doesn't work in Windows Powershell. Is the command different for Powershell ?
```
PS C:\> SET HOME=%USERPROFILE%
PS C:\> gdb
c:\program files\mingw64\bin\gdb.exe: warning: Couldn't determine a path for the index cache directory.
GNU gdb (GDB for MinGW-W64 x86_64, built by Brecht Sanders) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb)
```

**Comment by brechtsanders** [comment]
Yes, in PowerShell use: `$Env:HOME = $Env:USERPROFILE`

**Comment by ElAlderson** [comment]
Works, thank you!
