### ISSUE TITLE
[Request] Archive checksums on winlibs website

### ISSUE THREAD

**Issue by SteelShot** [brechtsanders/winlibs_mingw#33]
It would be really useful if release archives urls were acompanied with checksum urls. It good practice for security sake and really useful for automation.

something like this maybe?
![image](https://user-images.githubusercontent.com/5291010/100120502-e6998380-2e6f-11eb-86f5-f2dbcb767699.png)

**Comment by brechtsanders** [comment]
Thanks for the suggestion.
The winlibs.com site should stay simple for the novice user (who probably doesn't have a clue what a checksum is), but I will add sha256 and sha512 checksums for every new release on the github releases page https://github.com/brechtsanders/winlibs_mingw/releases/ and I have already added them for the latest release at https://github.com/brechtsanders/winlibs_mingw/releases/tag/10.2.0-11.0.0-9.0.0-r3

**Comment by kryzet** [comment]
Automatic checksum verification for these files is not working because they don't follow the standard format:

```
checksum[_][_]filename
...
<or>
checksum[_]*filename
```

`[_]` denotes a space character.

**Comment by brechtsanders** [comment]
Okay, I fixed my build script to make sure there are 2 spaces.

**Comment by brechtsanders** [comment]
The just released 16.1.0 builds now have correct checjsuls (with 2 spaces)
