### ISSUE TITLE
GitHub release tag confusion

### ISSUE THREAD

**Issue by chawyehsu** [brechtsanders/winlibs_mingw#36]
https://github.com/brechtsanders/winlibs_mingw/releases/tag/10.2.0-11.0.0-9.0.0-r5

The release tag marked with a `9.0.0` version of MinGW, but the actual version of winlibs archives is `8.0.0`. Could you please fix the confusion? I have a bot to obtain the latest releases of winlibs MinGW, which relies on the release tag.

**Comment by brechtsanders** [comment]
Thank you for letting me know. This was definitely a mistake.
Fixed now.

**Comment by chawyehsu** [comment]
Thank you for the quick response and fix, please keep up the good work! Wish you have a good day.

**Comment by chawyehsu** [comment]
@brechtsanders You marked https://github.com/brechtsanders/winlibs_mingw/releases/latest as the latest release while changing the tag, it maybe a mistake I guess.

**Comment by brechtsanders** [comment]
It seems to have broken the latest version, and I can't seem to set it to the right release...

**Comment by brechtsanders** [comment]
Fixed it by setting it as prerelease and then as release again :-)
