### ISSUE TITLE
Download went away temporarily / Python / CPython / ccache

### ISSUE THREAD

**Issue by kayhayen** [brechtsanders/winlibs_mingw#37]
Hello,

I am the author of Nuitka a Python compiler. It downloads tools on Windows, and as of recently I added winlibs gcc. Getting the usable MinGW64 has been a hardship so far. And my users barely know anything about Windows, C compilers, and MinGW64 many versions on average. They just want to compile their Python code, so winlibs is a perfect fit, esp. also as it's a more recent gcc than say the previously easiest way to tell them to get it, using Anaconda.

However, I am hardcoding download URLs in Nuitka releases. Just now, my Windows CI build failed, because the download is no longer available.

Would there be a way to keep the old releases for longer, esp. as I might want to put it through my own testing before updating it towards my users, to make sure there are no regressions? The easiest way would be to mirror the binary packages we are using on the Nuitka website and make the code download from there. But I don't know if that would be acceptable to you.

**Comment by brechtsanders** [comment]
As reported in #36 there was a mistake in the version tags, which has been fixed now.
Please check http://winlibs.com/ for the links to latest release files.

The best way to get a list of the available releases programatically would be through GitHub API, e.g.: https://api.github.com/repos/brechtsanders/winlibs_mingw/releases

Have you been able to build Python or CPython with the winlibs compiler? I can build the static version, but have problems building the shared version.

**Comment by kayhayen** [comment]
I will definitely consider the API way, esp. as Nuitka ought to also use Github releases for its things. I was browsing it, and I found the zip link there, and it was working again, and no longer 404ing. I am not really understanding the issue you linked there.

I would love to be able to have a static version of CPython (no PythonXY.DLL) and be compatible, e.g. loading the PyQT5 still, but that seems unattainable. Something (clever or stupid, I can't tell) in extension module loading requires that the DLL is present and the loading code to be in the DLL.

I am not normally building CPython myself these days. I am using Nuitka to build binaries that embedd the CPython interpreter, or to produce extension modules to load into it. They have historically made support of MinGW hard for CPython, although I have not had difficulties. I recall that e.g. floating point math results were off, at one time, but that was long ago and probably not a MinGW64 one.

My biggest complaints about MinGW64 is right now, they are not doing LTO at all, just gives an error. I have some hopes on the clang distribution of yours though. New MSVC and clangcl (likely, I didn' verify) do LTO.

In fact, I would not be opposed to having a fork of CPython that is compiled, and ask people to use that one instead. For Nuitka, there is always a few things that it wants to hook, but has a hard time, but the amount of effort is too high right now, and the out of the box experience is important. But now with winlibs, that's really a lot of steps easier as the compiler is out of the equation for the setup, so I might reconsider.

That said, I invite you to copy me on issues you have compiling Python shared with winlibs. Nuitka could of course instead of embedding also aim at integrating the CPython code into itself, and hack the extension module loading to use a DLL. If my suspect is right, and DLLs with symbol dependencies can only satisfy those symbols though another DLL, we could make such a DLL that on load, would be pass through to the embedded static implementation.

Also, if I could make this a wishlist thing. Why not include ccache in your distribution? Their Windows support seems good and that's a good way of having it. Nuitka is downloading it from official Github release, but that must be something every winlibs using developer wants to use anyway.

**Comment by brechtsanders** [comment]
I think including ccache is a really good idea. Unfortunately it seems to be broken for MinGW from version 4.0 onwards.
I'm still trying to figure out what's wrong so I can patch it.

**Comment by brechtsanders** [comment]
Found it: ccache 4.1 works fine when it's build with the `-DENABLE_IPO:BOOL=ON` option.
So I can distribute it with the next release, which you can expect soon as a new binutils version (2.36) was just released.

**Comment by brechtsanders** [comment]
Did some more tests and ccache 4 still has issues.
But the new release https://github.com/brechtsanders/winlibs_mingw/releases/tag/10.2.0-11.0.0-8.0.0-r6 now includes an older ccache that works fine.

**Comment by kayhayen** [comment]
Did you consider their config at https://github.com/ccache/ccache/blob/master/.github/workflows/build.yaml where they seem to have something for MinGW64 as well.
