### ISSUE TITLE
"terminate called without an active exception" is printed when my application exits

### ISSUE THREAD

**Issue by Keithcat1** [brechtsanders/winlibs_mingw#38]
Hi,
I'm using WinLibs along with Go to statically link a bunch of C++ code into my Go program.
However, when my program exits via calling Go's os.Exit(), the above message is prinettd.
This does not happen if my application exits normally, I.E. the main function returns.
Can this be removed? Since I don't think that this was happening when I used the MSYS compiler.
Thanks

**Comment by brechtsanders** [comment]
I'm not experienced in Go myself, and I wasn't able to build the [GCC Go language front-end](https://gcc.gnu.org/onlinedocs/gccgo/) yet for MinGW.

I juist build the GCC compiler against MinGW-w64, without specific code changes, so I don't know what causes your message. Maybe you should ask on a Go forum.

If you're using the compiler Go from [https://golang.org/](https://golang.org/) it may be interesting try with that compiler built from source with the compiler from [winlibs.com](http://winlibs.com/). But like I said I'm no Go expert so I haven't included that in winlibs yet.

**Comment by brechtsanders** [comment]
If you can provide a minimal reproducible example I can try to test this myself.

**Comment by Keithcat1** [comment]
I fixed the problem. Basically, I wasn't properly shutting down one of my C++ dependencies which was using threads, and it seems that that message is printed if you forcefully terminate a thread by suddenly exiting the program. This actually does happen with the MSYS program now that I checked properly.
