### ISSUE TITLE
clang -lucrt failed but gcc works

### ISSUE THREAD

**Issue by think2021** [brechtsanders/winlibs_mingw#44]
hi
i use clang -lucrt to build a source file but it gets failed with this error:

> C:\mingw64\bin\ld: C:\mingw64\x86_64-w64-mingw32\lib/libmingw32.a(lib64_libmingw32_a-charmax.o):charmax.c:(.text+0xb): undefined reference to `__imp___lconv_init'
C:\mingw64\bin\ld: C:\mingw64\x86_64-w64-mingw32\lib/libmingw32.a(lib64_libmingw32_a-pseudo-reloc.o):pseudo-reloc.c:(.text+0x46): undefined reference to `fwrite'
C:\mingw64\bin\ld: C:\mingw64\x86_64-w64-mingw32\lib/libmingw32.a(lib64_libmingw32_a-pseudo-reloc.o):pseudo-reloc.c:(.text+0x63): undefined reference to `vfprintf'
C:\mingw64\bin\ld: C:\mingw64\x86_64-w64-mingw32\lib/libmingw32.a(lib64_libmingw32_a-pseudo-reloc.o):pseudo-reloc.c:(.text+0x68): undefined reference to `abort'
C:\mingw64\bin\ld: C:\mingw64\x86_64-w64-mingw32\lib/libmingw32.a(lib64_libmingw32_a-usermatherr.o):usermatherr.c:(.text+0x86): undefined reference to `__setusermatherr'
C:\mingw64\bin\ld: C:\mingw64\x86_64-w64-mingw32\lib/libmingw32.a(lib64_libmingw32_a-crt_handler.o):crt_handler.c:(.text+0xe3): undefined reference to `signal'
C:\mingw64\bin\ld: C:\mingw64\x86_64-w64-mingw32\lib/libmingw32.a(lib64_libmingw32_a-crt_handler.o):crt_handler.c:(.text+0xfd): undefined reference to `signal'
C:\mingw64\bin\ld: C:\mingw64\x86_64-w64-mingw32\lib/libmingw32.a(lib64_libmingw32_a-crt_handler.o):crt_handler.c:(.text+0x13a): undefined reference to `signal'
C:\mingw64\bin\ld: C:\mingw64\x86_64-w64-mingw32\lib/libmingw32.a(lib64_libmingw32_a-crt_handler.o):crt_handler.c:(.text+0x154): undefined reference to `signal'
C:\mingw64\bin\ld: C:\mingw64\x86_64-w64-mingw32\lib/libmingw32.a(lib64_libmingw32_a-crt_handler.o):crt_handler.c:(.text+0x195): undefined reference to `signal'
C:\mingw64\bin\ld: C:\mingw64\x86_64-w64-mingw32\lib/libmingw32.a(lib64_libmingw32_a-crt_handler.o):crt_handler.c:(.text+0x1af): more undefined references to `signal' follow
C:\mingw64\bin\ld: C:\mingw64\x86_64-w64-mingw32\lib/libmingw32.a(lib64_libmingw32_a-tlsthrd.o):tlsthrd.c:(.text+0x2b): undefined reference to `calloc'
C:\mingw64\bin\ld: C:\mingw64\x86_64-w64-mingw32\lib/libmingw32.a(lib64_libmingw32_a-tlsthrd.o):tlsthrd.c:(.text+0x11a): undefined reference to `free'
C:\mingw64\bin\ld: C:\mingw64\x86_64-w64-mingw32\lib/libmingw32.a(lib64_libmingw32_a-tlsthrd.o):tlsthrd.c:(.text+0x28d): undefined reference to `free'
C:\mingw64\bin\ld: C:\mingw64\x86_64-w64-mingw32\lib/libmingw32.a(lib64_libmingw32_a-pesect.o):pesect.c:(.text+0x1a6): undefined reference to `strncmp'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

but in gcc in works.
then it can build a binary with this that used in gcc:
`-lucrt -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt`
i test in other llvm mingw64 from github.com/mstorsjo/llvm-mingw with clang -lucrt
it can create a binary but in your llvm-mingw can not.

**Comment by brechtsanders** [comment]
Which winlibs.com build release are you using?
Can you please provide a minimal reproducible example so I can investigate?

**Comment by think2021** [comment]
build version is :
`winlibs-x86_64-posix-seh-gcc-10.2.0-llvm-11.0.0-mingw-w64-8.0.0-r6b`
example .c file:
0.c
`int main()
{}`
`clang 0.c -lucrt`
it get's error but
`gcc 0.c -lucrt`
it's working fine.

**Comment by brechtsanders** [comment]
Both commands below work fine for me:
```
echo "int main() {}" | gcc -c -o test.o -xc - && gcc -o test.exe test.o
echo "int main() {}" | clang -c -o test.o -xc - && clang -o test.exe test.o
```
But when adding `-lucrt` it fails with clang.
This however works:
```
echo "int main() {}" | clang -c -o test.o -xc - && gcc -o test.exe test.o -lucrt
```
So apparently the clang linker is not linking to the dependancies.

Why do you need `-lucrt` exactly?

I also found that the LLVM developers added some kind of exception for `-lucrt`, see: https://reviews.llvm.org/D49054

**Comment by think2021** [comment]
I just test it, but in github.com/mstorsjo/llvm-mingw, it can link it!
thanks for reply

**Comment by Scr3amer** [comment]
@think2021 Are you sure it linked against UCRT with GCC ? Because you have both in the line you pasted -lmsvcrt and -lucrt. Double check the referenced DLLs in the exe with a dependency viewer.

My rule of thumb is having 2 toolchains. One which is built with ucrt and links against it by default and another one which does the same with msvcrt. This way no problem xD.

I would love to know what is the reason of your issue though. You found something in a month ?

**Comment by brechtsanders** [comment]
Looking at https://stackoverflow.com/questions/57528555/how-do-i-build-against-the-ucrt-with-mingw-w64 I also believe a completely seperate toolchain needs to be built based on MinGW-w64 built with `--with-default-msvcrt=ucrt`.

@think2021 Why did you ask this / why do you need to link against `-lucrt`?

**Comment by imba-tjd** [comment]
It seems that ucrt has better UTF8 support in console.

According to https://docs.microsoft.com/cpp/c-runtime-library/reference/setlocale-wsetlocale?view=msvc-160#utf-8-support , `setlocale(LC_ALL, ".utf8")` should work

But in my test it doens't work with `winlibs-x86_64-posix-seh-gcc-11.1.0-mingw-w64-8.0.0-r1.7z`.

```c
#include <locale.h>
#include <stdio.h>

int main() {
    puts(setlocale(LC_ALL, ".utf8"));
}
```

**Comment by brechtsanders** [comment]
You should check with the people who wrote MinGW-w64 (http://mingw-w64.org/) to see if they have actually implemented the behavior you expect.

The winlibs.com build is not linked against -lucrt. If I were to consider this it would indeed need to be a separate toolchain.

**Comment by brechtsanders** [comment]
I have spent the last few days building a winlibs.com GCC/MinGW-w64 build against UCRT runtime.
https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.2.0-9.0.0-ucrt-r1
