### ISSUE TITLE
gdb launching issue (due to launching iconv)

### ISSUE THREAD

**Issue by crcpucmg** [brechtsanders/winlibs_mingw#45]
When testing the all the latest releases (MinGW-w64, 10.2.0, releases 7 and 4) for the Windows 10 environment - 20H2 (OS Build 19402-844), and loading gdb, iconv reports that the library libintl-2.dll (gettext related) is missing (or Windows Error Code 0xc000007b). Wouldn't it be expected that libiconv-2 and the latest library (libintl-8.dll) were being used?

Downgrading both to previous versions temporarily fixes the error. Is there another better solution?

Another detail, gdb when loading, still looks for the HOME environment variable, while HOMEPATH or USERPROFILE, now, are the ones that have the value it needs.

**Comment by brechtsanders** [comment]
Note that iconv.exe is not shipped with the winlibs build.
If you say "iconv reports that the library libintl-2.dll is missing", than you are referring to iconv.exe from somewhere else which may be an older version.
The question here is: why are you running this iconv.exe? You say this happens when loading gdb. Is making a call to the external iconv.exe executable for some reason?

**Comment by crcpucmg** [comment]
Thanks for your attention.

I know that iconv is not shipped with winlibs
but, when gdb is loading, it is called and an error is reported (Picture 1),
the dialog box identifies iconv.exe. After OK,
gdb is loaded, eventually (Picture 2).
Maybe, gdb is calling something related to libconv-2.dll
(or gettext). I've also tried to downgrade gdb from 10.1.
However, downgrading libconv-2.dll that is shipped with winlibs,
and with libintl-2.dll added to bin folder, no error is reported (Picture
3).
The last picture shows the latest gcc version tested,
but I've tested the last four ones too, since last september.
I hope that the printed screens can be of some help.
T. Cruz




Em qua., 3 de mar. de 2021 às 11:04, Brecht Sanders <
notifications@github.com> escreveu:

**Comment by brechtsanders** [comment]
I can just ship `iconv.exe` with the next release. That should solve it.
The question is: are there any other .exe files called like this?
One would expect only .dll files get called, and for that I am already making sure they are all included.

**Comment by brechtsanders** [comment]
New release at https://github.com/brechtsanders/winlibs_mingw/releases/tag/10.2.0-11.0.0-8.0.0-r8 now contains `iconv.exe`.

**Comment by crcpucmg** [comment]
Thanks.

Works fine, now.


Em qui., 4 de mar. de 2021 às 18:28, Brecht Sanders <
notifications@github.com> escreveu:
