### ISSUE TITLE
Hope for libiconv in winlibs

### ISSUE THREAD

**Issue by luhuachuixue** [brechtsanders/winlibs_mingw#49]
First of all, thanks for your awesome mingw build！
To compile some library, I need libiconv in mingw, which should include iconv.h and libiconv.a.
If you could add libiconv to winlibs for me, I would be very appreciated.

**Comment by brechtsanders** [comment]
The plan for winlibs is to be a complete ecosystem with packages all compiled from source with the same compiler.
Work is in progress right now on the build and packages system for this.
libiconv is one of the over 2000 packages that already build.
Once this work is ready to be published libiconv will be available for you.

**Comment by luhuachuixue** [comment]
Thanks for your reply! I‘m looking forward to this work
