### ISSUE TITLE
Hope for `--enable-clocale`

### ISSUE THREAD

**Issue by flaribbit** [brechtsanders/winlibs_mingw#50]
Hi, thanks for your awesome build. I notice that there are locale files in `share/locale`, but `clocale` is not enabled in configuration. I tried to build it but ran into a lot of errors and failed. I think this feature might be helpful to non-English-native users. Could you add this feature?

**Comment by brechtsanders** [comment]
According to https://gcc.gnu.org/onlinedocs/libstdc++/manual/configure.html there are different options I can choose from. Would `--enable-clocale=generic` be enough, or should I consider `--enable-clocale=gnu`?

**Comment by flaribbit** [comment]
Thanks for your reply, but I have no idea which one is better, as far as I know, Manjaro and old MinGW use `--enable-clocale=gnu`, and they work fine, so I prefer gnu.

**Comment by brechtsanders** [comment]
I will try to make a build with this option, so you can test it.
What exactly doesn't work without it, and do you have a reproducible scenario?

**Comment by flaribbit** [comment]
sorry I havn't met that yet😥

**Comment by brechtsanders** [comment]
Can you try the `--enable-clocale=gnu` build I just released here: https://github.com/brechtsanders/winlibs_mingw/releases/tag/10.3.1-snapshot20210410 and let me know if that works better for you?

**Comment by flaribbit** [comment]
Ah, I'm wrong, it doesn't work, and it even don't visit `share/locale`(monitored with [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon)). I would appreciate it if you continue to try `generic`, if it still don't work, forget about it.

Here are Manjaro and MinGW's config, their language can be changed by `export LANG=xx` or `set LANG=xx`:
```
[manjaro]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (GCC)
```
```
C:\MinGW\bin>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/9.2.0/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-9.2.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --target=mingw32 --disable-win32-registry --with-arch=i586 --with-tune=generic --enable-static --enable-shared --enable-threads --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --enable-libgomp --disable-libvtv --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --disable-build-format-warnings --prefix=/mingw --with-gmp=/mingw --with-mpfr=/mingw --with-mpc=/mingw --with-isl=/mingw --enable-nls --with-pkgversion='MinGW.org GCC Build-2'
Thread model: win32
gcc version 9.2.0 (MinGW.org GCC Build-2)
```

**Comment by brechtsanders** [comment]
Are you just loooking for gcc output in your language? In that case `--enable-nls` should do. I disabled it in the past as I was aiming for highest performance and I was assuming nobody really depends on the localized output as its harder to searcjmh for translated errors and warnings online.

**Comment by flaribbit** [comment]
Yes, that's what I'm loooking for. Sorry for misleading. Turned out it’s nls, no wonder I couldn’t find anything about changing the locale. I agree with what you concern, maybe I should give up this idea. Thank you for your patient reply.
