### ISSUE TITLE
enable-libatomic Atomics not compiling

### ISSUE THREAD

**Issue by seppeon** [brechtsanders/winlibs_mingw#52]
It could be my own ineptitude, but I'm unable to get atomics compiling.
When I do `g++ -v` it doesn't seem like enable-libatomic is present (or enable-threads=posix).
Is this correct?

**Comment by brechtsanders** [comment]
The settings you mention are not gcc/g++ parameters, but parameters for building gcc/g++ from source.

The winlibs.com build of GCC was compiled without `--without-libatomic` and with `--enable-threads=posix`.

The following files are present in the winlibs.com download package under `mingw32`/`mingw64`:
- `libatomic-1.dll`
- `lib/libatomic.a`
- `lib/libatomic.dll.a`
