### ISSUE TITLE
GCC 11 floating point from_chars not supported

### ISSUE THREAD

**Issue by DeadParrot** [brechtsanders/winlibs_mingw#54]
Just trying out the GCC 11.1.0 release 1. I was hoping to be able to use the new from_chars support for floating point types but it doesn't appear to be enabled in this build. The functions are declared in charconv in a `#if _GLIBCXX_HAVE_USELOCALE` block so I assume that isn't defined for this build. If it would be possible to enable this in future builds that would be great. Or at least knowing what the obstacles are.

And thanks for these excellent MinGW builds!

**Comment by brechtsanders** [comment]
If you have a minimal reproducible code example I can look into this.
If this is not just the case for Windows however, this may be a question you should probably ask the GCC development team.

**Comment by DeadParrot** [comment]
I don't have GCC 11.1 on a Linux box yet to verify that it works but I assume it does since that is in the release notes. 

Here is a small demo:
```
// MinGW: g++ -std=c++17 from_chars.cpp -o from_chars.exe
//  error: no matching function for call to 'from_chars(char*&, char*&, float&)'

// VC++2019: cl /std:c++17 /EHsc from_chars.cpp

#include <charconv>
#include <iostream>

int
main()
{
	char s[] = "1.2345";
	char * b = &s[ 0 ];
	char * e = b + 6;
	float f( 0.0 );
	std::from_chars( b, e, f );
	std::cout << f << std::endl;
}

```

**Comment by brechtsanders** [comment]
Searching for this issue shows up multiple very recent issues and patches.
e.g.: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100146

I'm not sure how to get _GLIBCXX_HAVE_USELOCALE working on Windows though, or if this es even supported.

From what I see on this link: https://gcc.gnu.org/pipermail/gcc-patches/2020-July/550331.html it looks like the this from_chars isn't very final or ready for production

**Comment by brechtsanders** [comment]
Glad to hear you have a workaround.
GCC 11 is indeed still very rough. I'm trying to figure out several issues left and right (e.g. Qt5 not building).
