### ISSUE TITLE
It is of great value! I wish this project can be active for a long long time.

### ISSUE THREAD

**Issue by CoderTyn** [brechtsanders/winlibs_mingw#58]
By the way, we can write an updater for this toolchain,so we can keep it up to date all the time.

**Comment by brechtsanders** [comment]
Thanks. One of the strengths now is that there is no installer. Just unzip and use.
A risk of an updater is that when you update the toolchain in place libraries built with old and new toolchain version may not work well together (especially between major compiler releases).
