### ISSUE TITLE
i686 choco package

### ISSUE THREAD

**Issue by melanchall** [brechtsanders/winlibs_mingw#59]
Can i686 latest package be uploaded to Chocolatey. It seems package in Chocolatey is not actively maintaining... :(

I need to install i686-w64-mingw32-gcc.exe from CI build so I need command-line interface to have 32-bit gcc.

**Comment by brechtsanders** [comment]
Sorry, I have idea who manages this in Chocolatey. Have you asked there?

**Comment by melanchall** [comment]
Thanks for quick reply!

I have a CI build so I need to do all actions silently via scripts. Chocolatey is a popular package manager to install tools within CI build. Right now I get winlibs and build 32-bit DLL by PowerShell script:

```powershell
Write-Host "Downloading winlibs..."
Invoke-WebRequest -Uri "https://github.com/brechtsanders/winlibs_mingw/releases/download/11.1.0-12.0.0-9.0.0-r1/winlibs-i686-posix-dwarf-gcc-11.1.0-mingw-w64-9.0.0-r1.zip" -OutFile "winlibs.zip"
Write-Host "Downloaded."

Write-Host "Extracting winlibs..."
Expand-Archive -LiteralPath 'winlibs.zip' -DestinationPath "winlibs"
Write-Host "Extracted."

Write-Host "Building DLL..."
$gccPath = Get-ChildItem -Path "winlibs" -File -Filter "i686-w64-mingw32-gcc.exe" -Recurse

& $gccPath.FullName -c test.c -m32
& $gccPath.FullName -shared -o test.dll test.o -m32
Write-Host "Built."
```

So as you can see I download .zip from GitHub releases, unzip it and then execute required compiler. But it's not a reliable way since GitHub releases URLs can be changed, I don't think it's a good decision to rely on URLs at all. With Chocolatey installation will look this:

```
choco install winlibs-i686
```

which will download, unpack and put output folder to the PATH variable, so a user don't need to take care about internals of this process.

No, I didn't contact author of package on Chocolatey. Have you plans to publish your tools there with each new release? It would be super handy!

Anyway thank you! Your product is the only that allows me to have i686 gcc and build 32-bit DLL on 64-bit Windows. Maybe I'm stupid but all other software that provide this compiler don't work within my CI builds (Azure Pipelines). So you're my savior :)

Thanks,
Max

**Comment by melanchall** [comment]
Hi @brechtsanders,

Any comments on the issue?

**Comment by brechtsanders** [comment]
I'm not experienced with writing Chocolatey packages. But like you say, it should basically just download and unpack. So it should be fairly forward for anyone who knows how to do this.

I don't have enough time to investigate this myself, but there are a few things to consider.
For example I'm not a fan of installing this in a location in the `PATH` variable that is also used for other things.
In particular the 32-bit version may contain DLLs that conflict with other 64-bit software breaking that software.

In my own CI builds I just download the winlibs .7z archive, extract it (using 7-Zip, but you could stick with the (larger) .zip file if you like) and either set CC/CXX environment variables or add the extract location's `bin` folder to `PATH`.

**Comment by melanchall** [comment]
OK, I'll use archive then. Thanks for the winlibs!
