### ISSUE TITLE
AVR headers and libs are included in i686 and x86_64 mingw releases

### ISSUE THREAD

**Issue by turkerali** [brechtsanders/winlibs_mingw#60]
New releases for mingw for i686 and x86_64  includes headers and libs for AVR architecture, which almost doubles the extracted size. You may want to exclude this architecture from the default distribution. Thanks.

**Comment by brechtsanders** [comment]
The addition of AVR target support (see #60), probably wasn't such a good idea.
It would be better to do this in a separate archive.
I can take this into consideration for the next release.
