### ISSUE TITLE
gcc-10.3.0: Error "ld.exe: cannot find -ldl" when usign openmp

### ISSUE THREAD

**Issue by MortenMacFly** [brechtsanders/winlibs_mingw#62]
I want to use openmp in a DLL. I am using:
winlibs-i686-posix-dwarf-gcc-10.3.0-llvm-12.0.0-mingw-w64-9.0.0-r1.7z

When I compile, I receive this error:
d:/mingw_winlibs/bin/../lib/gcc/i686-w64-mingw32/10.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -ldl
collect2.exe: error: ld returned 1 exit status

Note that I am not adding this lib by myself and that the same DLL compiled w/o openmp works just fine. This is the erroneous command line:
i686-w64-mingw32-g++.exe -shared  -Wl,--out-implib=libcostfunc_parallel_dll.a -Wl,--dll CostFunc.o  -o costfunc_parallel.dll -static-libstdc++ -static-libgcc -static -s -fopenmp

Any hint what could be the root of this problem?

**Comment by brechtsanders** [comment]
Do you have some minimal code example I can use to reproduce your issue?

Do you have the same issue when using the latest snapshot build from https://github.com/brechtsanders/winlibs_mingw/releases/tag/10.3.1-snapshot20210604-9.0.0-r1 ?

**Comment by MortenMacFly** [comment]
Sure, here is the C++ code of a dummy DLL that I am trying to compile/link statically:

`//***********************************************************************

#ifdef _WIN32
  #include <windows.h>
  #ifdef BUILD_DLL
    #define DLL_EXPORT __declspec(dllexport)
  #else
    #define DLL_EXPORT __declspec(dllimport)
  #endif
#else
  #define DLL_EXPORT
#endif

//***********************************************************************

#ifdef _WIN32
BOOL WINAPI DllMain(HINSTANCE /*hinstDLL*/, DWORD fdwReason, LPVOID /*lpvReserved*/);
#endif

//***********************************************************************

unsigned int DLL_EXPORT DummyFunc(unsigned int uiDummy)
{
  return uiDummy++;
}

//***********************************************************************

#ifdef _WIN32
BOOL WINAPI DllMain(HINSTANCE /*hinstDLL*/, DWORD fdwReason, LPVOID /*lpvReserved*/)
{
  switch (fdwReason)
  {
    // attach to process ->  return FALSE here to fail DLL load
    case DLL_PROCESS_ATTACH : break;
    // detach from process
    case DLL_PROCESS_DETACH : break;
    // attach to thread
    case DLL_THREAD_ATTACH  : break;
    // detach from thread
    case DLL_THREAD_DETACH  : break;
    default:                  break;
  }
  return TRUE; // success
}
#endif // _WIN32

//***********************************************************************
`

...and here are the compile/link  commands:

i686-w64-mingw32-g++.exe -Wall -W -O2 -fopenmp -DBUILD_DLL -m32 -std=gnu++14 -c DummyFunc.cpp -o DummyFunc.o
i686-w64-mingw32-g++.exe -shared -Wl,--out-implib=libDummyFunc.a -Wl,--dll DummyFunc.o -o DummyFunc.dll -static-libstdc++ -static-libgcc -static -s -fopenmp -m32

Note that if you rename libdl.dll in the bin folder of MinGW to libdl.a and place it in the lib folder it works. However, that is no the roper way to do it, obviously. You should consider to create the DLL and static import version of the lib at compile time and add it to your distro.

So what should be in the lib folder is: libdl.dll.a and libdl.a

**Comment by MortenMacFly** [comment]
> Do you have the same issue when using the latest snapshot build from https://github.com/brechtsanders/winlibs_mingw/releases/tag/10.3.1-snapshot20210604-9.0.0-r1 ?

As long as you don't ship the required libs it won't work. So obviously it also does not work with that version.

Note that this is related to static linking only. But this is something a lot developers do to avoid the dependency on GCC libs which are usually not present on the target machine.

**Comment by brechtsanders** [comment]
I just did a new release that includes the `libdl.a` and `libdl.dll.a` files, see https://github.com/brechtsanders/winlibs_mingw/releases/tag/10.3.0-12.0.0-9.0.0-r2
Does it work now?

**Comment by MortenMacFly** [comment]
> Does it work now?

This works as a charm, thank you!

However, I noticed that you've exchanged most static link libs with the dynamic link lib version now (esp. the clang libs, for example). While it is OK for me, other users that rely on static linking of these might complain. Not sure if that was intended?

Thanks anyway for the great work... :-)

**Comment by brechtsanders** [comment]
That's good news.

For LLVM/Clang some people were asking for static libraries, and others were complaining the static build was too bloated. So this release has shared LLVM/Clang instead of static.

Maybe I should provide both but link the executables to the shared libraries, as it's mainly the .exe files that were enormous (which I assume also has performance impact)...

**Comment by liudonghua123** [comment]
I have the similar issue, and I installed `mingw-w64-i686-dlfcn` or `mingw-w64-x86_64-dlfcn` to fix it.

See also https://packages.msys2.org/package/mingw-w64-i686-dlfcn, https://packages.msys2.org/package/mingw-w64-x86_64-dlfcn.

**Comment by brechtsanders** [comment]
Please use the latest download from https://winlibs.com/

Mixing DLLs from MSYS2 like that is not guaranteed to be stable.
