### ISSUE TITLE
New version request (GCC 9.4.0 + MinGW-w64)

### ISSUE THREAD

**Issue by zborac** [brechtsanders/winlibs_mingw#63]
Can we expect GCC 9.4.0 + MinGW-w64 release soon?

**Comment by brechtsanders** [comment]
I somehow missed that GCC 8.5.0 and 9.4.0 were recently released.
Thanks for reminding me.

Yes, I will try to build them against MinGW-w64 9.0.0 and publish the new releases.

**Comment by brechtsanders** [comment]
https://github.com/brechtsanders/winlibs_mingw/releases/tag/9.4.0-9.0.0-r1
