### ISSUE TITLE
Is there any plan to make an installer?

### ISSUE THREAD

**Issue by TurnOffNOD** [brechtsanders/winlibs_mingw#64]
Hi, I search "mingw-w64 gcc11" and find here. Is there any plan to build an installer of this project?

**Comment by brechtsanders** [comment]
One of the stengths of the winlibs builds is that it doesn't need an installer, just extract the archive.

Why would you need an installer exactly?

**Comment by Eric-01** [comment]
> One of the stengths of the winlibs builds is that it doesn't need an installer, just extract the archive.

Exactly. It's one of the reasons why I use WinLibs for some time now instead of the other MinGW-based toolchains.

If you don't like the 7z format, or simply you don't have a suitable program to unpack it, you can use the commonly used ZIP instead.

**Comment by SirTwsted** [comment]
Quick question.  I have v8.1.0 of MingW-64 ,  can I just Un7zip and overwrite my current MingW-64 folder I have on C:\
Or does it need to be fresh.?  thanks :)
Also just checking is the 7zip suppose to be 655-mb....  like holy crap thats huge.  The version I got was this one.
winlibs-x86_64-posix-seh-gcc-11.1.0-llvm-12.0.0-mingw-w64-9.0.0-r2.7z

**Comment by brechtsanders** [comment]
I would really recommend a fresh extract.

Because there is no installation you can also have different versions on your system if needed.

If you don't need LLVM/Clang you should download the package without llvm in the name, because that's what's making it so much bigger.
