### ISSUE TITLE
GDB with python support

### ISSUE THREAD

**Issue by DEKOHG** [brechtsanders/winlibs_mingw#65]
Hi,
I am new to using the GNU project's tools on Windows. I just found your project recently. I am wondering if it is possible to add GDB with python support into the distribution. Thank you.

**Comment by xtemp09** [comment]
We all want [python support](https://github.com/brechtsanders/winlibs_mingw/issues/2).

Perhaps, sending a beer to the author will make it possible.

**Comment by brechtsanders** [comment]
That's right. I'm already trying to figure this out.
I would like to include Python in the winlibs distribution, built with matching GCC compiler.
Once that works I should be able to build GDB against it.

**Comment by brechtsanders** [comment]
Closing this ticket as it is a duplicate of #2

**Comment by xtemp09** [comment]
Perhaps, inclusion of python into distribution is a big step. People who need python already have it installed along with PyPy, NumPy, CPython etc. Users need gdb to support python, i.e. python39.dll.

**Comment by brechtsanders** [comment]
What is are you proposing exactly?

My idea is to have a python DLL included in the distribution, so one version can be used, instead of mixing versions which may cause GDB Python issues...

**Comment by PNBRQK** [comment]
Just want to ask a question:

Since the version included in GCC12.* releases is Python 3.9 which dropped support of Windows 7 as in Python's official declaration, does this change mean that newer releases can refuse to run on Win7?

Thanks for the compiler anyway

**Comment by brechtsanders** [comment]
First of all, Windows 7 is no longer supported by Microsoft. So it may nod be a good idea to use such an old version, especially when you think of security (since there are no more updates).

It's possible GDB linked against this Python works on Windows 7 as long as you don't use any Python in GDB, but there are no guarantees.

**Comment by xtemp09** [comment]
Windows 7 has extended support. Even if you didn't acquire it, some security bugfixes show up from time to time. Perhaps, Microsoft does not want to have 1.5 billion of bots DDoSing their servers.

Python `3.8.16` still supports Windows 7. Qt `5.15.13` has been released several days ago (and soon there will be `5.15.14`). `mingw-w64/gcc` still supports Windows 7.
