### ISSUE TITLE
Any plan for including OpenMPI and OpenCoarrays along with the distribution?

### ISSUE THREAD

**Issue by DEKOHG** [brechtsanders/winlibs_mingw#67]
Hi Brecht,
Thanks for your winlibs. It makes my process of learning programming on Windows a lot easier. 
I am wondering if there's any plan to integrate the OpenMPI and OpenCoarrays into the distribution cuz I am trying too learn parallel computing in fortran? Thank you.

**Comment by brechtsanders** [comment]
OpenMPI doesn't build on Windows and OpenCoarrays depends on it. So I haven't been able to build them yet.
