### ISSUE TITLE
64bit to crosscompile 32bit

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [brechtsanders/winlibs_mingw#69]
can those cross compile to 32bit easily? like the sourforge sjlj versions? (just adding the -m32?)

**Comment by brechtsanders** [comment]
For now the winlibs distributions don't cross-compile.

As for SJLJ, see #4 and #20. Basically SEH is used for 64-bit and Dwarf for 32-bit in the winlibs builds.

**Comment by TurnOffNOD** [comment]
> 
> 
> For now the winlibs distributions don't cross-compile.
> 
> As for SJLJ, see #4 and #20. Basically SEH is used for 64-bit and Dwarf for 32-bit in the winlibs builds.

HI, why winlibs distributions choose not to cross-compile? Is there any difficulties?

**Comment by brechtsanders** [comment]
That's because native builds allowed me to build even more packages from source.
What kind of cross-compiler would you be looking for? From another platform (like Linux) to Windows, or from Windows to another platform (like Linux or Arduino/ARM)?

**Comment by TurnOffNOD** [comment]
> That's because native builds allowed me to build even more packages from source.
> What kind of cross-compiler would you be looking for? From another platform (like Linux) to Windows, or from Windows to another platform (like Linux or Arduino/ARM)?

I am looking for something like gcc-multilib in linux distribution, which is a cross-compiler from x86_64 (64bit gcc binary) to x86 (32bit target). I will use it on Windows.

The usage of this kind of cross-compiler is as simple as "gcc -m32 foobar.c". That's why I like it.
(Of course, when I want 64bit target binary, its usage will be "gcc -m64 foobar.c" or just "gcc foobar.c").

**Comment by brechtsanders** [comment]
I have been keeping 32-bit and 64-bit toolchains separate on purpose, as a lot of people run into issues because they (accidentally) mix `-m32` and `-m64` libraries.

I just run the native 32-bit toolchain on Windows 64-bit without any issues. Some sources even compile slightly faster with 32-bit than 64-bit.

So never really saw a reason to have a 64-bit cross-compiler targetting Windows 32-bit.

**Comment by MyTDT-Mysoft** [comment]
> I have been keeping 32-bit and 64-bit toolchains separate on purpose, as a lot of people run into issues because they (accidentally) mix `-m32` and `-m64` libraries.
> 
> I just run the native 32-bit toolchain on Windows 64-bit without any issues. Some sources even compile slightly faster with 32-bit than 64-bit.
> 
> So never really saw a reason to have a 64-bit cross-compiler targetting Windows 32-bit.

well the reason was simple... NOTHING should be compiled for 64bit unless required... then 32bit should be the default... but then people are inticed into downloading the 64bit one because it appears as default... and then to compile anything 32bit it becomes 10x worse... while people on windows expect to just be able to compile without having to do a bunch of settings... so a compiler that does not work with -m32 makes this problem worse... and its made worse by the fact that gcc does not SEH for 32bit, altough that mostly affects C++ and i dont make C++ programs, so for my case thats irrelevant, except the problem it causes by bad defaults... many of them that are inherited by linux people where its not natural to have 32bit on the 64bit version of OS...

**Comment by brechtsanders** [comment]
With the native compiler use the 32-bit toolchain to build 32-bit only and use 64-bit to coompile 64-bit only.

This principle also helps avoid mixing the libraries and binaries for the 2 platforms, especially for people that never heard of cross-compiling.

All sources using build tools (e.g. autotools, cmake, meson, scons) or even plane make have no issues with this. It does mean separate builds (which I do for even for CI builds), but all for the benefit of not accidentally mixing platforms.

I have thought about adding `-m64` support to the 32-bit compiler (and `-m32` to the 64-bit compiler), but I'm pretty sure that would also make the compiler package much larger, and there are already multiple users asking to reduce size and bloat.
