### ISSUE TITLE
Building GCC 9.3 meet some error

### ISSUE THREAD

**Issue by Efreets** [brechtsanders/winlibs_mingw#7]
Hi,
  Do you have some time to help me to solve the problem with building gcc 9.3 on windows?
  Thanks.

  Here was my information during Build gcc, how it makes, I'm my best to solve the error, but it's no work

  My configure is

../gcc-9.3.0/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/P/Efreets/gcc930/ --with-sysroot=/P/Efreets/gcc930/ --enable-languages=c,lto,c++,fortran --enable-lto --enable-static --disable-symvers --disable-shared --enable-threads=posix --enable-sjlj-exceptions --with-system-zlib --with-gmp=/P/Efreets/gmp620 --with-mpfr=/P/Efreets/mpfr402 --with-mpc=/P/Efreets/mpc110 --with-isl=/P/Efreets/isl221 --with-zstd=/P/Efreets/zstd144

  It's meet this error

[ -f stage_final ] || echo stage3 > stage_final
make[1]: Entering directory 'P:/gcc930/gcc-9.3.0/Build'
make[2]: Entering directory 'P:/gcc930/gcc-9.3.0/Build'
make[3]: Entering directory 'P:/gcc930/gcc-9.3.0/Build'
rm -f stage_current
make[3]: Leaving directory 'P:/gcc930/gcc-9.3.0/Build'
make[2]: Leaving directory 'P:/gcc930/gcc-9.3.0/Build'
make[2]: Entering directory 'P:/gcc930/gcc-9.3.0/Build'
/usr/bin/sh: -c:行6: unexpected EOF while looking for matching `''
/usr/bin/sh: -c:行7: syntax error: unexpected end of file
make[2]: *** [Makefile:11206: all-stage1-libiberty] Error 1
make[2]: Leaving directory 'P:/gcc930/gcc-9.3.0/Build'
make[1]: *** [Makefile:21113: stage1-bubble] Error 2
make[1]: Leaving directory 'P:/gcc930/gcc-9.3.0/Build'
make: *** [Makefile:1003: all] Error 2

  And this is the error line in MakeFile
![eff889e3d134e9e2d88fbbae7fb15c79](https://user-images.githubusercontent.com/11472828/78423367-7b106500-7698-11ea-9fe3-8b3ec5817772.png)
![76f4fa84a85768a6c2482d160c8b1d07](https://user-images.githubusercontent.com/11472828/78423383-89f71780-7698-11ea-9c16-086a35624790.png)

I think error line in right, but I can't solve the problem, could you help me ?

  I can't thank you so much, I need you help, Waiting message.

yours sincerely

**Comment by brechtsanders** [comment]
Hi,
First of all: are you sure you are looking at the MakeFile in the right folder (`P:/gcc930/gcc-9.3.0/Build/MakeFile`)?
If that is the right line you should check what the value of `PWD_COMMAND` is set to. Maybe it contains something wrong (like a single backtick)...
I myself haven't encountered this situation yet, but maybe that's because I build on Windows with these configure switches: `--disable-bootstrap --disable-stage1-checking`.
Good luck!
Brecht

**Comment by Efreets** [comment]
> Hi,
> First of all: are you sure you are looking at the MakeFile in the right folder (`P:/gcc930/gcc-9.3.0/Build/MakeFile`)?
> If that is the right line you should check what the value of `PWD_COMMAND` is set to. Maybe it contains something wrong (like a single backtick)...
> I myself haven't encountered this situation yet, but maybe that's because I build on Windows with these configure switches: `--disable-bootstrap --disable-stage1-checking`.
> Good luck!
> Brecht

Thankg for your replaying, the Makefile is the error file by make said, I also think may be the PWD_COMMAND = $${PWDCMD-pwd}  was not work correct, because is't not send the pwd path value to the r, it does relay the source path to the system environment, but I don't know why, I'm Building under msys2, I distrust my msys2, because I built another gnu soft, like binutils, also meet the unexpected EOF while looking for matching `'' error, I didn't solve this problem, I need why that happend, I need your help, if you know how to solve.

Thanks
yours sincerely

**Comment by Efreets** [comment]
I modified the make file and make was this
![捕2获](https://user-images.githubusercontent.com/11472828/78424299-33d9a280-769f-11ea-85d4-8e3a767378f4.PNG)
![捕获](https://user-images.githubusercontent.com/11472828/78424302-3cca7400-769f-11ea-923e-8e9613911425.PNG)

**Comment by Efreets** [comment]
I'm new to building the gcc9.3, and didn't have the experience for the gnu soft building, didn't know why this happend, if you know how to solve, help me, please.
Thanks.

**Comment by Efreets** [comment]
> Hi,
> First of all: are you sure you are looking at the MakeFile in the right folder (`P:/gcc930/gcc-9.3.0/Build/MakeFile`)?
> If that is the right line you should check what the value of `PWD_COMMAND` is set to. Maybe it contains something wrong (like a single backtick)...
> I myself haven't encountered this situation yet, but maybe that's because I build on Windows with these configure switches: `--disable-bootstrap --disable-stage1-checking`.
> Good luck!
> Brecht

May be you are right about PWD_COMMAND was wrong, could you tell me how to set the PWD_COMMAND, I can't find any site about PWD_COMMAND, could you tell me the detail about PWD_COMMAND should be?

**Comment by brechtsanders** [comment]
I'm also building using MSYS2.
These things aren't ease and require a lot of digging.
I was only successful after failing many times...
You could to override PWD_COMMAND by running something like `make PWD_COMMAND=pwd` or `make PWD_COMMAND="pwd -W"`
Also I notice your error log contains some Asian characters.
I would avoid language specifics by starting out with this command: `export LANG=C`

**Comment by Efreets** [comment]
Could you mind to tell me your Building script and Configures, also make command or other details?
Or put them on your opensource Github repository.
Thanks.

**Comment by brechtsanders** [comment]
Please see issue #1 for now on how I built GCC itself.
There are a lot of dependancies which I also built from scratch.
When ready those build script will also be published as part of the winlibs.com project.

**Comment by flaribbit** [comment]
Same error, `export LANG=C` has some effect, and it goes a few more steps, then meet the same error again.

```
$ mingw32-make
[ -f stage_final ] || echo stage3 > stage_final
mingw32-make[1]: Entering directory 'D:/msys64/home/sora/source/build'
mingw32-make[2]: Entering directory 'D:/msys64/home/sora/source/build'
mingw32-make[3]: Entering directory 'D:/msys64/home/sora/source/build'
rm -f stage_current
mingw32-make[3]: Leaving directory 'D:/msys64/home/sora/source/build'
mingw32-make[2]: Leaving directory 'D:/msys64/home/sora/source/build'
mingw32-make[2]: Entering directory 'D:/msys64/home/sora/source/build'
/usr/bin/sh: -c: line 7: unexpected EOF while looking for matching `"'
/usr/bin/sh: -c: line 8: syntax error: unexpected end of file
mingw32-make[2]: *** [Makefile:11283: all-stage1-libiberty] Error 2
mingw32-make[2]: Leaving directory 'D:/msys64/home/sora/source/build'
mingw32-make[1]: *** [Makefile:22911: stage1-bubble] Error 2
mingw32-make[1]: Leaving directory 'D:/msys64/home/sora/source/build'
mingw32-make: *** [Makefile:1009: all] Error 2
```

![Snipaste_2021-04-11_16-56-13](https://user-images.githubusercontent.com/24885181/114298054-f516cd80-9ae6-11eb-9f90-2bd9fa79a2a5.png)

Maybe... only computer with English system can build it?

**Comment by flaribbit** [comment]
Oh, envs in `mingw32-make` is wrong, use `make` instead.
