### ISSUE TITLE
Can't run my exe build with this

### ISSUE THREAD

**Issue by awidesky** [brechtsanders/winlibs_mingw#70]
I tried both GCC 11.1.0 and GCC 10.3.0 (without LLVM), compiled my cpp file(which is well compiled in other compilers in the pc)
`g++ D:\development\src\fsqrt\main.cpp -o D:\development\src\fsqrt.exe`
It did good, giving me fresh new exe file.

But every time I try to execute it, error message pops up and says(there must be some incorrect error message since I translated Korean error message into English) :
 1. Can't progress cote execution because libgcc_s_seh-1.dll does not exist. Problem may be solved if reinstall the program.
 2. Can't progress cote execution because libstdc++-6.dll does not exist. Problem may be solved if reinstall the program.
 3. Can't progress cote execution because libwinpthread-1.dll does not exist. Problem may be solved if reinstall the program.
 
Can someone please help me with this issue?

  
![This](https://user-images.githubusercontent.com/40064726/126274073-81d9de8e-cecf-47d2-864b-ca5afc508570.PNG) 
This is one of th error popups(Korean).

**Comment by brechtsanders** [comment]
By default your application will depend on shared libraries (.dll files), and in your case the .dll files could not be found. It's best to copy them in the same directory as the .exe file. Or alternatively your PATH environment variable could be configured to include the location of the .dll files.

Another solution is to build the .exe with the `-static` flag, and for the C and C++ standard libraries also with `-static-libgcc` and  `-static-libstdc++` respectively. This will roll all the dependencies in the .exe file, making it bigger, but avoiding the need for separate .dll files.
