### ISSUE TITLE
UCRT Version not support unicode output filename

### ISSUE THREAD

**Issue by alphagocc** [brechtsanders/winlibs_mingw#73]
The linker can't correctly link the executable file

**Comment by brechtsanders** [comment]
Can you please say what you did exactly and what the output/error was?

**Comment by alphagocc** [comment]
```
PS C:\Users\Alphagocc\Documents\Programming\Coding\Archive\2021\10\06> g++.exe [CTSC2008]图腾.cpp  -o [CTSC2008]图腾.exe                                     
c:/users/alphagocc/scoop/apps/winlibs-gcc-ucrt/current/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: 
cannot open output file [CTSC2008]?: Illegal byte sequence
collect2.exe: error: ld returned 1 exit status
```
![image](https://user-images.githubusercontent.com/28982331/136148742-c9e5f26d-6a5d-4a4f-b643-41ce8fb90bf2.png)

**Comment by brechtsanders** [comment]
As you can see the exact error is `cannot open output file`. This is a known problem with gcc, especially on Windows.

Avoid spaces and non ASCII characters in path names and filenames. To test this try replacing `图腾` with `test`.

**Comment by brechtsanders** [comment]
The standard library is different, maybe it handles paths differently...
