### ISSUE TITLE
gcc crash during building qt with gcc 11.2.0

### ISSUE THREAD

**Issue by farta1986** [brechtsanders/winlibs_mingw#74]
Dear maintainer,
I'm struggling with winlibs_mingw for building a Qt build with it. I run into a gcc crash here.

OS: Win 10 x64 2020H2 19042.1237
MinGW Version: winlibs-x86_64-posix-seh-gcc-11.2.0-llvm-12.0.1-mingw-w64-9.0.0-r1
winlibs_mingw installed path : C:\mingw\x64
Compiler command line:

> E:\build\qt\5.12.11\build\qtbase\src\corelib>gcc -c -include .pch\release\qt_pch.h -fno-keep-inline-dllexport -O3 -std=gnu11 -ffunction-sections -fdata-sections -Wall -W -Wextra -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DQT_NO_USING_NAMESPACE -DQT_NO_FOREACH -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_CORE_LIB -DQT_BUILDING_QT -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -DQT_NO_DEBUG -DPCRE2_CODE_UNIT_WIDTH=16 -DPCRE2_STATIC -IE:\build\qt\5.12.11\Src\qtbase\src\corelib -I. -IE:\build\qt\5.12.11\Src\qtbase\src\3rdparty\zlib\src -Iglobal -IE:\build\qt\5.12.11\Src\qtbase\src\3rdparty\harfbuzz\src -IE:\build\qt\5.12.11\Src\qtbase\src\3rdparty\md5 -IE:\build\qt\5.12.11\Src\qtbase\src\3rdparty\md4 -IE:\build\qt\5.12.11\Src\qtbase\src\3rdparty\sha3 -IE:\build\qt\5.12.11\Src\qtbase\src\3rdparty -IE:\build\qt\5.12.11\Src\qtbase\src\3rdparty\double-conversion\include -IE:\build\qt\5.12.11\Src\qtbase\src\3rdparty\double-conversion\include\double-conversion -IE:\build\qt\5.12.11\Src\qtbase\src\3rdparty\tinycbor\src -IE:\build\qt\5.12.11\Src\qtbase\include -IE:\build\qt\5.12.11\Src\qtbase\include\QtCore -I..\..\include -I..\..\include\QtCore -IE:\build\qt\5.12.11\Src\qtbase\include\QtCore\5.12.11 -IE:\build\qt\5.12.11\Src\qtbase\include\QtCore\5.12.11\QtCore -I..\..\include\QtCore\5.12.11 -I..\..\include\QtCore\5.12.11\QtCore -Itmp -I.moc\release -I.tracegen\release -IE:\build\qt\5.12.11\Src\qtbase\src\3rdparty\pcre2\src -IE:\build\qt\5.12.11\Src\qtbase\mkspecs\win32-g++  -o .obj\release\harfbuzz-gpos.o E:\build\qt\5.12.11\Src\qtbase\src\3rdparty\harfbuzz\src\harfbuzz-gpos.c
> internal error in mingw32_gt_pch_use_address, at config/i386/host-mingw32.c:192: MapViewOfFileEx: 试图访问无效的地址(Translation: Trying to access invalid address)

Qt configure & build bat script:

> SET MY_QT_SRC=E:\build\qt\5.12.11\Src
> SET MY_CXX_PATH=C:\mingw\x64\bin
> SET _ROOT=%MY_QT_SRC%
> SET PATH=%MY_CXX_PATH%;%_ROOT%\qtbase\bin;%_ROOT%\gnuwin32\bin;C:\Perl64\bin;C:\Users\fayfa\AppData\Local\Programs\Python\Python39\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files\CMake\bin
> SET _ROOT=
> CALL %MY_QT_SRC%\configure.bat -release -opensource -nomake examples -nomake tests -platform win32-g++ -static -opengl desktop -c++std c++14 -confirm-license -prefix E:\build\qt\5.12.11\5.12.11_11.2.0_x64_static
> E:\build\qt\5.12.11\5.12.11_11.2.0_x64_static -release -force-debug-info -separate-debug-info -nomake tests -nomake examples -opengl desktop -platform win32-g++ QMAKE_LFLAGS_APP+=-s -qt-zlib
> mingw32-make -j8

Directory structure:
5.12.11
├Src
├build
├configure_build.bat
└5.12.11_11.2.0_x64_static

I've ran ..\configure_build.bat in path build, then hit some compile errors due to some qt code files missing header <limits> and a file redefined an structure in winbase.h. They're trivial to fix. After them been fixed, I ran into this gcc crash above.

Would you look at this problem? Thanks a lot.
And more, do you have any suggestions about building qt with winlibs_mingw? Thank you again.

**Comment by brechtsanders** [comment]
My advice: don't use `configure_build.bat`. Instead use MSYS2 shell and use the `configure` script.
Building Qt6 got slightly easier as it uses CMake, and if you combine it with Ninja it builds a lot faster too.

Anyway, the crash you are having is caused by issues with precompiled headers. Disable it with `configure` switch `-no-pch`.
