### ISSUE TITLE
lldb crash

### ISSUE THREAD

**Issue by skykeyjoker** [brechtsanders/winlibs_mingw#75]
I use the release `GCC 11.2.0 + LLVM/Clang 13.0.0 + MinGW-w64 9.0.0 UCRT (release 2)`, but the lldb can not work.
My system is Windows 11(22000.194).
```
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: lldb
#0 0x00007ff829ce0000
#1 0x00007ff88a3a5d19 LLDBSwigLuaWatchpointCallbackFunction (C:\mingw64\bin\liblldb.dll+0x355d19)
#2 0x00007ff88a3a2891 LLDBSwigLuaWatchpointCallbackFunction (C:\mingw64\bin\liblldb.dll+0x352891)
#3 0x00007ff88a53a8b1 lldb::SBDebugger::InitializeWithErrorHandling() (C:\mingw64\bin\liblldb.dll+0x4ea8b1)
#4 0x00007ff7900fc11f (C:\mingw64\bin\lldb.exe+0xc11f)
#5 0x00007ff7900f1445 (C:\mingw64\bin\lldb.exe+0x1445)
#6 0x00007ff7900f1146 (C:\mingw64\bin\lldb.exe+0x1146)
#7 0x00007ff8e01554e0 (C:\WINDOWS\System32\KERNEL32.DLL+0x154e0)
#8 0x00007ff8e14a485b (C:\WINDOWS\SYSTEM32\ntdll.dll+0x485b)
```

**Comment by jakerdy** [comment]
Hi, brechtsanders.

I got same kind behavior with: 
winlibs-x86_64-posix-seh-gcc-11.2.0-llvm-12.0.1-mingw-w64-9.0.0-r1.7z
But with different stacktrace:
```
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: C:\\DevTools\\mingw64\\bin\\lldb.exe
#0 0x00007ffb13af0000
#1 0x00007ffb73e7190f lldb::SBBlock::GetVariables(lldb::SBFrame&, bool, bool, bool, lldb::DynamicValueType) (C:\DevTools\mingw64\bin\liblldb.dll+0x1190f)
#2 0x00007ffb74524601 luaopen_lldb (C:\DevTools\mingw64\bin\liblldb.dll+0x6c4601)
#3 0x00007ffb73ec38ca lldb::SBDebugger::InitializeWithErrorHandling() (C:\DevTools\mingw64\bin\liblldb.dll+0x638ca)
#4 0x00007ff627d6c76d (C:\DevTools\mingw64\bin\lldb.exe+0xc76d)
#5 0x00007ff627d61445 (C:\DevTools\mingw64\bin\lldb.exe+0x1445)
#6 0x00007ff627d61146 (C:\DevTools\mingw64\bin\lldb.exe+0x1146)
#7 0x00007ffbfb577034 (C:\Windows\System32\KERNEL32.DLL+0x17034)
#8 0x00007ffbfcf82651 (C:\Windows\SYSTEM32\ntdll.dll+0x52651)
```

Officials builds at the same time works.

Could you please help figure out what's wrong with my (our) setup. 
I am ready to send you any additional information that could help.

Also is lldb works on your end?

**Comment by kevin3w** [comment]
Hi Sanders 
Due to the LLDB function was crashed by the  lastest revision, and also the newest LLVM 14.0 already released, woluld you please rebuild the GCC+LLVM 14.0 packages in next coming days?  Thanks so much.

**Comment by brechtsanders** [comment]
I have been struggling with the new LLVM 14.0 release, but mainly because I wanted to also include ARM support.
Maybe I should just drop that and make it work for only i686 / x86_64.

Also I am thinking of abandoning build LLVM against GCC's standard libraries, but instead have a standalone LLVM with its own standard libraries.

But I will see what I can do in the short term.

**Comment by brechtsanders** [comment]
I just built LLVM 14.0 and packaged it in a new release:

- MSVCRT: https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.2.0-14.0.0-9.0.0-msvcrt-r7
- UCRT: https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.2.0-14.0.0-9.0.0-ucrt-r7

This is a first attempt at buiulding LLVM 14.0, and it's still built against the GCC standard libraries.
Als I'm afraid for now I had to use `-DLLDB_ENABLE_LUA:BOOL=OFF` because there were some issues otherwise.

Looking forward to your feedback.

**Comment by kevin3w** [comment]
> I just built LLVM 14.0 and packaged it in a new release:
> 
> * MSVCRT: https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.2.0-14.0.0-9.0.0-msvcrt-r7
> * UCRT: https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.2.0-14.0.0-9.0.0-ucrt-r7
> 
> This is a first attempt at buiulding LLVM 14.0, and it's still built against the GCC standard libraries. Als I'm afraid for now I had to use `-DLLDB_ENABLE_LUA:BOOL=OFF` because there were some issues otherwise.
> 
> Looking forward to your feedback.



Hi Sanders,
Thanks for your greart effort to build the new release. I just tried the new release (UCRT revision) in simple commands. There's bug was found for  the 'lldb'. The details description as below, look forward to figure out crash reason and fix it.

### [start 
**C:\Temp\mingw64\bin>lldb
Python path configuration:
  PYTHONHOME = 'D:/Prog/winlibs64ucrt_stage/custombuilt/share/python/bin'
  PYTHONPATH = (not set)
  program name = 'D:\Temp\mingw64\bin\libpython3.9.dll'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'D:\\Temp\\mingw64\\bin\\libpython3.9.dll'
  sys.base_prefix = 'D:/Prog/winlibs64ucrt_stage/custombuilt/share/python/bin'
  sys.base_exec_prefix = 'D:\\Prog\\winlibs64ucrt_stage\\custombuilt\\share\\python\\bin'
  sys.platlibdir = 'lib'
  sys.executable = 'D:\\Temp\\mingw64\\bin\\libpython3.9.dll'
  sys.prefix = 'D:/Prog/winlibs64ucrt_stage/custombuilt/share/python/bin'
  sys.exec_prefix = 'D:\\Prog\\winlibs64ucrt_stage\\custombuilt\\share\\python\\bin'
  sys.path = [
    'D:\\Prog\\winlibs64ucrt_stage\\custombuilt\\share\\python\\bin\\lib\\python39.zip',
    'D:/Prog/winlibs64ucrt_stage/custombuilt/share/python/bin\\lib\\python3.9',
    'D:\\Prog\\winlibs64ucrt_stage\\custombuilt\\share\\python\\bin\\lib\\python3.9\\lib-dynload',
    '',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00001ae0 (most recent call first):
<no Python frame>**

### end]

**Comment by brechtsanders** [comment]
You're right, lldb has a problem with Python. More info and workaround for now, see #93

**Comment by brechtsanders** [comment]
What is the status of this issue in the latest release?

* https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.3.0-14.0.3-10.0.0-msvcrt-r3
* https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.3.0-14.0.3-10.0.0-ucrt-r3

**Comment by kevin3w** [comment]
> What is the status of this issue in the latest release?
> 
> * https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.3.0-14.0.3-10.0.0-msvcrt-r3
> * https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.3.0-14.0.3-10.0.0-ucrt-r3

It's perfect works for the latest release.

**Comment by kevin3w** [comment]
It's perfect works for the latest release. The bug should be closed now.
