### ISSUE TITLE
Provide build environment & scripts

### ISSUE THREAD

**Issue by ricochhet** [brechtsanders/winlibs_mingw#76]
I was curious as to whether you'll provide build scripts / environment in the future, so I could build this toolchain myself? I'd greatly appreciate it.

**Comment by brechtsanders** [comment]
I am working on standardizing my build environment and getting the build tools ready for publication along with build recipes.
The way I build the toolchain is the build the entire dependency chain from scratch.
Once published you will be able to reproduce build yourself, but know it takes a while to build the whole chain, especially if you don't have a superfast build system...

**Comment by AdhTri001** [comment]
@brechtsanders are the build scripts ready?

**Comment by brechtsanders** [comment]
I don't have the build system documented and fine-tuned yet, but yes I have many build scripts already in usable state. So I will go ahead and publish them.
See: https://github.com/brechtsanders/winlibs_recipes

**Comment by AdhTri001** [comment]
> I don't have the build system documented and fine-tuned yet, but yes I have many build scripts already in usable state. So I will go ahead and publish them. See: https://github.com/brechtsanders/winlibs_recipes

Brilliant, thank you!
