### ISSUE TITLE
ld.exe: skipping incompatible library

### ISSUE THREAD

**Issue by fpgrande** [brechtsanders/winlibs_mingw#77]
When i've tried to compile Harbour 3.4 from Viktor Szakats https://github.com/vszakats/hb using GCC 11.2.0 + LLVM/Clang/LLD/LLDB 13.0.0 + MinGW-w64 9.0.0 (UCRT) - release 2 - Win64.

With Win32 version all is ok.

**Comment by brechtsanders** [comment]
Which library is being skipped?
Can you please paste more detailed output?

**Comment by fpgrande** [comment]
kernel32,user32,ws2_32,iphlpapi, advapi32, gdi32, winmm

**Comment by brechtsanders** [comment]
I was able to reproduce your issue.

Apparently winlibs' MinGW-w64 isn't properly detected, and it compiles 32-bit object files/libraries with `-m32` and then tries to link as 64-bit, which is indeed incompatible.

I found that adding `HB_PLATFORM=win HB_COMPILER=mingw64` to the make command works for Windows 64-bit builds (for 32-but this should be `HB_PLATFORM=win HB_COMPILER=mingw`), as this bypasses the compiler detection.

For completeness, I'm building from MSYS2 shell with this command:
```bash
make install \
  HB_INSTALL_PREFIX=/C/Temp/harbour \
  HB_PLATFORM=win HB_COMPILER=mingw64 \
  HB_BUILD_SHARED=yes \
  HB_WITH_MINIZIP=local \
  HB_WITH_MINILZO=local \
  HB_WITH_ALLEGRO=no \
  HB_WITH_CAIRO=no \
  HB_BUILD_3RDEXT=no \
  HB_BUILD_VERBOSE=yes \
  HB_IMPLIB=yes \
  HB_BUILD_DYN=no \
  HB_BUILD_CONTRIB_DYN=no \
  HB_BUILD_SHARED=no \
  HB_BUILD_STRIP=all \
  HB_WITH_ZLIB=local \
  HB_WITH_BZIP2=local \
  HB_WITH_MXML=local \
  HB_WITH_LZF=local \
  HB_WITH_CURL=$MINGWPREFIX\include \
  HB_WITH_CURL=yes \
  HB_WITH_OPENSSL=yes \
  HB_STATIC_CURL=yes \
  HB_STATIC_OPENSSL=yes &&
 echo SUCCESS
```

**Comment by fpgrande** [comment]
Sorry for my mistake. Thanks Brecht !
