### ISSUE TITLE
Winlibs gcc9.3 fails with big PCH

### ISSUE THREAD

**Issue by SzGaa** [brechtsanders/winlibs_mingw#8]
Hi, maybe you are interested in the following issue.

# Winlibs gcc9.3 fails with big PCH

Os:
* Microsoft Windows 10 Home Build 18362

Compiler:
* http://winlibs.com/
	* winlibs-x86_64-posix-seh-gcc-9.3.0-llvm-10.0.0-mingw-w64-7.0.0-r3.7z
		* g++ (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders) 9.3.0

##  Reproduce with Qt5.14.2

Prerequisite:
* http://download.qt.io/official_releases/qt/
	* qt-everywhere-src-5.14.2
* https://www.msys2.org/

Steps
* Compilation of Qt 5.14.2 debug mode with -D_GLIBCXX_DEBUG from msys2 shell
```
PATH=/c/Tools/mingw64/winlibs-x86_64-posix-seh-gcc-9.3.0-llvm-10.0.0-mingw-w64-7.0.0-r3/mingw64/bin:$PATH
cd /E/compile/qt-everywhere-src-5.14.2
./configure --prefix=/E/compile/Qt-5.14.2/dinstall-mgw93/ -platform win32-g++ -opengl desktop -nomake examples -nomake tests -nomake tools -skip qt3d -skip qtandroidextras -skip qtcanvas3d -skip qtcharts -skip qtconnectivity -skip qtdatavis3d -skip qtdeclarative -skip qtdoc -skip qtgamepad -skip qtgraphicaleffects -skip qtimageformats -skip qtlocation -skip qtmacextras -skip qtnetworkauth -skip qtpurchasing -skip qtquickcontrols -skip qtquickcontrols2 -skip qtscript -skip qtscxml -skip qtsensors -skip qtserialbus -skip qtserialport -skip qtspeech -skip qtsvg -skip qttools -skip qttranslations -skip qtvirtualkeyboard -skip qtwayland -skip qtwebchannel -skip qtwebengine -skip qtwebsockets -skip qtwebview -skip qtwinextras -skip qtx11extras -skip qtxmlpatterns -skip qtactiveqt -skip qtremoteobjects -c++std c++1z -opensource -debug -D_GLIBCXX_DEBUG
mingw32-make -j9
```

Compilation fails & return with Error 1
No useful error message even in verbose mode

```
g++ -c -include .pch/debug/qt_gui_pch.h -fno-keep-inline-dllexport -g -Og -std=c++1z -fno-exceptions -Wall -Wextra -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -Wno-format-overflow -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DQT_NO_LINKED_LIST -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_USING_NAMESPACE -DQT_NO_FOREACH -DMD4C_USE_UTF8 -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_GUI_LIB -DQT_BUILDING_QT -D_CRT_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -DQT_DEPRECATED_WARNINGS_SINCE=0x060000 -DQT_CORE_LIB -DQT_CORE_LIB -DQT_NO_EXCEPTIONS -D_GLIBCXX_DEBUG -I. -I../3rdparty/md4c -I../3rdparty/zlib/src -I../3rdparty/VulkanMemoryAllocator -I../../include -I../../include/QtGui -I../../include/QtGui/5.14.2 -I../../include/QtGui/5.14.2/QtGui -Itmp -I.tracegen/debug -I../../include/QtCore/5.14.2 -I../../include/QtCore/5.14.2/QtCore -I../../include/QtCore -I.moc/debug -I../3rdparty/libpng -I../3rdparty/harfbuzz-ng/include -I../../mkspecs/win32-g++  -o .obj/debug/qaccessible.o accessible/qaccessible.cpp

mingw32-make[4]: *** [Makefile.Debug:15027: .obj/debug/qaccessible.o] Error 1
mingw32-make[4]: Leaving directory 'E:/compile/qt-everywhere-src-5.14.2/qtbase/src/gui'
```

Same issue happens compiling my own sources with lot of 3rd party header heavy dependencies using CMake & cotire for PCH generation.
Not Qt specific, fails only for too big pch files like 'qt_gui_pch.h' in this case.
There is no issue with the smaller ones even within Qt project.

```
$ find . -type f -name 'c++' -exec ls -s {} + | sort -k1
  1904 ./config.tests/precompile_header/.pch/header.h.gch/c++
 98544 ./qtbase/src/sql/.pch/debug/qt_pch.h.gch/c++
 98960 ./qtbase/src/network/.pch/debug/qt_pch.h.gch/c++
 99352 ./qtbase/src/concurrent/.pch/debug/qt_pch.h.gch/c++
 99440 ./qtbase/src/corelib/.pch/debug/qt_pch.h.gch/c++
134440 ./qtbase/src/gui/.pch/debug/qt_gui_pch.h.gch/c++
```

Maybe related issue:
* https://sourceforge.net/p/mingw-w64/bugs/382/
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56926#c16

##  Workaround

* manually remove pch usage by removing '-include .*\.h'
* turning off precompiled header usage (where possible)

Best Regards,
Gábor

**Comment by brechtsanders** [comment]
Hi,
I have also noticed QT5 will only build with MinGW-w64 if precompiled headers are not used, also when using other MinGW-w64 builds provided by others.
For me the `-no-pch` fixes it.
This is really something you should report to the GCC team.
Regards
Brecht

**Comment by SzGaa** [comment]
Previously I used the following compiler from the original minGW-W64 site:
* g++.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0

With this compiler I do not have the issue while compiling the Qt sources, it handles perfectly
the same sized PCH files:
```
$ g++ --version
g++.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0

$ find . -type f -name 'c++' -exec ls -s {} + | sort -k1
  1944 ./config.tests/precompile_header/.pch/header.h.gch/c++
 95528 ./qtbase/src/sql/.pch/debug/qt_pch.h.gch/c++
 95560 ./qtbase/src/platformsupport/fbconvenience/.pch/debug/qt_pch.h.gch/c++
 95560 ./qtbase/src/platformsupport/fontdatabases/.pch/debug/qt_pch.h.gch/c++
 95880 ./qtbase/src/network/.pch/debug/qt_pch.h.gch/c++
 96256 ./qtbase/src/concurrent/.pch/debug/qt_pch.h.gch/c++
 96344 ./qtbase/src/corelib/.pch/debug/qt_pch.h.gch/c++
130624 ./qtbase/src/gui/.pch/debug/qt_gui_pch.h.gch/c++
134760 ./qtbase/src/widgets/.pch/debug/qt_widgets_pch.h.gch/c++
```

Also that compiler handles correctly 500+MB PCH files generated for my own project.
That is why I thought it could be an issue with your personal build.

There is also a chance that it is an issue introduced in GCC9, but did not find anything about it...
Unfortunately I do not have time to do any further investigations.
In case I loose too much time due to the loss of 'precompiled header' functionality, I'll need to fall back to the older compiler :(

Anyway, thanks, for your quick response.

Best Regards,
Gábor

**Comment by brechtsanders** [comment]
My build doesn't change any of the GCC source code.
I just try to provide a build with as many of the optional dependancies and features.

Have you tried with my GCC 10 prerelease build?

**Comment by SzGaa** [comment]
> My build doesn't change any of the GCC source code.
> I just try to provide a build with as many of the optional dependancies and features.

Yes, your builds are really good to have. Its really time to upgrade from GCC 8.1..

I wanted you to know about this issue (as it was not listed on the known issues list, I thought that maybe you are unaware of it).
I already recompiled all my dependencies with this compiler, probably I'll be ok with your 9.3's build for this quarter year, I can wait for the stable release of GCC10.

Thanks for your personal builds.

**Comment by syncu2** [comment]
This problem still occurs for me when building Qt 6.3.0 with gcc 12. Also tried with gcc 11.3, same issue. Problems start when the cmake_pch.hxx.gch file is about 158 MB large. No error message is displayed - the gcc command simply fails with a non-zero exit code. Also, the Windows Event log lists an access violation by cc1plus.exe.

**Comment by luisdallos** [comment]
> PCH has had issues for as long as I can remember, see for example:
> 
>     * https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-gcc/0010-Fix-using-large-PCH.patch
The msys2 team commited in https://github.com/msys2/MINGW-packages/commit/52908ed an additional patch in order to fix PCH relocation issues.

https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-gcc/0021-PR14940-Allow-a-PCH-to-be-mapped-to-a-different-addr.patch

See also:

https://github.com/msys2/MINGW-packages/pull/11582#issuecomment-1123886775
https://gcc.gnu.org/pipermail/gcc-patches/2022-May/594556.html

**Comment by brechtsanders** [comment]
I tried that patch, but GCC still isn't able to build itself with the `--enable-libstdcxx-pch` flag.

**Comment by luisdallos** [comment]
Seeing that the msys2 team does apply both patches ([`0010-Fix-using-large-PCH.patch`](https://github.com/msys2/MINGW-packages/blob/247e7b1/mingw-w64-gcc/PKGBUILD#L136) and [`0021-PR14940-Allow-a-PCH-to-be-mapped-to-a-different-addr.patch`](https://github.com/msys2/MINGW-packages/blob/247e7b1/mingw-w64-gcc/PKGBUILD#L141)) but GCC [is built](https://github.com/msys2/MINGW-packages/blob/247e7b1/mingw-w64-gcc/PKGBUILD#L248) with the `--disable-libstdcxx-pch` flag.

Another thing is that in both unpatched (see [here](https://github.com/gcc-mirror/gcc/blob/5c69acb/gcc/config/i386/host-mingw32.cc#L182-L183)) and patched (see [here](https://github.com/msys2/MINGW-packages/blob/247e7b1/mingw-w64-gcc/0021-PR14940-Allow-a-PCH-to-be-mapped-to-a-different-addr.patch#L51-L52) and [here](https://github.com/msys2/MINGW-packages/blob/247e7b1/mingw-w64-gcc/0021-PR14940-Allow-a-PCH-to-be-mapped-to-a-different-addr.patch#L60-L61)) GCC 12.1.0, the `MapViewOfFileEx` function is called with a `size_t` argument (named `offset`) as the 4th parameter (`dwFileOffsetLow`, declared as `DWORD` [according to](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-mapviewoffileex#syntax) the official M$ documentation). This can be an issue in 64-bit Windows, where unlike the 32-bit wide `DWORD` data type, the `size_t` data type is 64-bit wide.
