### ISSUE TITLE
Feature request: '--enable-languages=c,c++,fortran,lto,objc,obj-c++,d,jit' consider to add 'go' support

### ISSUE THREAD

**Issue by tedli** [brechtsanders/winlibs_mingw#80]
Hi,

I wish there could be a 'go' support. I know the golang native compiler provided by official golang sdk is more widly used, and more robust.

I request this feature just for interest. I want to try a windows version gccgo. If it's not necessary for this project, feel to close this issue.

:blush:

**Comment by brechtsanders** [comment]
I would like that too, and have tried it in the past but got `not supported for this target` as a result.
Strangely the output of gcc-11.2.0's `configure` with `go`added to `--enable-languages` is:
```
The following requested languages could not be built: go
Supported languages are: c,brig,c,c++,d,fortran,jit,lto,objc,obj-c++
```
So there seems to be something wrong there.
I will have a go with a gcc 12 snapshot version, you never know...

**Comment by tedli** [comment]
Hi @brechtsanders ，

I got it, so the gcc upstream didn't port 'go' target to windows. Thanks for reply.

**Comment by brechtsanders** [comment]
Well, according to https://go.dev/doc/install/gccgo they did.
My first attempt with gcc 12 gave me precompiled header issues:
```
x86_64-w64-mingw32/libstdc++-v3/include/ext/enc_filebuf.h:63:1: fatal error: cannot write PCH file: required memory segment unavailable
```
Now trying a second time with `--disable-libstdcxx-pch`...

**Comment by brechtsanders** [comment]
Well, according to https://go.dev/doc/install/gccgo go is supported in gcc.

But even the gcc 12 snapshot build returns
```
The following requested languages could not be built: brig,go
Supported languages are: c,c,c++,d,fortran,jit,lto,objc,obj-c++
```

So it looks like it's not supported for MinGW...

**Comment by tedli** [comment]
It makes sense. Although I'm a completely layman about compiler, but as https://go.dev/doc/install/gccgo told, the go support of gcc is just a frontend, it's something like turns go source to an intermediate language, the rest things is about how to generate target code, it's MinGW's staff.

**Comment by brechtsanders** [comment]
Because you got me really curious I'm now trying to build with go disabling the MinGW blockage in `configure` like this:
```
patch -ulbf configure << EOF
@@ -3577,3 +3577,3 @@
 case "\${target}" in
-*-*-darwin* | *-*-cygwin* | *-*-mingw* | bpf-* )
+*-*-darwin* | *-*-cygwin* | bpf-* )
     unsupported_languages="\$unsupported_languages go"
@@ -3609,3 +3609,3 @@
        ;;
-    *-*-cygwin* | *-*-mingw*)
+    *-*-cygwin*)
        noconfigdirs="\$noconfigdirs target-libgo"
EOF
```
Completely unsupported of course, but I just want to know if it builds at all...

**Comment by brechtsanders** [comment]
Final conclusion: libgo (part of gcc build with go support) fails with:
```
libgo/sysinfo.c:19:10: fatal error: ucontext.h: No such file or directory
   19 | #include <ucontext.h>
      |          ^~~~~~~~~~~~
```
Unfortunately there is no `ucontext.h` on Windows or in MinGW.
So until the gcc team uses an alternative for this go won't build.

**Comment by tedli** [comment]
Hi @brechtsanders ,

I noticed that the `git-for-windows` team did something that may give us some luck.

https://github.com/git-for-windows/git-sdk-64/blob/main/usr/include/sys/resource.h
https://github.com/git-for-windows/git-sdk-64/blob/main/usr/include/ucontext.h

Hope I didn't get it wrong.

**Comment by brechtsanders** [comment]
I already tried with this earlier: https://github.com/zuzuf/freeocl/tree/master/libs/win32.64_ucontext but still wasn't able to build...
