### ISSUE TITLE
gdb cannot stop process

### ISSUE THREAD

**Issue by Logrus12** [brechtsanders/winlibs_mingw#82]
In codeblocks, when i try to debug programm with gdb, it cannot stop process (Trying to interrupt process with pid:), (redist mingw-w64 ucrt), but it seems that problem maybe not in gdb itself. When i manually launch and attach gdb to notepad, it can handle and stop it.

**Comment by brechtsanders** [comment]
I use gdb in Code::Blocks all the time and have not been able to reproduce this.
Which version of Code::Blocks are you using? Could you try with a more recent nightly build?

**Comment by Logrus12** [comment]
I use codeblocks 20.03(32-bit) and GCC 11.2.0 + LLVM/Clang/LLD/LLDB 13.0.0 + MinGW-w64 9.0.0 (UCRT), latest with console application. In code blocks compilers set as gcc g++ and other default apps from the bin folder of this mingw. Debugger set as gdb from bin folder.

**Comment by brechtsanders** [comment]
A new GDB (11.2) was just released and I published a new build caontaining this new GDB.
Can you try with this release to see if if was maybe a bug that is already fixed in GDB?
https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.2.0-9.0.0-ucrt-r4

**Comment by Logrus12** [comment]
Thanks! Debugger in  last version
 [https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.2.0-9.0.0-ucrt-r5](url)
 works correctly with Code::Blocks in windows
