### ISSUE TITLE
Commandline parsing

### ISSUE THREAD

**Issue by kayhayen** [brechtsanders/winlibs_mingw#84]
Hello,

I am using winlibs gcc for Nuitka, and I have encountered issues with the command line expansion of arguments. We are parsing Python command lines, and there you can say `--filenames *.py` and on Windows with python.exe on CMD and other shells, no quoting is needed. With MinGW64 and Clang too, this ends up as something that `argparse` and `optparse` fail to understand.

As an aside, I recently switching to `-m unicode`, but I have had reproducible crashes when patterns match without that, not with it, but these crashes were inside the unwanted code.

Is there a way to disable this behavior? I assume it's added on Windows such that things are more compatible with Linux, but I would like to not have it. Actually in `sys.argv` there shoud be `["--filenames", "*.py"]`. Currently only MSVC gives us that.

I am dealing with Python beginners here, some of which don't know what escaping or quoting is and why things are different from the standard Python. And in at last one case, a user is aiming at replacing a program that is called by another one outside of his control, that doesn't do quoting.

Please advise. Is this a compile time option. Is there a function that I need to overload in C runtime, and then I can disable it that way, any idea would be helpful.

Otherwise thanks for the fantastic job. I am able to LTO/PGO with MinGW64 from your winlibs work, and that's fantastic, and a first to me.

**Comment by brechtsanders** [comment]
Seems like a globbing issue. File globbing is indeed not the same on Windows as on other systems like Linux.

I read [somewhere](https://gcc.gnu.org/legacy-ml/gcc-patches/2017-01/msg01299.html) that linking with `x86_64-w64-mingw32/lib/CRT_glob.o` or `x86_64-w64-mingw32/lib/CRT_noglob.o` can be used to use the different globbing settings.

**Comment by kayhayen** [comment]
So, I tried to add the noglob object to the command line, but it didn't change anything. I just added the object file to the linker command line, not sure where to put it, since of course the CRT library is always last, I am not sure if with traditional logic it would be used.

Then I googled for the source of this module, looking for a function to overload, and I came across this:

https://github.com/Alexpux/mingw-w64/blob/master/mingw-w64-crt/crt/wildcard.c

The comment there suggests that `int _dowildcard = -1;` and `int _dowildcard = 0;` should control things, but for me they do not change the behaviour, globing still occurs. Am I on the right track with that then, I didn't see any effect.

Seeing you got this in your configure for winlibs there is `--enable-mingw-wildcard` would that override what I am attempting, and not allow the disable?

**Comment by kayhayen** [comment]
Actually checking some more, I found that `extern int _dowildcard` passes  an assert and seems to default to `-1` indeed. But me setting it on the top level to `0` seems to not impact the runtime. I even disabled LTO, just in case, there have been bugs with it before, but it changes nothing either. I think I need you to help me here. I do not understand which parts of the code get used here, but from looking at it, it seems I should be able to overload it, but then I am not?

**Comment by kayhayen** [comment]
I should be ashamed, I originally testing this with `cmd.exe` but now I forgot about it, and did all the things with Git bash.... and you can probably tell what that means, false alarms, it works with the integer set in the main program as desired. Sorry for wasting your time with my previous comments.

**Comment by brechtsanders** [comment]
Glad to help.
