### ISSUE TITLE
Is there any way to generate a gcc version with SJLJ rather than ssh for x86_64 and posix ?

### ISSUE THREAD

**Issue by hermosayhl** [brechtsanders/winlibs_mingw#86]
winlibs-x86_64-posix-**seh**-gcc-11.2.0-mingw-w64ucrt-9.0.0-r4.zip

to 

winlibs-x86_64-posix-**sjlj**-gcc-11.2.0-mingw-w64ucrt-9.0.0-r4.zip

**Comment by brechtsanders** [comment]
This was already discussed in #4  where we settled on:
- 32-bit: dwarf
- 64-bit: SEH
