### ISSUE TITLE
Include GLEW

### ISSUE THREAD

**Issue by Zero3K** [brechtsanders/winlibs_mingw#91]
It would be nice if it included the GLEW component from MSYS2 so more applications could be compiled using it.

**Comment by brechtsanders** [comment]
MSYS2 is the _build_ environment, its components should not be linked to your MinGW-w64 target output.
The idea is to limit the winlibs toolchain to just the compiler tools, and to make a separate build and/or packaging system (https://github.com/brechtsanders/winlibs_tools/) for many different packages (https://github.com/brechtsanders/winlibs_recipes/).

Together this will be the winlibs ecosystem, but it's still somewhat a work in progress right now and it still needs an easy setup manual and/or installer.

But I can already tell you glew is included in this. The build recipe can be found here: https://github.com/brechtsanders/winlibs_recipes/blob/main/recipes/glew.winlib
