### ISSUE TITLE
Running C++ files don't produce any output

### ISSUE THREAD

**Issue by RevengerWizard** [brechtsanders/winlibs_mingw#92]
Hi, I downloaded the latest version of winlibs_mingw using Chocolatey as installer. 

Compiling C files using GCC works as expected and without any problems, but trying to compile C++ files using G++ and trying to run them doesn't produce any visible output. I tried using the C headers and functions and it worked.

My latest version of both GCC and G++ is 11.2.0

**Comment by brechtsanders** [comment]
Do you have a minimal reproducible example to illustrate your issue?

Are you sure you compiled as a console application?

**Comment by RevengerWizard** [comment]
After trying compile again the file, it now outputs correctly to the console. I guess it was something I've done wrong earlier.

**Comment by lightmon233** [comment]
I got this issue now and I dont know how to fix it out

**Comment by lightmon233** [comment]
![image](https://github.com/brechtsanders/winlibs_mingw/assets/56477197/7cea1e19-d658-4b1d-a652-26192d754a19)
It's a very simple program, the 2018 version mingw works properly, but mingw winlibs the latest version does not. the program is right, but the exe file cannot be executed or there is some problems

**Comment by lightmon233** [comment]
my environment is windows11 22H2

**Comment by lightmon233** [comment]
> Can you please try with the latest GCC13 release?

tried lately but still the same problem

**Comment by lightmon233** [comment]
I used a 2018 version mingw and the problem disappered which is soooo weird
