### ISSUE TITLE
There may be a problem with lldb.exe

### ISSUE THREAD

**Issue by F7kyyy** [brechtsanders/winlibs_mingw#93]
Dear winlibs friends

I am very pleasantly surprised to find this project. The version I use is `GCC 11.2.0 + LLVM/Clang/LLD/LLDB 14.0.0 + MinGW-w64 9.0.0 (UCRT) - release 7   (LATEST)`.When I type `lldb` in powershell, the result is
```I could't use lldb to debug my c++ program.
Python path configuration:
  PYTHONHOME = 'D:/Prog/winlibs64ucrt_stage/custombuilt/share/python/bin'
  PYTHONPATH = (not set)
  program name = 'C:\Users\FengisZZZ\ServerTools\mingw64\bin\libpython3.9.dll'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\Users\\FengisZZZ\\ServerTools\\mingw64\\bin\\libpython3.9.dll'
  sys.base_prefix = 'D:/Prog/winlibs64ucrt_stage/custombuilt/share/python/bin'
  sys.base_exec_prefix = 'D:\\Prog\\winlibs64ucrt_stage\\custombuilt\\share\\python\\bin'
  sys.platlibdir = 'lib'
  sys.executable = 'C:\\Users\\FengisZZZ\\ServerTools\\mingw64\\bin\\libpython3.9.dll'
  sys.prefix = 'D:/Prog/winlibs64ucrt_stage/custombuilt/share/python/bin'
  sys.exec_prefix = 'D:\\Prog\\winlibs64ucrt_stage\\custombuilt\\share\\python\\bin'
  sys.path = [
    'D:\\Prog\\winlibs64ucrt_stage\\custombuilt\\share\\python\\bin\\lib\\python39.zip',
    'D:/Prog/winlibs64ucrt_stage/custombuilt/share/python/bin\\lib\\python3.9',
    'D:\\Prog\\winlibs64ucrt_stage\\custombuilt\\share\\python\\bin\\lib\\python3.9\\lib-dynload',
    '',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000035a8 (most recent call first):
<no Python frame>
```
I could't use lldb to debug my c++ program at the same time. I could only find release 2 to replace on the website, and the lldb of release 2 could be used normally,but the clangd version is only 12.0.

Best regard
F7kyyy

**Comment by F7kyyy** [comment]
> In the mean time I noticed the files are not missing, but rather the Python library is looking in the wrong place. When setting the environment variable `PYTHONPATH` to the full path of `mingw64/lib/python3.9` I do get the `lldb` prompt.

Thank you for your prompt reply.I set the environment variable `PYTHONPATH` to the full path of mingw64/lib/python3.9 as you say. Although I get the `lldb` prompt , it still get the error like
```
PS C:\Users\FengisZZZ> lldb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users/FengisZZZ/ServerTools/mingw64/lib/python3.9/site-packages\lldb\__init__.py", line 99, in <module>
    import six
  File "C:\Users/FengisZZZ/ServerTools/mingw64/lib/python3.9/site-packages\six.py", line 644, in <module>
    import struct
  File "C:\Users\FengisZZZ\ServerTools\mingw64\lib\python3.9\struct.py", line 13, in <module>
    from _struct import *
ModuleNotFoundError: No module named '_struct'
(lldb)
```
I still could't use the debug function of lldb in visual studio code. Breakpoint on program doesn't seem to work

**Comment by kouhe3** [comment]
yes.same here.
 I can't hit breakpoint.
and
`No module named '_struct'`

**Comment by brechtsanders** [comment]
There was a Python issue in the first release (see #98)
Is it better with the new release https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.3.0-14.0.1-10.0.0-ucrt-r2?

**Comment by InchChou** [comment]
> There was a Python issue in the first release (see #98) Is it better with the new release https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.3.0-14.0.1-10.0.0-ucrt-r2?

when I typed `lldb -v` in my console, there is still an error:
```powershell
> lldb -v
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\PortablePrograms/mingw64/lib/python3.9/site-packages\lldb\__init__.py", line 99, in <module>
    import six
  File "D:\PortablePrograms/mingw64/lib/python3.9/site-packages\six.py", line 644, in <module>
    import struct
  File "D:\PortablePrograms\mingw64\lib\python3.9\struct.py", line 13, in <module>
    from _struct import *
ModuleNotFoundError: No module named '_struct'
lldb version 14.0.1
```

**Comment by brechtsanders** [comment]
After a lot of searching I found that somehow lldb was statically linking with the Python library and that somehow messed up the Python path detection in lldb. I just released a new build where lldb links to the shared Python library.

* https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.3.0-14.0.3-10.0.0-msvcrt-r3
* https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.3.0-14.0.3-10.0.0-ucrt-r3

Can you please check if it also solves the issue on your end?

**Comment by kouhe3** [comment]
winlibs-x86_64-posix-seh-gcc-11.3.0-llvm-14.0.3-mingw-w64ucrt-10.0.0-r3

lldb works on my machine

**Comment by brechtsanders** [comment]
Excellent. Thanks!
