### ISSUE TITLE
Github actions can't find old tags

### ISSUE THREAD

**Issue by Craig44** [brechtsanders/winlibs_mingw#94]
Hi there,

We have been using the gcc tag `10.3.1-snapshot20211112-9.0.0-ucrt-r1` in our C++ project. But our recent [github action](https://github.com/NIWAFisheriesModelling/CASAL2/runs/5729307220?check_suite_focus=true) has failed to install this gcc tag. The error is below it looks like the github action looks at the latest 30 tags? 

```
does not exist. Possible tags are:
  12.0.1-snapshot20220123-9.0.0-msvcrt-r1
  12.0.0-snapshot20211205-9.0.0-msvcrt-r1
  11.2.1-snapshot20220219-9.0.0-ucrt-r1
  11.2.1-snapshot20211211-9.0.0-ucrt-r1
  11.2.1-snapshot20211204-9.0.0-msvcrt-r1
  11.2.1-snapshot20211106-9.0.0-ucrt-r1
  11.2.1-snapshot20211030-9.0.0-ucrt-r1
  11.2.1-snapshot20210918-9.0.0-ucrt-r1
  11.2.1-snapshot20210814-9.0.0-r1
  11.2.0-9.0.0-ucrt-r5
  11.2.0-9.0.0-ucrt-r4
  11.2.0-9.0.0-ucrt-r3
  11.2.0-9.0.0-ucrt-r1
  11.2.0-9.0.0-msvcrt-r6
  11.2.0-9.0.0-msvcrt-r5
  11.2.0-9.0.0-msvcrt-r4c
  11.2.0-14.0.0-9.0.0-ucrt-r7
  11.2.0-14.0.0-9.0.0-msvcrt-r7
  11.2.0-13.0.0-9.0.0-ucrt-r2
  11.2.0-13.0.0-9.0.0-msvcrt-r3
  11.2.0-12.0.1-9.0.0-r1
  11.1.1-snapshot20210710-r1
  11.1.1-snapshot20210[60](https://github.com/NIWAFisheriesModelling/CASAL2/runs/5729307220?check_suite_focus=true#step:5:60)5-9.0.0-r1
  11.1.0-8.0.0-r2
  11.1.0-8.0.0-r1
  11.1.0-12.0.0-9.0.0-r3
  11.1.0-12.0.0-9.0.0-r2
  11.1.0-12.0.0-9.0.0-r1
  11.1.0-12.0.0-8.0.2-r1
  11.0.0-snapshot20210404-r1
```

**Comment by brechtsanders** [comment]
Seems like a an issue that you should take up with github.

Why would you build with a snapshot version instead of a release version?

**Comment by Craig44** [comment]
Thanks for replying. I will close the issue, was hoping you had come across this before but I will head towards github actions.

We have found differences between compilers in our unit-tests. So in order to reduce time investigating compiler differences, we wanted to freeze a version.
