### ISSUE TITLE
gcc-11.3.0-llvm-14.0.1-mingw-w64ucrt-10.0.0-r1 pretty-printing is disable

### ISSUE THREAD

**Issue by 233lol** [brechtsanders/winlibs_mingw#98]
GCC 11.2.0 + LLVM/Clang/LLD/LLDB 14.0.0 + MinGW-w64 9.0.0 (UCRT) - release 7 pretty-printing is enable but gcc-11.3.0-llvm-14.0.1-mingw-w64ucrt-10.0.0-r1 pretty-printing is disable.

**Comment by brechtsanders** [comment]
In which program(s) exactly? gdb, gcc/g++ ?

**Comment by 233lol** [comment]
> In which program(s) exactly? gdb, gcc/g++ ?

when I use vscode debug program, gdb's pretty-printing is disabl. so I back to GCC 11.2.0 + LLVM/Clang/LLD/LLDB 14.0.0 + MinGW-w64 9.0.0 (UCRT) - release 7. It's pretty-printing is enable.

**Comment by InchChou** [comment]
when I open gdb in

**Comment by brechtsanders** [comment]
That's strange: gdb was built with `--enable-source-highlight` and `gdb.exe` depends on `libsource-highlight-4.dll`.

Maybe it's related to the recent addition of the file `share/gdb/gdbinit` (see also #2).

Could you try to adding the `color functions` section from https://github.com/gdbinit/Gdbinit/blob/master/gdbinit to the file `share/gdb/gdbinit` (under `mingw32` or `mingw64`) to see if that changes anything for you?

You could also try to delete/rename that file to see if that makes a difference.

**Comment by brechtsanders** [comment]
Can you check if it works better in this new release https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.3.0-14.0.1-10.0.0-ucrt-r2 ?

**Comment by InchChou** [comment]
> That's strange: gdb was built with `--enable-source-highlight` and `gdb.exe` depends on `libsource-highlight-4.dll`.
> 
> Maybe it's related to the recent addition of the file `share/gdb/gdbinit` (see also #2).
> 
> Could you try to adding the `color functions` section from https://github.com/gdbinit/Gdbinit/blob/master/gdbinit to the file `share/gdb/gdbinit` (under `mingw32` or `mingw64`) to see if that changes anything for you?
> 
> You could also try to delete/rename that file to see if that makes a difference?

I tried to adding the `color functions` section into the file `share/gdb/gdbinit`, it doesn't work.



> Can you please check if it works better in this new release https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.3.0-14.0.1-10.0.0-ucrt-r2 ?

This realese works fine, thanks.

**Comment by 233lol** [comment]
> 您能否检查一下它在这个新版本中是否更好用https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.3.0-14.0.1-10.0.0-ucrt-r2？
This realese's pretty-printing is enable, thanks.
