### ISSUE TITLE
Will there be lldb-mi?

### ISSUE THREAD

**Issue by InchChou** [brechtsanders/winlibs_mingw#99]
When I download the releases include with LLVM/Clang/LLD/LLDB, I can't find the lldb-mi.exe. While debug with VSCode under lldb, it is required. Do you have a plan to compile lldb-mi? Thanks.

**Comment by xtemp09** [comment]
LLDB does not work in this toolchain. I've just checked the latest version ― still not working.

**Comment by brechtsanders** [comment]
I know, it is related to Python not locating things correctly relative to the current executable.
I resolved this same issue in gdb by tweaking Python, but somehow the same tweak doesn't do the trick (yet) for lldb. I need some more time to look into this.

**Comment by brechtsanders** [comment]
The Python issue is solved now.

Apparently lldb-mi isn't built as part of the LLVM project.

Is https://github.com/lldb-tools/lldb-mi what I should try to build and include in future releases, or is there another place to get it?

**Comment by brechtsanders** [comment]
I have added .zip files with first attempt to build lldb-mi to the latest release:

* MSVCRT
  * 32-bit: https://github.com/brechtsanders/winlibs_mingw/releases/download/11.3.0-14.0.3-10.0.0-msvcrt-r3/lldb-mi.32msvcrt.zip
  * 64-bit: https://github.com/brechtsanders/winlibs_mingw/releases/download/11.3.0-14.0.3-10.0.0-msvcrt-r3/lldb-mi.64msvcrt.zip
* UCRT
  * 32-bit: https://github.com/brechtsanders/winlibs_mingw/releases/download/11.3.0-14.0.3-10.0.0-ucrt-r3/lldb-mi.32ucrt.zip
  * 64-bit: https://github.com/brechtsanders/winlibs_mingw/releases/download/11.3.0-14.0.3-10.0.0-ucrt-r3/lldb-mi.64ucrt.zip

Can you unzip what you need in the same place you unzipped the main file and see if that fixes it for you?

**Comment by InchChou** [comment]
> The Python issue is solved now. #93
> 
> Apparently lldb-mi isn't built as part of the LLVM project.
> 
> Is https://github.com/lldb-tools/lldb-mi what I should try to build and include in future releases, or is there another place to get it?

Yes, it's exactly what we need to include.

> I have added .zip files with first attempt to build lldb-mi to the latest release:
> 
> * MSVCRT
>   
>   * 32-bit: https://github.com/brechtsanders/winlibs_mingw/releases/download/11.3.0-14.0.3-10.0.0-msvcrt-r3/lldb-mi.32msvcrt.zip
>   * 64-bit: https://github.com/brechtsanders/winlibs_mingw/releases/download/11.3.0-14.0.3-10.0.0-msvcrt-r3/lldb-mi.64msvcrt.zip
> * UCRT
>   
>   * 32-bit: https://github.com/brechtsanders/winlibs_mingw/releases/download/11.3.0-14.0.3-10.0.0-ucrt-r3/lldb-mi.32ucrt.zip
>   * 64-bit: https://github.com/brechtsanders/winlibs_mingw/releases/download/11.3.0-14.0.3-10.0.0-ucrt-r3/lldb-mi.64ucrt.zip
> 
> Can you unzip what you need in the same place you unzipped the main file and see if that fixes it for you?

I unzip it and put it together with [GCC 11.3.0 + LLVM 14.0.3 + MinGW-w64 10.0.0 UCRT (release 3)](https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.3.0-14.0.3-10.0.0-ucrt-r3), it works fine.

Thanks for all your efforts.

**Comment by brechtsanders** [comment]
Great. I will include lldb-mi in future releases.
